### ISSUE TITLE
hang on cmrcx/test_ucp_mmap.alloc/0

### ISSUE THREAD

**Issue by alinask** [openucx/ucx#1058]
Passes on the test nodes but doesn't on our compute nodes:

alinas@vegas26 ~/workspace/ucx
$./test/gtest/gtest --gtest_filter=cmrcx/test_ucp_mmap.alloc/0
[     INFO ] checking dc: yes
[     INFO ] checking dcx: yes
[     INFO ] checking ud: yes
[     INFO ] checking udx: yes
[     INFO ] checking udrc: yes
[     INFO ] checking cmrcx: yes
[     INFO ] checking shm: yes
[     INFO ] checking udrcx: yes
[     INFO ] checking ugni: no
[     INFO ] checking self: yes
[     INFO ] checking rc: yes
[     INFO ] checking rc_x: yes
[     INFO ] checking ud_mlx5: yes
[     INFO ] checking all: yes
[     INFO ] Using random seed of 3927
Note: Google Test filter = cmrcx/test_ucp_mmap.alloc/0
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from cmrcx/test_ucp_mmap
[ RUN      ] cmrcx/test_ucp_mmap.alloc/0
... hang ...

hangs on the disconnect flow:

```
$gstack 13492
Thread 2 (Thread 0x7ffff5250700 (LWP 13517)):
#0  0x00007ffff5c0f2c3 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007ffff7ad1418 in ucs_async_thread_func (arg=0x0) at async/thread.c:62
#2  0x00007ffff6b0edc5 in start_thread () from /usr/lib64/libpthread.so.0
#3  0x00007ffff5c0eced in clone () from /usr/lib64/libc.so.6
Thread 1 (Thread 0x7ffff7fc9740 (LWP 13492)):
#0  0x0000000000541dc8 in ucs::handle<ucp_worker*>::operator ucp_worker* (this=0x2ca2d38) at ./common/test_helpers.h:277
#1  0x0000000000540eb2 in ucp_test_base::entity::progress (this=0x2ca2d20) at ucp/ucp_test.cc:340
#2  0x000000000053eeef in ucp_test::progress (this=0x2c92000) at ucp/ucp_test.cc:80
#3  0x000000000053f168 in ucp_test::wait (this=0x2c92000, req=0x2e0b2f0) at ucp/ucp_test.cc:107
#4  0x000000000053f0d3 in ucp_test::disconnect (this=0x2c92000, entity=...) at ucp/ucp_test.cc:96
#5  0x000000000053ed14 in ucp_test::cleanup (this=0x2c92000) at ucp/ucp_test.cc:44
#6  0x0000000000440f0f in ucs::test_base::TearDownProxy (this=0x2c92000) at common/test.cc:122
#7  0x00000000004db8ea in ucp_test::TearDown (this=0x2c92000) at ucp/ucp_test.h:72
#8  0x000000000042fbbe in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void> (object=0x2c92058, method=&virtual testing::Test::TearDown(), location=0x65ef01 "TearDown()") at common/gtest-all.cc:3562
#9  0x000000000042ad9c in testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=0x2c92058, method=&virtual testing::Test::TearDown(), location=0x65ef01 "TearDown()") at common/gtest-all.cc:3598
#10 0x000000000041215a in testing::Test::Run (this=0x2c92058) at common/gtest-all.cc:3643
#11 0x00000000004128ee in testing::TestInfo::Run (this=0x2b76900) at common/gtest-all.cc:3812
#12 0x0000000000412f7e in testing::TestCase::Run (this=0x2b76a20) at common/gtest-all.cc:3930
#13 0x0000000000419776 in testing::internal::UnitTestImpl::RunAllTests (this=0x29a3760) at common/gtest-all.cc:5802
#14 0x0000000000430f9c in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x29a3760, method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x4194f8 <testing::internal::UnitTestImpl::RunAllTests()>, location=0x65f7d0 "auxiliary test code (environments or event listeners)") at common/gtest-all.cc:3562
#15 0x000000000042bbfe in testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x29a3760, method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x4194f8 <testing::internal::UnitTestImpl::RunAllTests()>, location=0x65f7d0 "auxiliary test code (environments or event listeners)") at common/gtest-all.cc:3598
#16 0x00000000004183b2 in testing::UnitTest::Run (this=0x9a12a0 <testing::UnitTest::GetInstance()::instance>) at common/gtest-all.cc:5416
#17 0x000000000043a203 in RUN_ALL_TESTS () at common/gtest.h:20058
#18 0x000000000043a130 in main (argc=1, argv=0x7fffffffded8) at common/main.cc:79
```

**Comment by yosefe** [comment]
similar hang in http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/2647/label=hpc-test-node2/console:
```
01:13:24 [       OK ] cmrcx/test_ucp_tag_mt.send_recv/3 (1583 ms)
01:13:24 [ RUN      ] cmrcx/test_ucp_tag_mt.send_recv/0
01:13:30 [       OK ] cmrcx/test_ucp_tag_mt.send_recv/0 (6574 ms)
01:13:30 [ RUN      ] cmrcx/test_ucp_tag_mt.send_recv/1
01:13:37 make: *** [test_valgrind] Killed
01:13:37 
```

**Comment by yosefe** [comment]
not reproduced after ~11k iterations
