### ISSUE TITLE
hang on rc and dc with the bsendpending test

### ISSUE THREAD

**Issue by alinask** [openucx/ucx#1287]
There is a hang that happens on a large scale with the bsendpending test but it can also be reproduced on 2 ranks with 2 hosts.
It passes with ud and with mm (when running on one host with ppn=32). hangs only on rc and dc.

To reproduce with 2 ranks:

/hpc/local/benchmarks/hpcx_install_Wednesday/hpcx-gcc-redhat7.2/ompi-v2.x/bin/mpirun -np 2 -mca btl_openib_warn_default_gid_prefix 0 --bind-to core --tag-output --timestamp-output --display-map -mca pml ucx -x UCX_SHM_DEVICES=all -x UCX_NET_DEVICES=mlx5_0:1 -x UCX_ACC_DEVICES=all -mca btl_openib_if_include mlx5_0:1 -mca coll_hcoll_enable 0 -x UCX_IB_ADDR_TYPE=ib_local -x UCX_TLS=rc -mca opal_pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0 --map-by node /hpc/scrap/users/mtt/scratch/ucx_ompi/20170128_120403_29638_78793_clx-hercules-065/installs/aTIq/tests/mpich_tests/mpich-mellanox.git/test/mpi/pt2pt/bsendpending

Trace from the 2 hosts:
```
[alinas@clx-hercules-001 ~]$ gstack 15282
Thread 4 (Thread 0x7ffff4354700 (LWP 15283)):
#0  0x00007ffff76307a3 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007ffff702c933 in epoll_dispatch (base=0x67e170, tv=<optimized out>) at epoll.c:407
#2  0x00007ffff7030380 in opal_libevent2022_event_base_loop (base=base@entry=0x67e170, flags=flags@entry=1) at event.c:1630
#3  0x00007ffff43862ad in progress_engine (obj=0x67e170) at src/util/progress_threads.c:52
#4  0x00007ffff7902dc5 in start_thread () from /usr/lib64/libpthread.so.0
#5  0x00007ffff76301cd in clone () from /usr/lib64/libc.so.6
Thread 3 (Thread 0x7ffff3b53700 (LWP 15284)):
#0  0x00007ffff76307a3 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007ffff702c933 in epoll_dispatch (base=0x67f670, tv=<optimized out>) at epoll.c:407
#2  0x00007ffff7030380 in opal_libevent2022_event_base_loop (base=0x67f670, flags=flags@entry=1) at event.c:1630
#3  0x00007ffff6ff512e in progress_engine (obj=<optimized out>) at runtime/opal_progress_threads.c:105
#4  0x00007ffff7902dc5 in start_thread () from /usr/lib64/libpthread.so.0
#5  0x00007ffff76301cd in clone () from /usr/lib64/libc.so.6
Thread 2 (Thread 0x7fffea9d3700 (LWP 15292)):
#0  0x00007ffff76307a3 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007fffeac1f845 in ucs_async_thread_func (arg=0x93bb50) at async/thread.c:91
#2  0x00007ffff7902dc5 in start_thread () from /usr/lib64/libpthread.so.0
#3  0x00007ffff76301cd in clone () from /usr/lib64/libc.so.6
Thread 1 (Thread 0x7ffff7fb5740 (LWP 15282)):
#0  0x00007ffff707c263 in opal_sys_timer_get_cycles () at ../../../../opal/include/opal/sys/amd64/timer.h:42
#1  opal_timer_base_get_usec_sys_timer () at timer_linux_component.c:221
#2  0x00007ffff6ff0da9 in opal_progress () at runtime/opal_progress.c:197
#3  0x00007ffff7b5a31d in ompi_request_wait_completion (req=0xac7008) at ../ompi/request/request.h:398
#4  ompi_request_default_wait (req_ptr=0x7fffffffbf20, status=0x0) at request/req_wait.c:41
#5  0x00007fffeb5a0b5a in mca_pml_ucx_send (buf=0x7ffff7efb010, count=131072, datatype=<optimized out>, dst=<optimized out>, tag=<optimized out>, mode=<optimized out>, comm=0x60e7e0 <ompi_mpi_comm_world>) at pml_ucx.c:631
#6  0x00007ffff7b6a4a5 in PMPI_Bsend (buf=<optimized out>, count=<optimized out>, type=<optimized out>, dest=<optimized out>, tag=<optimized out>, comm=0x60e7e0 <ompi_mpi_comm_world>) at pbsend.c:79
#7  0x0000000000402807 in main ()
```

```
[alinas@clx-hercules-002 ~]$ gstack 26005
Thread 4 (Thread 0x7ffff4354700 (LWP 26006)):
#0  0x00007ffff76307a3 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007ffff702c933 in epoll_dispatch (base=0x67e170, tv=<optimized out>) at epoll.c:407
#2  0x00007ffff7030380 in opal_libevent2022_event_base_loop (base=base@entry=0x67e170, flags=flags@entry=1) at event.c:1630
#3  0x00007ffff43862ad in progress_engine (obj=0x67e170) at src/util/progress_threads.c:52
#4  0x00007ffff7902dc5 in start_thread () from /usr/lib64/libpthread.so.0
#5  0x00007ffff76301cd in clone () from /usr/lib64/libc.so.6
Thread 3 (Thread 0x7ffff3b53700 (LWP 26007)):
#0  0x00007ffff76307a3 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007ffff702c933 in epoll_dispatch (base=0x67f670, tv=<optimized out>) at epoll.c:407
#2  0x00007ffff7030380 in opal_libevent2022_event_base_loop (base=0x67f670, flags=flags@entry=1) at event.c:1630
#3  0x00007ffff6ff512e in progress_engine (obj=<optimized out>) at runtime/opal_progress_threads.c:105
#4  0x00007ffff7902dc5 in start_thread () from /usr/lib64/libpthread.so.0
#5  0x00007ffff76301cd in clone () from /usr/lib64/libc.so.6
Thread 2 (Thread 0x7fffea9d3700 (LWP 26015)):
#0  0x00007ffff76307a3 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007fffeac1f845 in ucs_async_thread_func (arg=0x93bb50) at async/thread.c:91
#2  0x00007ffff7902dc5 in start_thread () from /usr/lib64/libpthread.so.0
#3  0x00007ffff76301cd in clone () from /usr/lib64/libc.so.6
Thread 1 (Thread 0x7ffff7fb5740 (LWP 26005)):
#0  0x00007ffff707c263 in opal_sys_timer_get_cycles () at ../../../../opal/include/opal/sys/amd64/timer.h:42
#1  opal_timer_base_get_usec_sys_timer () at timer_linux_component.c:221
#2  0x00007ffff6ff0da9 in opal_progress () at runtime/opal_progress.c:197
#3  0x00007ffff7b5a31d in ompi_request_wait_completion (req=0xac7008) at ../ompi/request/request.h:398
#4  ompi_request_default_wait (req_ptr=0x7fffffffbf50, status=0x0) at request/req_wait.c:41
#5  0x00007ffff7b73a52 in PMPI_Sendrecv (sendbuf=0x0, sendcount=0, sendtype=0x60d3e0 <ompi_mpi_unsigned_char>, dest=0, sendtag=10, recvbuf=<optimized out>, recvcount=0, recvtype=0x60d3e0 <ompi_mpi_unsigned_char>, source=0, recvtag=10, comm=0x60e7e0 <ompi_mpi_comm_world>, status=0x0) at psendrecv.c:92
#6  0x00000000004029ca in main ()
```

**Comment by yosefe** [comment]
see https://github.com/open-mpi/ompi/pull/3020
