### ISSUE TITLE
Hang in different tests with HW TM

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#1693]
Hang is reproduced on both large and small scales.

Devices: `mlx5_4:1 (4119)` on Orion, `mlx5_2:1` on Hercules
MOFED: `MLNX_OFED_LINUX-4.1-1.0.2.0`

3 ranks `large_message`: http://e2e-gw.mellanox.com:4080//hpc/scrap/users/mtt/scratch/ucx_ompi/20170713_073528_19243_4300_clx-orion-035/html/test_stdout_2TS3_m.txt
256 ranks `nbicalltoall`: http://e2e-gw.mellanox.com:4080//hpc/scrap/users/mtt/scratch/ucx_ompi/20170712_195920_31383_4224_clx-hercules-055/html/test_stdout_ehFfKS.txt
112 ranks `IMB-MPI1`: http://e2e-gw.mellanox.com:4080//hpc/scrap/users/mtt/scratch/ucx_ompi/20170713_050453_6469_4290_clx-orion-002/html/test_stdout_a7kVFQ.txt

Reproduction and trace:
```
MTT_TEST_SID=/hpc/scrap/users/mtt/scratch/ucx_ompi/20170713_073528_19243_4300_clx-orion-035/run_test_48.sbatch
/tmp/aHcPPNrKWH: line 41: ulimit: core file size: cannot modify limit: Operation not permitted
+ date
Thu Jul 13 08:35:31 IDT 2017
+ /hpc/local/benchmarks/hpcx_install_Wednesday/hpcx-gcc-redhat7.2/ompi-v2.x/bin/mpirun -np 3 -mca btl_openib_warn_default_gid_prefix 0 --debug-daemons --bind-to core --tag-output --timestamp-output --display-map -mca pml ucx -x UCX_NET_DEVICES=mlx5_4:1 -mca btl_openib_if_include mlx5_4:1 -mca coll_hcoll_enable 0 -x UCX_TLS=rc,sm -x UCX_RC_VERBS_TM_ENABLE=y -mca opal_pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0 --map-by node /hpc/scrap/users/mtt/scratch/ucx_ompi/20170713_073528_19243_4300_clx-orion-035/installs/o1Bb/tests/mpich_tests/mpich-mellanox.git/test/mpi/pt2pt/large_message
Daemon [[32140,0],2] checking in as pid 8021 on host clx-orion-044
Daemon [[32140,0],1] checking in as pid 14469 on host clx-orion-043
Daemon [[32140,0],3] checking in as pid 3681 on host clx-orion-045
 Data for JOB [32140,1] offset 0

 ========================   JOB MAP   ========================

 Data for node: clx-orion-035	Num slots: 28	Max slots: 0	Num procs: 1
 	Process OMPI jobid: [32140,1] App: 0 Process rank: 0 Bound: socket 0[core 0[hwt 0]]:[B/././././././././././././.][./././././././././././././.]

 Data for node: clx-orion-043	Num slots: 28	Max slots: 0	Num procs: 1
 	Process OMPI jobid: [32140,1] App: 0 Process rank: 1 Bound: socket 0[core 0[hwt 0]]:[B/././././././././././././.][./././././././././././././.]

 Data for node: clx-orion-044	Num slots: 28	Max slots: 0	Num procs: 1
 	Process OMPI jobid: [32140,1] App: 0 Process rank: 2 Bound: socket 0[core 0[hwt 0]]:[B/././././././././././././.][./././././././././././././.]

 =============================================================[clx-orion-035:29831] [[32140,0],0] orted_cmd: received add_local_procs
[warn] Epoll ADD(1) on fd 0 failed.  Old events were 0; read change was 1 (add); write change was 0 (none): Operation not permitted
  MPIR_being_debugged = 0
  MPIR_debug_state = 1  MPIR_partial_attach_ok = 1
  MPIR_i_am_starter = 0
  MPIR_forward_output = 0
  MPIR_proctable_size = 3
  MPIR_proctable:
    (i, host, exe, pid) = (0, clx-orion-035, /hpc/scrap/users/mtt/scratch/ucx_ompi/20170713_073528_19243_4300_clx-orion-035/installs/o1Bb/tests/mpich_tests/mpich-mellanox.git/test/mpi/pt2pt/large_message, 29848)
    (i, host, exe, pid) = (1, clx-orion-043, /hpc/scrap/users/mtt/scratch/ucx_ompi/20170713_073528_19243_4300_clx-orion-035/installs/o1Bb/tests/mpich_tests/mpich-mellanox.git/test/mpi/pt2pt/large_message, 14475)
    (i, host, exe, pid) = (2, clx-orion-044, /hpc/scrap/users/mtt/scratch/ucx_ompi/20170713_073528_19243_4300_clx-orion-035/installs/o1Bb/tests/mpich_tests/mpich-mellanox.git/test/mpi/pt2pt/large_message, 8027)
MPIR_executable_path: NULL
MPIR_server_arguments: NULL[clx-orion-044:08021] [[32140,0],2] orted: up and running - waiting for commands!
[clx-orion-044:08021] [[32140,0],2] orted_cmd: received add_local_procs
[clx-orion-043:14469] [[32140,0],1] orted: up and running - waiting for commands!
[clx-orion-043:14469] [[32140,0],1] orted_cmd: received add_local_procs
[clx-orion-045:03681] [[32140,0],3] orted: up and running - waiting for commands!
[clx-orion-045:03681] [[32140,0],3] orted_cmd: received add_local_procs
Thu Jul 13 08:35:34 2017[1,2]<stderr>:mlx5: clx-orion-044: got completion with error:
Thu Jul 13 08:35:34 2017[1,2]<stderr>:00000000 00000000 00000000 00000000
Thu Jul 13 08:35:34 2017[1,2]<stderr>:00000000 00000000 00000000 00000000
Thu Jul 13 08:35:34 2017[1,2]<stderr>:00000002 00000000 00000000 00000000
Thu Jul 13 08:35:34 2017[1,2]<stderr>:00000000 42006802 2802eb32 0000f4d2Thu Jul 13 08:35:34 2017[1,2]<stderr>:[clx-orion-044:8027 :0] rc_verbs_iface.c:146  Fatal: Receive completion with error on XRQ: local QP operation error
Thu Jul 13 08:35:34 2017[1,1]<stderr>:mlx5: clx-orion-043: got completion with error:
Thu Jul 13 08:35:34 2017[1,1]<stderr>:00000000 00000000 00000000 00000000
Thu Jul 13 08:35:34 2017[1,1]<stderr>:00000000 00000000 00000000 00000000
Thu Jul 13 08:35:34 2017[1,1]<stderr>:00000002 00000000 00000000 00000000
Thu Jul 13 08:35:34 2017[1,1]<stderr>:00000000 42006802 2802e376 0000b8d2Thu Jul 13 08:35:34 2017[1,1]<stderr>:[clx-orion-043:14475:0] rc_verbs_iface.c:146  Fatal: Receive completion with error on XRQ: local QP operation error
Thu Jul 13 08:35:34 2017[1,2]<stderr>:==== backtrace ====
Thu Jul 13 08:35:34 2017[1,2]<stderr>: 0 0x0000000000028d24 uct_rc_verbs_iface_wc_error()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/uct/ib/rc/verbs/rc_verbs_iface.c:145Thu Jul 13 08:35:34 2017[1,2]<stderr>: 1 0x000000000002a527 uct_rc_verbs_iface_poll_rx_tm()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/uct/ib/rc/verbs/rc_verbs_iface.c:315
Thu Jul 13 08:35:34 2017[1,2]<stderr>: 2 0x000000000002a527 uct_rc_verbs_iface_progress_tm()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/uct/ib/rc/verbs/rc_verbs_iface.c:368
Thu Jul 13 08:35:34 2017[1,2]<stderr>: 3 0x0000000000010042 ucs_callbackq_dispatch()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/ucs/datastruct/callbackq.h:152
Thu Jul 13 08:35:34 2017[1,2]<stderr>: 4 0x0000000000010042 uct_worker_progress()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/uct/api/uct.h:1363
Thu Jul 13 08:35:34 2017[1,2]<stderr>: 5 0x0000000000010042 ucp_worker_progress()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/ucp/core/ucp_worker.c:844
Thu Jul 13 08:35:34 2017[1,2]<stderr>: 6 0x0000000000002f97 mca_pml_ucx_progress()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ompi-v2.x/ompi/mca/pml/ucx/pml_ucx.c:421
Thu Jul 13 08:35:34 2017[1,2]<stderr>: 7 0x000000000002ef5c opal_progress()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ompi-v2.x/opal/runtime/opal_progress.c:226
Thu Jul 13 08:35:34 2017[1,2]<stderr>: 8 0x00000000000032dd mca_pml_ucx_recv()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ompi-v2.x/ompi/mca/pml/ucx/pml_ucx.c:510
Thu Jul 13 08:35:34 2017[1,2]<stderr>: 9 0x000000000005b4d4 PMPI_Recv()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ompi-v2.x/ompi/mpi/c/profile/precv.c:77
Thu Jul 13 08:35:34 2017[1,2]<stderr>:10 0x0000000000402677 main()  ???:0
Thu Jul 13 08:35:34 2017[1,2]<stderr>:11 0x0000000000021b35 __libc_start_main()  ???:0
Thu Jul 13 08:35:34 2017[1,2]<stderr>:12 0x00000000004023e9 _start()  ???:0
Thu Jul 13 08:35:34 2017[1,2]<stderr>:===================Thu Jul 13 08:35:34 2017[1,2]<stderr>:[clx-orion-044:8027 :0] Process frozen...
Thu Jul 13 08:35:34 2017[1,1]<stderr>:==== backtrace ====
Thu Jul 13 08:35:34 2017[1,1]<stderr>: 0 0x0000000000028d24 uct_rc_verbs_iface_wc_error()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/uct/ib/rc/verbs/rc_verbs_iface.c:145
Thu Jul 13 08:35:34 2017[1,1]<stderr>: 1 0x000000000002a527 uct_rc_verbs_iface_poll_rx_tm()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/uct/ib/rc/verbs/rc_verbs_iface.c:315
Thu Jul 13 08:35:34 2017[1,1]<stderr>: 2 0x000000000002a527 uct_rc_verbs_iface_progress_tm()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/uct/ib/rc/verbs/rc_verbs_iface.c:368
Thu Jul 13 08:35:34 2017[1,1]<stderr>: 3 0x0000000000010042 ucs_callbackq_dispatch()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/ucs/datastruct/callbackq.h:152
Thu Jul 13 08:35:34 2017[1,1]<stderr>: 4 0x0000000000010042 uct_worker_progress()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/uct/api/uct.h:1363
Thu Jul 13 08:35:34 2017[1,1]<stderr>: 5 0x0000000000010042 ucp_worker_progress()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/ucp/core/ucp_worker.c:844
Thu Jul 13 08:35:34 2017[1,1]<stderr>: 6 0x0000000000002f97 mca_pml_ucx_progress()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ompi-v2.x/ompi/mca/pml/ucx/pml_ucx.c:421
Thu Jul 13 08:35:34 2017[1,1]<stderr>: 7 0x000000000002ef5c opal_progress()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ompi-v2.x/opal/runtime/opal_progress.c:226
Thu Jul 13 08:35:34 2017[1,1]<stderr>: 8 0x00000000000032dd mca_pml_ucx_recv()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ompi-v2.x/ompi/mca/pml/ucx/pml_ucx.c:510
Thu Jul 13 08:35:34 2017[1,1]<stderr>: 9 0x000000000005b4d4 PMPI_Recv()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ompi-v2.x/ompi/mpi/c/profile/precv.c:77
Thu Jul 13 08:35:34 2017[1,1]<stderr>:10 0x0000000000402677 main()  ???:0
Thu Jul 13 08:35:34 2017[1,1]<stderr>:11 0x0000000000021b35 __libc_start_main()  ???:0
Thu Jul 13 08:35:34 2017[1,1]<stderr>:12 0x00000000004023e9 _start()  ???:0
Thu Jul 13 08:35:34 2017[1,1]<stderr>:===================Thu Jul 13 08:35:34 2017[1,1]<stderr>:[clx-orion-043:14475:0] Process frozen...
[clx-orion-035:29831] [[32140,0],0] orted_cmd: received exit cmd
srun: forcing job termination
srun: Job step aborted: Waiting up to 12 seconds for job step to finish.
slurmstepd: error: *** STEP 4300.48 ON clx-orion-043 CANCELLED AT 2017-07-13T09:05:37 ***
srun: error: clx-orion-043: task 0: Killed
srun: Terminating job step 4300.48
srun: error: clx-orion-044: task 1: Killed
srun: error: clx-orion-045: task 2: Killed
[clx-orion-035:29831] [[32140,0],0] orted_cmd: exit cmd, 3 routes still exist
[clx-orion-035:29831] [[32140,0],0] orted_cmd: received halt_vm cmd
node=clx-orion-035, pid=29848:
Thread 4 (Thread 0x7ffff4346700 (LWP 29849)):
#0  0x00007ffff7633d13 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007ffff702cc73 in epoll_dispatch (base=0x680490, tv=<optimized out>) at epoll.c:407
#2  0x00007ffff70306c0 in opal_libevent2022_event_base_loop (base=base@entry=0x680490, flags=flags@entry=1) at event.c:1630
#3  0x00007ffff4378c5d in progress_engine (obj=0x680490) at src/util/progress_threads.c:52
#4  0x00007ffff7904dc5 in start_thread () from /usr/lib64/libpthread.so.0
#5  0x00007ffff763373d in clone () from /usr/lib64/libc.so.6
Thread 3 (Thread 0x7ffff3945700 (LWP 29850)):
#0  0x00007ffff7633d13 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007ffff702cc73 in epoll_dispatch (base=0x681970, tv=<optimized out>) at epoll.c:407
#2  0x00007ffff70306c0 in opal_libevent2022_event_base_loop (base=0x681970, flags=flags@entry=1) at event.c:1630
#3  0x00007ffff6ff442e in progress_engine (obj=<optimized out>) at runtime/opal_progress_threads.c:105
#4  0x00007ffff7904dc5 in start_thread () from /usr/lib64/libpthread.so.0
#5  0x00007ffff763373d in clone () from /usr/lib64/libc.so.6
Thread 2 (Thread 0x7fffea1c0700 (LWP 29860)):
#0  0x00007ffff7633d13 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007fffea407bb0 in ucs_async_thread_func (arg=0xad4620) at async/thread.c:93
#2  0x00007ffff7904dc5 in start_thread () from /usr/lib64/libpthread.so.0
#3  0x00007ffff763373d in clone () from /usr/lib64/libc.so.6
Thread 1 (Thread 0x7ffff7fb7740 (LWP 29848)):
#0  ucs_spin_lock (lock=0x7ffff7e4b010) at /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/ucs/type/spinlock.h:64
#1  uct_ud_enter (iface=0xb8e050) at /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/uct/ib/ud/base/ud_iface.h:211
#2  uct_ud_verbs_iface_progress (arg=0xb8e050) at ib/ud/verbs/ud_verbs.c:365
#3  0x00007fffeab73042 in ucs_callbackq_dispatch (cbq=<optimized out>) at /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/ucs/datastruct/callbackq.h:152
#4  uct_worker_progress (worker=<optimized out>) at /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/uct/api/uct.h:1363
#5  ucp_worker_progress (worker=0x7ffff7e4b010) at core/ucp_worker.c:844
#6  0x00007fffead8ef97 in mca_pml_ucx_progress () at pml_ucx.c:421
#7  0x00007ffff6feff5c in opal_progress () at runtime/opal_progress.c:226
#8  0x00007ffff7b5c1dd in ompi_request_wait_completion (req=0xbf8e48) at ../ompi/request/request.h:392
#9  ompi_request_default_wait (req_ptr=0x7fffffffc0b0, status=0x0) at request/req_wait.c:41
#10 0x00007fffead90ffb in mca_pml_ucx_send (buf=0x7fff5b6ad010, count=270000000, datatype=<optimized out>, dst=<optimized out>, tag=<optimized out>, mode=<optimized out>, comm=0x60d7c0 <ompi_mpi_comm_world>) at pml_ucx.c:717
#11 0x00007ffff7b758f5 in PMPI_Send (buf=<optimized out>, count=<optimized out>, type=<optimized out>, dest=<optimized out>, tag=<optimized out>, comm=0x60d7c0 <ompi_mpi_comm_world>) at psend.c:77
#12 0x00000000004025ea in main ()

node=clx-orion-043, pid=14475:
Thread 4 (Thread 0x7ffff4346700 (LWP 14476)):
#0  0x00007ffff790bc9d in pause () from /usr/lib64/libpthread.so.0
#1  0x00007fffea40d535 in ucs_debug_freeze () at debug/debug.c:709
#2  <signal handler called>
#3  0x00007ffff7633d13 in epoll_wait () from /usr/lib64/libc.so.6
#4  0x00007ffff702cc73 in epoll_dispatch (base=0x680490, tv=<optimized out>) at epoll.c:407
#5  0x00007ffff70306c0 in opal_libevent2022_event_base_loop (base=base@entry=0x680490, flags=flags@entry=1) at event.c:1630
#6  0x00007ffff4378c5d in progress_engine (obj=0x680490) at src/util/progress_threads.c:52
#7  0x00007ffff7904dc5 in start_thread () from /usr/lib64/libpthread.so.0
#8  0x00007ffff763373d in clone () from /usr/lib64/libc.so.6
Thread 3 (Thread 0x7ffff3945700 (LWP 14477)):
#0  0x00007ffff790bc9d in pause () from /usr/lib64/libpthread.so.0
#1  0x00007fffea40d535 in ucs_debug_freeze () at debug/debug.c:709
#2  <signal handler called>
#3  0x00007ffff7633d13 in epoll_wait () from /usr/lib64/libc.so.6
#4  0x00007ffff702cc73 in epoll_dispatch (base=0x681970, tv=<optimized out>) at epoll.c:407
#5  0x00007ffff70306c0 in opal_libevent2022_event_base_loop (base=0x681970, flags=flags@entry=1) at event.c:1630
#6  0x00007ffff6ff442e in progress_engine (obj=<optimized out>) at runtime/opal_progress_threads.c:105
#7  0x00007ffff7904dc5 in start_thread () from /usr/lib64/libpthread.so.0
#8  0x00007ffff763373d in clone () from /usr/lib64/libc.so.6
Thread 2 (Thread 0x7fffea1c0700 (LWP 14487)):
#0  0x00007ffff790bc9d in pause () from /usr/lib64/libpthread.so.0
#1  0x00007fffea40d535 in ucs_debug_freeze () at debug/debug.c:709
#2  <signal handler called>
#3  0x00007ffff7633d13 in epoll_wait () from /usr/lib64/libc.so.6
#4  0x00007fffea407bb0 in ucs_async_thread_func (arg=0xadbe90) at async/thread.c:93
#5  0x00007ffff7904dc5 in start_thread () from /usr/lib64/libpthread.so.0
#6  0x00007ffff763373d in clone () from /usr/lib64/libc.so.6
Thread 1 (Thread 0x7ffff7fb7740 (LWP 14475)):
#0  0x00007ffff790bc9d in pause () from /usr/lib64/libpthread.so.0
#1  0x00007fffea40d535 in ucs_debug_freeze () at debug/debug.c:709
#2  0x00007fffea40e7dd in ucs_error_freeze (message=0x7fffffffaaa0 "rc_verbs_iface.c:146  Fatal: Receive completion with error on XRQ: local QP operation error", error_type=0x7fffea9496b3 "fatal error") at debug/debug.c:828
#3  ucs_handle_error (error_type=error_type@entry=0x7fffea9496b3 "fatal error", message=message@entry=0x7fffea4a8a6d "%13s:%-4u %s") at debug/debug.c:992
#4  0x00007fffea40f922 in __ucs_abort (error_type=error_type@entry=0x7fffea9496b3 "fatal error", file=file@entry=0x7fffea94c983 "ib/rc/verbs/rc_verbs_iface.c", line=line@entry=146, function=function@entry=0x7fffea94cb50 <__FUNCTION__.17385> "uct_rc_verbs_iface_wc_error", message=message@entry=0x7fffea94c6e0 "Fatal: Receive completion with error on XRQ: %s") at debug/log.c:227
#5  0x00007fffea926d24 in uct_rc_verbs_iface_wc_error (status=<optimized out>, iface=0xb1c180) at ib/rc/verbs/rc_verbs_iface.c:145
#6  0x00007fffea928527 in uct_rc_verbs_iface_poll_rx_tm (iface=0xb1c180) at ib/rc/verbs/rc_verbs_iface.c:315
#7  uct_rc_verbs_iface_progress_tm (arg=0xb1c180) at ib/rc/verbs/rc_verbs_iface.c:366
#8  0x00007fffeab73042 in ucs_callbackq_dispatch (cbq=<optimized out>) at /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/ucs/datastruct/callbackq.h:152
#9  uct_worker_progress (worker=<optimized out>) at /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/uct/api/uct.h:1363
#10 ucp_worker_progress (worker=0x7ffff7e4b010) at core/ucp_worker.c:844
#11 0x00007fffead8ef97 in mca_pml_ucx_progress () at pml_ucx.c:421
#12 0x00007ffff6feff5c in opal_progress () at runtime/opal_progress.c:226
#13 0x00007fffead8f2dd in mca_pml_ucx_recv (buf=<optimized out>, count=<optimized out>, datatype=<optimized out>, src=<optimized out>, tag=<optimized out>, comm=<optimized out>, mpi_status=0x7fffffffbe60) at pml_ucx.c:510
#14 0x00007ffff7b744d4 in PMPI_Recv (buf=<optimized out>, count=<optimized out>, type=<optimized out>, source=<optimized out>, tag=<optimized out>, comm=0x60d7c0 <ompi_mpi_comm_world>, status=0x7fffffffbe60) at precv.c:77
#15 0x0000000000402677 in main ()

node=clx-orion-044, pid=8027:
Thread 4 (Thread 0x7ffff4346700 (LWP 8028)):
#0  0x00007ffff790bc9d in pause () from /usr/lib64/libpthread.so.0
#1  0x00007fffea40d535 in ucs_debug_freeze () at debug/debug.c:709
#2  <signal handler called>
#3  0x00007ffff7633d13 in epoll_wait () from /usr/lib64/libc.so.6
#4  0x00007ffff702cc73 in epoll_dispatch (base=0x680490, tv=<optimized out>) at epoll.c:407
#5  0x00007ffff70306c0 in opal_libevent2022_event_base_loop (base=base@entry=0x680490, flags=flags@entry=1) at event.c:1630
#6  0x00007ffff4378c5d in progress_engine (obj=0x680490) at src/util/progress_threads.c:52
#7  0x00007ffff7904dc5 in start_thread () from /usr/lib64/libpthread.so.0
#8  0x00007ffff763373d in clone () from /usr/lib64/libc.so.6
Thread 3 (Thread 0x7ffff3945700 (LWP 8029)):
#0  0x00007ffff790bc9d in pause () from /usr/lib64/libpthread.so.0
#1  0x00007fffea40d535 in ucs_debug_freeze () at debug/debug.c:709
#2  <signal handler called>
#3  0x00007ffff7633d13 in epoll_wait () from /usr/lib64/libc.so.6
#4  0x00007ffff702cc73 in epoll_dispatch (base=0x681970, tv=<optimized out>) at epoll.c:407
#5  0x00007ffff70306c0 in opal_libevent2022_event_base_loop (base=0x681970, flags=flags@entry=1) at event.c:1630
#6  0x00007ffff6ff442e in progress_engine (obj=<optimized out>) at runtime/opal_progress_threads.c:105
#7  0x00007ffff7904dc5 in start_thread () from /usr/lib64/libpthread.so.0
#8  0x00007ffff763373d in clone () from /usr/lib64/libc.so.6
Thread 2 (Thread 0x7fffea1c0700 (LWP 8039)):
#0  0x00007ffff790bc9d in pause () from /usr/lib64/libpthread.so.0
#1  0x00007fffea40d535 in ucs_debug_freeze () at debug/debug.c:709
#2  <signal handler called>
#3  0x00007ffff7633d13 in epoll_wait () from /usr/lib64/libc.so.6
#4  0x00007fffea407bb0 in ucs_async_thread_func (arg=0xadbe90) at async/thread.c:93
#5  0x00007ffff7904dc5 in start_thread () from /usr/lib64/libpthread.so.0
#6  0x00007ffff763373d in clone () from /usr/lib64/libc.so.6
Thread 1 (Thread 0x7ffff7fb7740 (LWP 8027)):
#0  0x00007ffff790bc9d in pause () from /usr/lib64/libpthread.so.0
#1  0x00007fffea40d535 in ucs_debug_freeze () at debug/debug.c:709
#2  0x00007fffea40e7dd in ucs_error_freeze (message=0x7fffffffaaa0 "rc_verbs_iface.c:146  Fatal: Receive completion with error on XRQ: local QP operation error", error_type=0x7fffea9496b3 "fatal error") at debug/debug.c:828
#3  ucs_handle_error (error_type=error_type@entry=0x7fffea9496b3 "fatal error", message=message@entry=0x7fffea4a8a6d "%13s:%-4u %s") at debug/debug.c:992
#4  0x00007fffea40f922 in __ucs_abort (error_type=error_type@entry=0x7fffea9496b3 "fatal error", file=file@entry=0x7fffea94c983 "ib/rc/verbs/rc_verbs_iface.c", line=line@entry=146, function=function@entry=0x7fffea94cb50 <__FUNCTION__.17385> "uct_rc_verbs_iface_wc_error", message=message@entry=0x7fffea94c6e0 "Fatal: Receive completion with error on XRQ: %s") at debug/log.c:227
#5  0x00007fffea926d24 in uct_rc_verbs_iface_wc_error (status=<optimized out>, iface=0xb1c180) at ib/rc/verbs/rc_verbs_iface.c:145
#6  0x00007fffea928527 in uct_rc_verbs_iface_poll_rx_tm (iface=0xb1c180) at ib/rc/verbs/rc_verbs_iface.c:315
#7  uct_rc_verbs_iface_progress_tm (arg=0xb1c180) at ib/rc/verbs/rc_verbs_iface.c:366
#8  0x00007fffeab73042 in ucs_callbackq_dispatch (cbq=<optimized out>) at /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/ucs/datastruct/callbackq.h:152
#9  uct_worker_progress (worker=<optimized out>) at /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ucx-master/src/uct/api/uct.h:1363
#10 ucp_worker_progress (worker=0x7ffff7e4b010) at core/ucp_worker.c:844
#11 0x00007fffead8ef97 in mca_pml_ucx_progress () at pml_ucx.c:421
#12 0x00007ffff6feff5c in opal_progress () at runtime/opal_progress.c:226
#13 0x00007fffead8f2dd in mca_pml_ucx_recv (buf=<optimized out>, count=<optimized out>, datatype=<optimized out>, src=<optimized out>, tag=<optimized out>, comm=<optimized out>, mpi_status=0x7fffffffbe70) at pml_ucx.c:510
#14 0x00007ffff7b744d4 in PMPI_Recv (buf=<optimized out>, count=<optimized out>, type=<optimized out>, source=<optimized out>, tag=<optimized out>, comm=0x60d7c0 <ompi_mpi_comm_world>, status=0x7fffffffbe70) at precv.c:77
#15 0x0000000000402677 in main ()
MTT killed /tmp/aHcPPNrKWH via SIGTERM
```

**Comment by yosefe** [comment]
fixed by #1706
