### ISSUE TITLE
[mtt] osu_thread_multiple takes to much time

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#2111]
Configuration:
```
OMPI: v4.0
Vegas x4 vegas[17,25,31-32]
```

Cmd:
`/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20171223_103718_6800_137635_vegas17/installs/HyeC/install/bin/mpirun -np 2 --debug-daemons --display-map -mca btl_openib_warn_default_gid_prefix 0 --bind-to core --tag-output --timestamp-output -mca pml ucx -x UCX_NET_DEVICES=mlx5_0:1 -mca btl_openib_if_include mlx5_0:1 -mca coll '^hcoll' -x UCX_IB_GID_INDEX=0 -x UCX_TLS=ud,sm --map-by node /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20171223_103718_6800_137635_vegas17/installs/HyeC/tests/thread_multiple_tests/ompi-tests/osu/osu_latency_mt`

Output:
```
Sun Dec 24 09:52:05 2017[1,0]<stdout>:provided thread level: 3
Sun Dec 24 09:52:05 2017[1,0]<stdout>:# OSU MPI Multi-threaded Latency Test v3.6
Sun Dec 24 09:52:05 2017[1,0]<stdout>:# Size          Latency (us)
Sun Dec 24 09:52:05 2017[1,1]<stdout>:provided thread level: 3
Sun Dec 24 09:52:05 2017[1,0]<stdout>:0                       2.35
Sun Dec 24 09:52:05 2017[1,0]<stdout>:1                       1.90
Sun Dec 24 09:52:05 2017[1,0]<stdout>:2                       1.90
Sun Dec 24 09:52:47 2017[1,0]<stdout>:4                    2113.56
Sun Dec 24 09:52:47 2017[1,0]<stdout>:8                       1.25
```

Affected also `dc` an `rc`.

**Comment by alinask** [comment]
@amaslenn Can you please mention how long it takes for the test to finish?

**Comment by amaslenn** [comment]
I didn't wait until the end this time.

Previously I faced this issue and test took only slightly longer than timeout (`30min`), it was `31-32min`. But latency values were confusing:
```
Wed Dec 20 08:22:53 2017[1,0]<stdout>:provided thread level: 3                                                                                                                                                                   [31/2327]
Wed Dec 20 08:22:53 2017[1,0]<stdout>:# OSU MPI Multi-threaded Latency Test v3.6
Wed Dec 20 08:22:53 2017[1,0]<stdout>:# Size          Latency (us)
Wed Dec 20 08:25:20 2017[1,0]<stdout>:0                    7377.40
Wed Dec 20 08:27:45 2017[1,0]<stdout>:1                    7224.01
Wed Dec 20 08:30:12 2017[1,0]<stdout>:2                    7359.70
Wed Dec 20 08:32:38 2017[1,0]<stdout>:4                    7276.10
Wed Dec 20 08:35:04 2017[1,0]<stdout>:8                    7315.75
Wed Dec 20 08:35:04 2017[1,0]<stdout>:16                      2.25
Wed Dec 20 08:35:28 2017[1,0]<stdout>:32                   1213.80
Wed Dec 20 08:40:14 2017[1,0]<stdout>:64                  13132.22
Wed Dec 20 08:41:10 2017[1,0]<stdout>:128                  2840.52
Wed Dec 20 08:42:56 2017[1,0]<stdout>:256                  5302.46
Wed Dec 20 08:44:46 2017[1,0]<stdout>:512                  5491.54
Wed Dec 20 08:49:28 2017[1,0]<stdout>:1024                13056.39
Wed Dec 20 08:50:52 2017[1,0]<stdout>:2048                 4204.05
Wed Dec 20 08:52:06 2017[1,0]<stdout>:4096                 3693.04
Wed Dec 20 08:53:24 2017[1,0]<stdout>:8192                 3898.39
Wed Dec 20 08:53:24 2017[1,0]<stdout>:16384                   6.07
Wed Dec 20 08:53:24 2017[1,0]<stdout>:32768                   9.40
Wed Dec 20 08:53:24 2017[1,0]<stdout>:65536                  14.85
Wed Dec 20 08:53:24 2017[1,0]<stdout>:131072                 25.38
Wed Dec 20 08:53:24 2017[1,0]<stdout>:262144                 46.78
Wed Dec 20 08:53:24 2017[1,0]<stdout>:524288                 87.05
Wed Dec 20 08:53:24 2017[1,0]<stdout>:1048576               167.60
Wed Dec 20 08:53:24 2017[1,0]<stdout>:2097152               392.53
Wed Dec 20 08:53:24 2017[1,0]<stdout>:4194304               649.75
```

**Comment by alinask** [comment]
one more hang (30 mins) - 
```
/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20180118_150145_147359_139476_jazz01/installs/q_dz/install/bin/mpirun -np 2 --display-map -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_0:1 -x UCX_IB_GID_INDEX=0 -x UCX_TLS=rc_x,sm --map-by node /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20180118_150145_147359_139476_jazz01/installs/q_dz/tests/thread_multiple_tests/ompi-tests/osu/osu_latency_mt
 Data for JOB [11542,1] offset 0 Total slots allocated 56

 ========================   JOB MAP   ========================

 Data for node: jazz01	Num slots: 28	Max slots: 0	Num procs: 1
 	Process OMPI jobid: [11542,1] App: 0 Process rank: 0 Bound: socket 0[core 0[hwt 0]]:[B/././././././././././././.][./././././././././././././.]

 Data for node: jazz02	Num slots: 28	Max slots: 0	Num procs: 1
 	Process OMPI jobid: [11542,1] App: 0 Process rank: 1 Bound: N/A

 =============================================================Thu Jan 18 15:51:07 2018[1,0]<stdout>:provided thread level: 3
Thu Jan 18 15:51:07 2018[1,0]<stdout>:# OSU MPI Multi-threaded Latency Test v3.6
Thu Jan 18 15:51:07 2018[1,0]<stdout>:# Size          Latency (us)Thu Jan 18 15:51:07 2018[1,1]<stdout>:provided thread level: 3
Thu Jan 18 15:51:07 2018[1,0]<stdout>:0                       1.03
Thu Jan 18 15:51:07 2018[1,0]<stdout>:1                       1.04
Thu Jan 18 15:59:53 2018[1,0]<stdout>:2                   25426.07
Thu Jan 18 15:59:53 2018[1,0]<stdout>:4                       1.68
Thu Jan 18 15:59:53 2018[1,0]<stdout>:8                       1.03
Thu Jan 18 16:08:57 2018[1,0]<stdout>:16                  25822.44
Thu Jan 18 16:08:57 2018[1,0]<stdout>:32                      2.35
Thu Jan 18 16:18:26 2018[1,0]<stdout>:64                  26312.48

node=jazz01, pid=163593:
Thread 5 (Thread 0x7f0ca7598700 (LWP 163594)):
#0  0x00007f0caa898923 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007f0caa1ceca3 in epoll_dispatch (base=0x14ae350, tv=<optimized out>) at epoll.c:407
#2  0x00007f0caa1d26f0 in opal_libevent2022_event_base_loop (base=0x14ae350, flags=1) at event.c:1630
#3  0x00007f0caa170d86 in progress_engine (obj=0x14ae298) at runtime/opal_progress_threads.c:105
#4  0x00007f0caab6ae25 in start_thread () from /usr/lib64/libpthread.so.0
#5  0x00007f0caa89834d in clone () from /usr/lib64/libc.so.6
Thread 4 (Thread 0x7f0ca4f77700 (LWP 163595)):
#0  0x00007f0caa898923 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007f0caa1ceca3 in epoll_dispatch (base=0x14ed830, tv=<optimized out>) at epoll.c:407
#2  0x00007f0caa1d26f0 in opal_libevent2022_event_base_loop (base=0x14ed830, flags=1) at event.c:1630
#3  0x00007f0ca64de7c4 in progress_engine (obj=0x14ed788) at runtime/pmix_progress_threads.c:109
#4  0x00007f0caab6ae25 in start_thread () from /usr/lib64/libpthread.so.0
#5  0x00007f0caa89834d in clone () from /usr/lib64/libc.so.6
Thread 3 (Thread 0x7f0c95005700 (LWP 163598)):
#0  0x00007f0caa898923 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007f0c9737ddc0 in ucs_async_thread_func (arg=0x16a6d00) at async/thread.c:93
#2  0x00007f0caab6ae25 in start_thread () from /usr/lib64/libpthread.so.0
#3  0x00007f0caa89834d in clone () from /usr/lib64/libc.so.6
Thread 2 (Thread 0x7f0c943fa700 (LWP 163601)):
#0  0x00007f0caab6f483 in pthread_spin_lock () from /usr/lib64/libpthread.so.0
#1  0x00007f0c97da1ab0 in ucs_spin_lock (lock=0x7f0cab541180) at /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20180118_150145_147359_139476_jazz01/ucx_src/src/ucs/type/spinlock.h:65
#2  ucp_worker_progress (worker=0x7f0cab541010) at core/ucp_worker.c:1265
#3  0x00007f0c9c0af835 in mca_pml_ucx_progress () at pml_ucx.c:454
#4  0x00007f0caa1697f1 in opal_progress () at runtime/opal_progress.c:228
#5  0x00007f0c9c0afe13 in mca_pml_ucx_recv (buf=0xa02600 <r_buf1+32>, count=128, datatype=0x602100 <ompi_mpi_char>, src=1, tag=2, comm=0x602300 <ompi_mpi_comm_world>, mpi_status=0xe02620 <reqstat>) at pml_ucx.c:542
#6  0x00007f0caae428c5 in PMPI_Recv (buf=0xa02600 <r_buf1+32>, count=128, type=0x602100 <ompi_mpi_char>, source=1, tag=2, comm=0x602300 <ompi_mpi_comm_world>, status=status@entry=0xe02620 <reqstat>) at precv.c:79
#7  0x000000000040130f in send_thread (arg=<optimized out>) at osu_latency_mt.c:235
#8  0x00007f0caab6ae25 in start_thread () from /usr/lib64/libpthread.so.0
#9  0x00007f0caa89834d in clone () from /usr/lib64/libc.so.6
Thread 1 (Thread 0x7f0cab615740 (LWP 163593)):
#0  0x00007f0caab6bf57 in pthread_join () from /usr/lib64/libpthread.so.0
#1  0x0000000000400fb3 in main (argc=1, argv=0x7ffd87d513c8) at osu_latency_mt.c:115

node=jazz02, pid=126919:
Thread 6 (Thread 0x7f974484e700 (LWP 126920)):
#0  0x00007f9747b4e923 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007f9747484ca3 in epoll_dispatch (base=0x134b420, tv=<optimized out>) at epoll.c:407
#2  0x00007f97474886f0 in opal_libevent2022_event_base_loop (base=0x134b420, flags=1) at event.c:1630
#3  0x00007f9747426d86 in progress_engine (obj=0x134b368) at runtime/opal_progress_threads.c:105
#4  0x00007f9747e20e25 in start_thread () from /usr/lib64/libpthread.so.0
#5  0x00007f9747b4e34d in clone () from /usr/lib64/libc.so.6
Thread 5 (Thread 0x7f974222d700 (LWP 126921)):
#0  0x00007f9747b4e923 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007f9747484ca3 in epoll_dispatch (base=0x138a900, tv=<optimized out>) at epoll.c:407
#2  0x00007f97474886f0 in opal_libevent2022_event_base_loop (base=0x138a900, flags=1) at event.c:1630
#3  0x00007f97437947c4 in progress_engine (obj=0x138a858) at runtime/pmix_progress_threads.c:109
#4  0x00007f9747e20e25 in start_thread () from /usr/lib64/libpthread.so.0
#5  0x00007f9747b4e34d in clone () from /usr/lib64/libc.so.6
Thread 4 (Thread 0x7f97322f3700 (LWP 126924)):
#0  0x00007f9747b4e923 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007f9738853dc0 in ucs_async_thread_func (arg=0x15455f0) at async/thread.c:93
#2  0x00007f9747e20e25 in start_thread () from /usr/lib64/libpthread.so.0
#3  0x00007f9747b4e34d in clone () from /usr/lib64/libc.so.6
Thread 3 (Thread 0x7f97317ed700 (LWP 126927)):
#0  0x00007f97394d9050 in opal_progress@plt () from /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20180118_150145_147359_139476_jazz01/installs/q_dz/install/lib/openmpi/mca_pml_ucx.so
#1  0x00007f97394dbe13 in mca_pml_ucx_recv (buf=0xa02600 <r_buf1+32>, count=128, datatype=0x602100 <ompi_mpi_char>, src=0, tag=1, comm=0x602300 <ompi_mpi_comm_world>, mpi_status=0xe02620 <reqstat>) at pml_ucx.c:542
#2  0x00007f97480f88c5 in PMPI_Recv (buf=0xa02600 <r_buf1+32>, count=128, type=0x602100 <ompi_mpi_char>, source=0, tag=1, comm=0x602300 <ompi_mpi_comm_world>, status=status@entry=0xe02620 <reqstat>) at precv.c:79
#3  0x00000000004011ad in recv_thread (arg=<optimized out>) at osu_latency_mt.c:185
#4  0x00007f9747e20e25 in start_thread () from /usr/lib64/libpthread.so.0
#5  0x00007f9747b4e34d in clone () from /usr/lib64/libc.so.6
Thread 2 (Thread 0x7f9730dec700 (LWP 126928)):
#0  0x00007f97474e32fa in opal_sys_timer_get_cycles () at ../../../../opal/include/opal/sys/x86_64/timer.h:39
#1  0x00007f97474e387d in opal_timer_linux_get_cycles_sys_timer () at timer_linux_component.c:232
#2  0x00007f974741f759 in opal_progress_events () at runtime/opal_progress.c:181
#3  0x00007f974741f85c in opal_progress () at runtime/opal_progress.c:242
#4  0x00007f97394dbe13 in mca_pml_ucx_recv (buf=0xa02600 <r_buf1+32>, count=128, datatype=0x602100 <ompi_mpi_char>, src=0, tag=1, comm=0x602300 <ompi_mpi_comm_world>, mpi_status=0xe02638 <reqstat+24>) at pml_ucx.c:542
#5  0x00007f97480f88c5 in PMPI_Recv (buf=0xa02600 <r_buf1+32>, count=128, type=0x602100 <ompi_mpi_char>, source=0, tag=1, comm=0x602300 <ompi_mpi_comm_world>, status=status@entry=0xe02638 <reqstat+24>) at precv.c:79
#6  0x00000000004011ad in recv_thread (arg=<optimized out>) at osu_latency_mt.c:185
#7  0x00007f9747e20e25 in start_thread () from /usr/lib64/libpthread.so.0
#8  0x00007f9747b4e34d in clone () from /usr/lib64/libc.so.6
Thread 1 (Thread 0x7f97488cb740 (LWP 126919)):
#0  0x00007f9747e21f57 in pthread_join () from /usr/lib64/libpthread.so.0
#1  0x0000000000400f21 in main (argc=1, argv=0x7ffde88de4c8) at osu_latency_mt.c:126
MTT killed /tmp/pUq1oeRqxE via SIGTERM
```

**Comment by yosefe** [comment]
still happens
