### ISSUE TITLE
segv on ibm/pt2pt tests

### ISSUE THREAD

**Issue by alinask** [openucx/ucx#2229]
Configuration:

```
ompi-v3.1.x
Hercules x26 (ppn=32(x26),  clx-hercules-[048,057-073,093-096,113-116]
```

MTT log:
http://e2e-gw.mellanox.com:4080/mnt/lustre/users/mtt/scratch/ucx_ompi/20180130_160329_5501_53680_clx-hercules-003/Test_Run-ibm-tests-ompi_installed-3.1.0rc1-ompi_installed.html

Cmd:
mpirun  -np 832  -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_0:1,mlx5_2:1 -x UCX_IB_GID_INDEX=0 -mca osc '^ucx' -x UCX_TLS=ud,sm -x UCX_TM_OFFLOAD=n -x UCX_RC_TM_ENABLE=n -mca opal_pmix_base_async_modex 0 -mca mpi_add_procs_cutoff 100000 -x UCX_MAX_EAGER_LANES=3 -x UCX_MAX_RNDV_LANES=3 --map-by node /mnt/lustre/users/mtt/scratch/ucx_ompi/20180130_160329_5501_53680_clx-hercules-003/installs/i93E/tests/ibm-tests/ompi-tests/ibm/pt2pt/allocmem_usempi

Output:

```
Tue Jan 30 16:31:38 2018[1,0]<stdout>: Rank 0 doing message size           2
Tue Jan 30 16:31:38 2018[1,0]<stdout>: Rank 0 doing message size           4Tue Jan 30 16:31:38 2018[1,0]<stdout>: Rank 0 doing message size           8
Tue Jan 30 16:31:39 2018[1,0]<stdout>: Rank 0 doing message size          16
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 80 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
Tue Jan 30 16:31:39 2018[1,80]<stderr>:[**ERROR**]: MPI_COMM_WORLD rank 80:
Tue Jan 30 16:31:39 2018[1,80]<stderr>:ERROR: Got wrong right value in ADDRESS_KIND test
Tue Jan 30 16:31:39 2018[1,73]<stderr>:[clx-hercules-088:11990:0:11990] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
Tue Jan 30 16:31:39 2018[1,0]<stdout>: Rank 0 doing message size          32
Tue Jan 30 16:31:39 2018[1,0]<stdout>: Rank 0 doing message size          64
Tue Jan 30 16:31:39 2018[1,0]<stdout>: Rank 0 doing message size         128
Tue Jan 30 16:31:39 2018[1,0]<stdout>: Rank 0 doing message size         256
Tue Jan 30 16:31:39 2018[1,0]<stdout>: Rank 0 doing message size         512
Tue Jan 30 16:31:39 2018[1,0]<stdout>: Rank 0 doing message size        1024
Tue Jan 30 16:31:39 2018[1,0]<stdout>: Rank 0 doing message size        2048Tue Jan 30 16:31:40 2018[1,405]<stderr>:[clx-hercules-082:26929:0:26929] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
Tue Jan 30 16:31:40 2018[1,60]<stderr>:[**ERROR**]: MPI_COMM_WORLD rank 60:
Tue Jan 30 16:31:40 2018[1,60]<stderr>:ERROR: Got wrong left value in ADDRESS_KIND test
Tue Jan 30 16:31:40 2018[1,43]<stderr>:[**ERROR**]: MPI_COMM_WORLD rank 43:
Tue Jan 30 16:31:40 2018[1,43]<stderr>:ERROR: Got wrong right value in ADDRESS_KIND test
Tue Jan 30 16:31:40 2018[1,400]<stderr>:[clx-hercules-075:13067:0:13067] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
Tue Jan 30 16:31:40 2018[1,87]<stderr>:[clx-hercules-074:24092:0:24092] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
Tue Jan 30 16:31:40 2018[1,277]<stderr>:[clx-hercules-084:18070:0:18070] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))Tue Jan 30 16:31:40 2018[1,286]<stderr>:[clx-hercules-003:7448 :0:7448] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
Tue Jan 30 16:31:40 2018[1,286]<stderr>:==== backtrace ====
Tue Jan 30 16:31:40 2018[1,286]<stderr>: 0 0x000000000003f565 ucs_arbiter_dispatch_nonempty()  /hpc/local/benchmarks/hpcx_install_2018-01-30/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/datastruct/arbiter.c:205
Tue Jan 30 16:31:40 2018[1,286]<stderr>: 1 0x000000000004e66e ucs_arbiter_dispatch()  /hpc/local/benchmarks/hpcx_install_2018-01-30/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/datastruct/arbiter.h:298
Tue Jan 30 16:31:40 2018[1,286]<stderr>: 2 0x0000000000013dac uct_ep_pending_add()  /hpc/local/benchmarks/hpcx_install_2018-01-30/src/hpcx-gcc-redhat7.4/ucx-master/src/uct/api/uct.h:1996
Tue Jan 30 16:31:40 2018[1,286]<stderr>: 3 0x000000000001d738 ucp_do_am_zcopy_multi()  /hpc/local/benchmarks/hpcx_install_2018-01-30/src/hpcx-gcc-redhat7.4/ucx-master/src/ucp/proto/proto_am.inl:309
Tue Jan 30 16:31:40 2018[1,286]<stderr>: 4 0x000000000004d41d uct_ud_ep_do_pending()  /hpc/local/benchmarks/hpcx_install_2018-01-30/src/hpcx-gcc-redhat7.4/ucx-master/src/uct/ib/ud/base/ud_ep.c:1044
Tue Jan 30 16:31:40 2018[1,286]<stderr>: 5 0x000000000003f672 ucs_arbiter_dispatch_nonempty()  /hpc/local/benchmarks/hpcx_install_2018-01-30/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/datastruct/arbiter.c:164
Tue Jan 30 16:31:40 2018[1,286]<stderr>: 6 0x00000000000511c8 uct_ud_iface_progress_pending_tx()  /hpc/local/benchmarks/hpcx_install_2018-01-30/src/hpcx-gcc-redhat7.4/ucx-master/src/uct/ib/ud/base/ud_iface.h:396
Tue Jan 30 16:31:40 2018[1,286]<stderr>: 7 0x000000000001d7bf uct_ep_am_zcopy()  /hpc/local/benchmarks/hpcx_install_2018-01-30/src/hpcx-gcc-redhat7.4/ucx-master/src/uct/api/uct.h:1877
Tue Jan 30 16:31:40 2018[1,286]<stderr>: 8 0x000000000004d41d uct_ud_ep_do_pending()  /hpc/local/benchmarks/hpcx_install_2018-01-30/src/hpcx-gcc-redhat7.4/ucx-master/src/uct/ib/ud/base/ud_ep.c:1044
Tue Jan 30 16:31:40 2018[1,286]<stderr>: 9 0x000000000003f672 ucs_arbiter_dispatch_nonempty()  /hpc/local/benchmarks/hpcx_install_2018-01-30/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/datastruct/arbiter.c:164
Tue Jan 30 16:31:40 2018[1,286]<stderr>:10 0x000000000004fad5 ucs_arbiter_dispatch()  /hpc/local/benchmarks/hpcx_install_2018-01-30/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/datastruct/arbiter.h:298
Tue Jan 30 16:31:40 2018[1,286]<stderr>:11 0x00000000000176a2 ucs_callbackq_dispatch()  /hpc/local/benchmarks/hpcx_install_2018-01-30/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/datastruct/callbackq.h:208
Tue Jan 30 16:31:40 2018[1,286]<stderr>:12 0x0000000000003327 mca_pml_ucx_progress()  /hpc/local/benchmarks/hpcx_install_2018-01-30/src/hpcx-gcc-redhat7.4/ompi-v3.1.x/ompi/mca/pml/ucx/pml_ucx.c:454
Tue Jan 30 16:31:40 2018[1,286]<stderr>:13 0x00000000000329fc opal_progress()  /hpc/local/benchmarks/hpcx_install_2018-01-30/src/hpcx-gcc-redhat7.4/ompi-v3.1.x/opal/runtime/opal_progress.c:228
Tue Jan 30 16:31:40 2018[1,286]<stderr>:14 0x0000000000048ded sync_wait_st()  /hpc/local/benchmarks/hpcx_install_2018-01-30/src/hpcx-gcc-redhat7.4/ompi-v3.1.x/ompi/../opal/threads/wait_sync.h:83
Tue Jan 30 16:31:40 2018[1,286]<stderr>:15 0x0000000000070e7c PMPI_Waitall()  /hpc/local/benchmarks/hpcx_install_2018-01-30/src/hpcx-gcc-redhat7.4/ompi-v3.1.x/ompi/mpi/c/profile/pwaitall.c:77
Tue Jan 30 16:31:40 2018[1,286]<stderr>:16 0x0000000000047819 ompi_waitall_f()  /hpc/local/benchmarks/hpcx_install_2018-01-30/src/hpcx-gcc-redhat7.4/ompi-v3.1.x/ompi/mpi/fortran/mpif-h/profile/pwaitall_f.c:104
Tue Jan 30 16:31:40 2018[1,286]<stderr>:17 0x0000000000401f14 MAIN__()  /mnt/lustre/users/mtt/scratch/ucx_ompi/20180130_160329_5501_53680_clx-hercules-003/installs/i93E/tests/ibm-tests/ompi-tests/ibm/pt2pt/allocmem_usempi.F90:156
Tue Jan 30 16:31:40 2018[1,286]<stderr>:18 0x00000000004020ca main()  /mnt/lustre/users/mtt/scratch/ucx_ompi/20180130_160329_5501_53680_clx-hercules-003/installs/i93E/tests/ibm-tests/ompi-tests/ibm/pt2pt/allocmem_usempi.F90:2
Tue Jan 30 16:31:40 2018[1,286]<stderr>:19 0x0000000000021c05 __libc_start_main()  ???:0
Tue Jan 30 16:31:40 2018[1,286]<stderr>:20 0x0000000000401509 _start()  ???:0
Tue Jan 30 16:31:40 2018[1,286]<stderr>:===================
```

Setting UCX_MAX_EAGER_LANES=1 UCX_MAX_RNDV_LANES=1,  seems to resolve this:
```
$mpirun  -np 832  -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_0:1,mlx5_2:1 -x UCX_IB_GID_INDEX=0 -mca osc '^ucx' -x UCX_TLS=ud,sm -x UCX_TM_OFFLOAD=n -x UCX_RC_TM_ENABLE=n -mca opal_pmix_base_async_modex 0 -mca mpi_add_procs_cutoff 100000 -x UCX_MAX_EAGER_LANES=1 -x UCX_MAX_RNDV_LANES=1 --map-by node /mnt/lustre/users/mtt/scratch/ucx_ompi/20180130_160329_5501_53680_clx-hercules-003/installs/i93E/tests/ibm-tests/ompi-tests/ibm/pt2pt/allocmem_usempi
Tue Jan 30 17:14:49 2018[1,0]<stdout>: Rank 0 doing message size           1
Tue Jan 30 17:14:49 2018[1,0]<stdout>: Rank 0 doing message size           2
Tue Jan 30 17:14:49 2018[1,0]<stdout>: Rank 0 doing message size           4
Tue Jan 30 17:14:49 2018[1,0]<stdout>: Rank 0 doing message size           8
Tue Jan 30 17:14:49 2018[1,0]<stdout>: Rank 0 doing message size          16
Tue Jan 30 17:14:49 2018[1,0]<stdout>: Rank 0 doing message size          32
Tue Jan 30 17:14:49 2018[1,0]<stdout>: Rank 0 doing message size          64
Tue Jan 30 17:14:49 2018[1,0]<stdout>: Rank 0 doing message size         128
Tue Jan 30 17:14:49 2018[1,0]<stdout>: Rank 0 doing message size         256
Tue Jan 30 17:14:49 2018[1,0]<stdout>: Rank 0 doing message size         512
Tue Jan 30 17:14:49 2018[1,0]<stdout>: Rank 0 doing message size        1024
Tue Jan 30 17:14:49 2018[1,0]<stdout>: Rank 0 doing message size        2048
Tue Jan 30 17:14:49 2018[1,0]<stdout>: Rank 0 doing message size        4096
Tue Jan 30 17:14:49 2018[1,0]<stdout>: Rank 0 doing message size        8192
Tue Jan 30 17:14:49 2018[1,0]<stdout>: Rank 0 doing message size       16384
Tue Jan 30 17:14:49 2018[1,0]<stdout>: Rank 0 doing message size       32768
Tue Jan 30 17:14:49 2018[1,0]<stdout>: Rank 0 doing message size       65536
Tue Jan 30 17:14:49 2018[1,0]<stdout>: Rank 0 doing message size      131072
Tue Jan 30 17:14:49 2018[1,0]<stdout>: Rank 0 doing message size      262144
Tue Jan 30 17:14:49 2018[1,0]<stdout>: Rank 0 doing message size      524288
Tue Jan 30 17:14:49 2018[1,0]<stdout>: Rank 0 doing message size     1048576
```

Note:
this fix - https://github.com/openucx/ucx/pull/2227 , for a lanes bug, _isn't_ present in the ucx which was run here.
UCT version=1.3.0 revision 1f64572

**Comment by hoopoepg** [comment]
issue is reproduced on single node with 2 ranks
backtrace for multi-lane arbiter crash:
```
#0  0x00007ffff67a1f0d in pause () from /usr/lib64/libpthread.so.0
#1  0x00007ffff55dc465 in ucs_debug_freeze () at debug/debug.c:709
#2  0x00007ffff55ddeb5 in ucs_error_freeze (message=0x7fffffffa8d0 "    arbiter.c:143  Assertion `next_group != ((void *)0)' failed", error_type=0x7ffff568211e "assertion failure")
    at debug/debug.c:828
#3  ucs_handle_error (error_type=error_type@entry=0x7ffff568211e "assertion failure", message=message@entry=0x7ffff568619c "%13s:%-4u %s") at debug/debug.c:992
#4  0x00007ffff55dbf9a in ucs_fatal_error (error_type=error_type@entry=0x7ffff568211e "assertion failure", file=file@entry=0x7ffff56846cb "datastruct/arbiter.c", line=line@entry=143,
    function=function@entry=0x7ffff5684800 <__FUNCTION__.2968> "ucs_arbiter_dispatch_nonempty", format=format@entry=0x7ffff56820fa "Assertion `%s' failed") at debug/assert.c:36
#5  0x00007ffff55d5141 in ucs_arbiter_dispatch_nonempty (arbiter=arbiter@entry=0x895830, per_group=per_group@entry=1, cb=cb@entry=0x7ffff618f240 <uct_ud_ep_do_pending>,
    cb_arg=cb_arg@entry=0x0) at datastruct/arbiter.c:143
#6  0x00007ffff6190f12 in ucs_arbiter_dispatch (per_group=1, cb=0x7ffff618f240 <uct_ud_ep_do_pending>, cb_arg=0x0, arbiter=0x895830) at /labhome/sergeyo/ucx/src/ucs/datastruct/arbiter.h:298
#7  uct_ud_iface_progress_pending (is_async=0, iface=0x895220) at ib/ud/base/ud_iface.h:385
#8  uct_ud_ep_pending_add (ep_h=0x9664e0, req=0x9789e0) at ib/ud/base/ud_ep.c:1073
#9  0x00007ffff7b75d02 in uct_ep_pending_add (req=0x9789e0, ep=0x9664e0) at /labhome/sergeyo/ucx/src/uct/api/uct.h:1996
#10 ucp_request_pending_add (req=req@entry=0x978940, req_status=req_status@entry=0x7fffffffb560) at core/ucp_request.c:166
#11 0x00007ffff7b90aad in ucp_do_am_bcopy_multi (enable_am_bw=1, pack_last=0x7ffff7b8f990 <ucp_tag_pack_eager_last_dt>, pack_middle=0x7ffff7b8fa20 <ucp_tag_pack_eager_middle_dt>,
    pack_first=0x7ffff7b8fc10 <ucp_tag_pack_eager_first_dt>, hdr_size_middle=16, am_id_last=4 '\004', am_id_middle=4 '\004', am_id_first=3 '\003', self=0x9789e0)
    at /labhome/sergeyo/ucx/src/ucp/proto/proto_am.inl:90
#12 ucp_tag_eager_bcopy_multi (self=0x9789e0) at tag/eager_snd.c:157
#13 0x00007ffff618f2cf in uct_ud_ep_do_pending (arbiter=arbiter@entry=0x881ac0, elem=elem@entry=0x9789e8, arg=arg@entry=0x0) at ib/ud/base/ud_ep.c:1044
#14 0x00007ffff55d4e4e in ucs_arbiter_dispatch_nonempty (arbiter=0x881ac0, per_group=per_group@entry=1, cb=0x7ffff618f240 <uct_ud_ep_do_pending>, cb_arg=cb_arg@entry=0x0)
    at datastruct/arbiter.c:167
#15 0x00007ffff6191e91 in ucs_arbiter_dispatch (arbiter=arbiter@entry=0x881ac0, cb_arg=cb_arg@entry=0x0, cb=<optimized out>, per_group=1)
    at /labhome/sergeyo/ucx/src/ucs/datastruct/arbiter.h:298
#16 0x00007ffff6195be1 in uct_ud_iface_progress_pending_tx (iface=0x8814b0) at /labhome/sergeyo/ucx/src/uct/ib/ud/base/ud_iface.h:396
#17 uct_ud_verbs_ep_am_bcopy (tl_ep=0x966650, id=<optimized out>, pack_cb=0x7ffff7b8fa20 <ucp_tag_pack_eager_middle_dt>, arg=<optimized out>, flags=<optimized out>)
    at ib/ud/verbs/ud_verbs.c:183
#18 0x00007ffff7b90a78 in uct_ep_am_bcopy (flags=0, arg=0x978780, pack_cb=0x7ffff7b8fa20 <ucp_tag_pack_eager_middle_dt>, id=4 '\004', ep=0x966650)
    at /labhome/sergeyo/ucx/src/uct/api/uct.h:1835
#19 ucp_do_am_bcopy_multi (enable_am_bw=1, pack_last=0x7ffff7b8f990 <ucp_tag_pack_eager_last_dt>, pack_middle=0x7ffff7b8fa20 <ucp_tag_pack_eager_middle_dt>,
    pack_first=0x7ffff7b8fc10 <ucp_tag_pack_eager_first_dt>, hdr_size_middle=16, am_id_last=4 '\004', am_id_middle=4 '\004', am_id_first=3 '\003', self=0x978820)
    at /labhome/sergeyo/ucx/src/ucp/proto/proto_am.inl:70
#20 ucp_tag_eager_bcopy_multi (self=0x978820) at tag/eager_snd.c:157
#21 0x00007ffff618f2cf in uct_ud_ep_do_pending (arbiter=arbiter@entry=0x895830, elem=elem@entry=0x978828, arg=arg@entry=0x0) at ib/ud/base/ud_ep.c:1044
#22 0x00007ffff55d4e4e in ucs_arbiter_dispatch_nonempty (arbiter=arbiter@entry=0x895830, per_group=per_group@entry=1, cb=0x7ffff618f240 <uct_ud_ep_do_pending>, cb_arg=cb_arg@entry=0x0)
    at datastruct/arbiter.c:167
#23 0x00007ffff6192bd9 in ucs_arbiter_dispatch (per_group=1, cb=<optimized out>, cb_arg=0x0, arbiter=0x895830) at /labhome/sergeyo/ucx/src/ucs/datastruct/arbiter.h:298
#24 uct_ud_iface_progress_pending (is_async=0, iface=0x895220) at /labhome/sergeyo/ucx/src/uct/ib/ud/base/ud_iface.h:385
#25 uct_ud_verbs_iface_progress (tl_iface=0x895220) at ib/ud/verbs/ud_verbs.c:385
#26 0x00007ffff7b7bb2a in ucs_callbackq_dispatch (cbq=<optimized out>) at /labhome/sergeyo/ucx/src/ucs/datastruct/callbackq.h:208
#27 uct_worker_progress (worker=<optimized out>) at /labhome/sergeyo/ucx/src/uct/api/uct.h:1631
#28 ucp_worker_progress (worker=0x866850) at core/ucp_worker.c:1277
#29 0x00007fffe79ef327 in mca_pml_ucx_progress () at pml_ucx.c:454
#30 0x00007ffff47ce9fc in opal_progress () at runtime/opal_progress.c:228
#31 0x00007ffff746dded in sync_wait_st (sync=<optimized out>) at ../opal/threads/wait_sync.h:83
#32 ompi_request_default_wait_all (count=4, requests=0x978b10, statuses=0x978b30) at request/req_wait.c:237
#33 0x00007ffff7495e7c in PMPI_Waitall (count=4, requests=requests@entry=0x978b10, statuses=statuses@entry=0x978b30) at pwaitall.c:77
#34 0x00007ffff774a819 in ompi_waitall_f (count=0x403170, array_of_requests=0x7fffffffbfd0, array_of_statuses=0x6043e0 <mpi_fortran_statuses_ignore_>, ierr=0x7fffffffc0c4) at pwaitall_f.c:104
#35 0x0000000000401f14 in allocmem_test () at allocmem_usempi.F90:156
#36 0x00000000004020ca in main (argc=1, argv=0x7fffffffc7d8) at allocmem_usempi.F90:2
#37 0x00007ffff63f1c05 in __libc_start_main () from /usr/lib64/libc.so.6
#38 0x0000000000401509 in _start ()
```
