### ISSUE TITLE
[mtt] UCX WARN got active message id 0, but no handler installed

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#2654]
Configuration:
```
OMPI: 3.1.1a1
MOFED: MLNX_OFED_LINUX-4.3-2.0.2.0
Nodes: hwi-arm x2 (ppn=64(x2), nodelist=hpc-arm-hwi[01-02])
Job: ucx
```

MTT log: http://hpcweb.lab.mtl.com//hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20180527_115701_42672_5517_hpc-arm-hwi01/html/test_stdout_2Zyotl.txt

Cmd:
`mpirun -np 64 --display-map -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_0:1,mlx5_3:1,mlx5_4:1 -x UCX_IB_ADDR_TYPE=ib_global -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=dc,sm -x UCX_IB_SL=1 -x UCX_RC_TM_ENABLE=n -mca pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0 -x UCX_MAX_EAGER_LANES=3 -x UCX_MAX_RNDV_LANES=3 --map-by node /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20180527_115701_42672_5517_hpc-arm-hwi01/installs/tYBh/tests/imb/imb/src/IMB-MPI1 -npmin 128 -iter 1000 -mem 0.9`

Output:

```sh
...
Sun May 27 12:24:33 2018[1,61]<stdout>:[1527413073.646167] [hpc-arm-hwi02:6875 :0]    ucp_context.c:586  UCX  WARN  device 'mlx5_3:1' is not available
Sun May 27 12:24:33 2018[1,39]<stdout>:[1527413073.646165] [hpc-arm-hwi02:6839 :0]    ucp_context.c:586  UCX  WARN  device 'mlx5_3:1' is not available
Sun May 27 12:24:33 2018[1,33]<stdout>:[1527413073.646168] [hpc-arm-hwi02:6823 :0]    ucp_context.c:586  UCX  WARN  device 'mlx5_3:1' is not available
Sun May 27 12:24:33 2018[1,0]<stdout>:#------------------------------------------------------------
Sun May 27 12:24:33 2018[1,0]<stdout>:#    Intel (R) MPI Benchmarks 4.1, MPI-1 part    
Sun May 27 12:24:33 2018[1,0]<stdout>:#------------------------------------------------------------
Sun May 27 12:24:33 2018[1,0]<stdout>:# Date                  : Sun May 27 12:24:33 2018
Sun May 27 12:24:33 2018[1,0]<stdout>:# Machine               : aarch64
Sun May 27 12:24:33 2018[1,0]<stdout>:# System                : Linux
Sun May 27 12:24:33 2018[1,0]<stdout>:# Release               : 4.11.0-44.el7a.aarch64
Sun May 27 12:24:33 2018[1,0]<stdout>:# Version               : #1 SMP Mon Oct 16 17:14:11 EDT 2017
Sun May 27 12:24:33 2018[1,0]<stdout>:# MPI Version           : 3.1
Sun May 27 12:24:33 2018[1,0]<stdout>:# MPI Thread Environment: 
Sun May 27 12:24:33 2018[1,0]<stdout>:
Sun May 27 12:24:33 2018[1,0]<stdout>:# New default behavior from Version 3.2 on:
Sun May 27 12:24:33 2018[1,0]<stdout>:
Sun May 27 12:24:33 2018[1,0]<stdout>:# the number of iterations per message size is cut down 
Sun May 27 12:24:33 2018[1,0]<stdout>:# dynamically when a certain run time (per message size sample) 
Sun May 27 12:24:33 2018[1,0]<stdout>:# is expected to be exceeded. Time limit is defined by variable 
Sun May 27 12:24:33 2018[1,0]<stdout>:# "SECS_PER_SAMPLE" (=> IMB_settings.h) 
Sun May 27 12:24:33 2018[1,0]<stdout>:# or through the flag => -time 
Sun May 27 12:24:33 2018[1,0]<stdout>:  
Sun May 27 12:24:33 2018[1,0]<stdout>:
Sun May 27 12:24:33 2018[1,0]<stdout>:
Sun May 27 12:24:33 2018[1,0]<stdout>:# Calling sequence was: 
Sun May 27 12:24:33 2018[1,0]<stdout>:
Sun May 27 12:24:33 2018[1,0]<stdout>:# /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20180527_115701_42672_5517_hpc-arm-hwi01/installs/tYBh/tests/imb/imb/src/IMB-MPI1 -npmin 128 -iter 1000 -mem 0.9
Sun May 27 12:24:33 2018[1,0]<stdout>:#                                                                                                                            
Sun May 27 12:24:33 2018[1,0]<stdout>:
Sun May 27 12:24:33 2018[1,0]<stdout>:# Minimum message length in bytes:   0
Sun May 27 12:24:33 2018[1,0]<stdout>:# Maximum message length in bytes:   4194304
Sun May 27 12:24:33 2018[1,0]<stdout>:#
Sun May 27 12:24:33 2018[1,0]<stdout>:# MPI_Datatype                   :   MPI_BYTE 
Sun May 27 12:24:33 2018[1,0]<stdout>:# MPI_Datatype for reductions    :   MPI_FLOAT
Sun May 27 12:24:33 2018[1,0]<stdout>:# MPI_Op                         :   MPI_SUM  
Sun May 27 12:24:33 2018[1,0]<stdout>:#
Sun May 27 12:24:33 2018[1,0]<stdout>:#
Sun May 27 12:24:33 2018[1,0]<stdout>:
Sun May 27 12:24:33 2018[1,0]<stdout>:# List of Benchmarks to run:
Sun May 27 12:24:33 2018[1,0]<stdout>:
Sun May 27 12:24:33 2018[1,0]<stdout>:# PingPong
Sun May 27 12:24:33 2018[1,0]<stdout>:# PingPing
Sun May 27 12:24:33 2018[1,0]<stdout>:# Sendrecv
Sun May 27 12:24:33 2018[1,0]<stdout>:# Exchange
Sun May 27 12:24:33 2018[1,0]<stdout>:# Allreduce
Sun May 27 12:24:33 2018[1,0]<stdout>:# Reduce
Sun May 27 12:24:33 2018[1,0]<stdout>:# Reduce_scatter
Sun May 27 12:24:33 2018[1,0]<stdout>:# Allgather
Sun May 27 12:24:33 2018[1,0]<stdout>:# Allgatherv
Sun May 27 12:24:33 2018[1,0]<stdout>:# Gather
Sun May 27 12:24:33 2018[1,0]<stdout>:# Gatherv
Sun May 27 12:24:33 2018[1,0]<stdout>:# Scatter
Sun May 27 12:24:33 2018[1,0]<stdout>:# Scatterv
Sun May 27 12:24:33 2018[1,0]<stdout>:# Alltoall
Sun May 27 12:24:33 2018[1,0]<stdout>:# Alltoallv
Sun May 27 12:24:33 2018[1,0]<stdout>:# Bcast
Sun May 27 12:24:33 2018[1,0]<stdout>:# BarrierSun May 27 12:24:33 2018[1,0]<stdout>:
Sun May 27 12:24:33 2018[1,0]<stdout>:#---------------------------------------------------
Sun May 27 12:24:33 2018[1,0]<stdout>:# Benchmarking PingPong 
Sun May 27 12:24:33 2018[1,0]<stdout>:# #processes = 2 
Sun May 27 12:24:33 2018[1,0]<stdout>:# ( 62 additional processes waiting in MPI_Barrier)
Sun May 27 12:24:33 2018[1,0]<stdout>:#---------------------------------------------------
Sun May 27 12:24:33 2018[1,0]<stdout>:       #bytes #repetitions      t[usec]   Mbytes/sec
Sun May 27 12:24:33 2018[1,0]<stdout>:            0         1000         3.26         0.00
Sun May 27 12:24:33 2018[1,0]<stdout>:            1         1000         3.22         0.30
Sun May 27 12:24:33 2018[1,0]<stdout>:            2         1000         3.06         0.62
Sun May 27 12:24:33 2018[1,0]<stdout>:            4         1000         3.07         1.24
Sun May 27 12:24:33 2018[1,0]<stdout>:            8         1000         3.08         2.47
Sun May 27 12:24:33 2018[1,0]<stdout>:           16         1000         3.09         4.94
Sun May 27 12:24:33 2018[1,0]<stdout>:           32         1000         3.11         9.82
Sun May 27 12:24:33 2018[1,0]<stdout>:           64         1000         3.23        18.89
Sun May 27 12:24:33 2018[1,0]<stdout>:          128         1000         3.88        31.45
Sun May 27 12:24:33 2018[1,0]<stdout>:          256         1000         4.06        60.10
Sun May 27 12:24:33 2018[1,0]<stdout>:          512         1000         4.44       110.01
Sun May 27 12:24:33 2018[1,0]<stdout>:         1024         1000         4.92       198.67
Sun May 27 12:24:33 2018[1,0]<stdout>:         2048         1000         5.90       330.96
Sun May 27 12:24:34 2018[1,0]<stdout>:         4096         1000         7.86       497.19
Sun May 27 12:24:34 2018[1,0]<stdout>:         8192         1000        12.31       634.68
Sun May 27 12:24:34 2018[1,0]<stdout>:        16384         1000        16.16       966.77
Sun May 27 12:24:34 2018[1,1]<stdout>:[1527413074.098187] [hpc-arm-hwi02:6797 :0]      uct_iface.c:54   UCX  WARN  got active message id 0, but no handler installed

node=hpc-arm-hwi01, pid=12413:
Thread 4 (Thread 0xffffb74cf1e0 (LWP 12445)):
#0  0x0000ffffb7d8b80c in epoll_pwait () from /usr/lib64/libc.so.6
#1  0x0000ffffb7b34438 in epoll_dispatch (base=0x4a5690, tv=<optimized out>) at epoll.c:407
#2  0x0000ffffb7b37e8c in opal_libevent2022_event_base_loop (base=0x4a5690, flags=flags@entry=1) at event.c:1630
#3  0x0000ffffb7af8e8c in progress_engine (obj=<optimized out>) at runtime/opal_progress_threads.c:105
#4  0x0000ffffb7e47bb0 in start_thread () from /usr/lib64/libpthread.so.0
#5  0x0000ffffb7d8b630 in thread_start () from /usr/lib64/libc.so.6
Thread 3 (Thread 0xffffb677f1e0 (LWP 12453)):
#0  0x0000ffffb7d8b80c in epoll_pwait () from /usr/lib64/libc.so.6
#1  0x0000ffffb7b34438 in epoll_dispatch (base=0x4de470, tv=<optimized out>) at epoll.c:407
#2  0x0000ffffb7b37e8c in opal_libevent2022_event_base_loop (base=0x4de470, flags=flags@entry=1) at event.c:1630
#3  0x0000ffffb69f27d0 in progress_engine (obj=<optimized out>) at runtime/pmix_progress_threads.c:109
#4  0x0000ffffb7e47bb0 in start_thread () from /usr/lib64/libpthread.so.0
#5  0x0000ffffb7d8b630 in thread_start () from /usr/lib64/libc.so.6
Thread 2 (Thread 0xffffafd5f1e0 (LWP 12553)):
#0  0x0000ffffb7d8b80c in epoll_pwait () from /usr/lib64/libc.so.6
#1  0x0000ffffb449c61c in ucs_async_thread_func (arg=0x72b110) at async/thread.c:93
#2  0x0000ffffb7e47bb0 in start_thread () from /usr/lib64/libpthread.so.0
#3  0x0000ffffb7d8b630 in thread_start () from /usr/lib64/libc.so.6
Thread 1 (Thread 0xffffb800a6a0 (LWP 12413)):
#0  opal_timer_linux_get_cycles_sys_timer () at timer_linux_component.c:236
#1  0x0000ffffb7af2fc8 in opal_progress_events () at runtime/opal_progress.c:181
#2  opal_progress () at runtime/opal_progress.c:242
#3  0x0000ffffb7ef7350 in ompi_request_wait_completion (req=0x8c18e0) at ../ompi/request/request.h:413
#4  ompi_request_default_wait (req_ptr=0xffffffffc920, status=0xffffffffc928) at request/req_wait.c:42
#5  0x0000ffffb7f2f728 in ompi_coll_base_sendrecv_actual (sendbuf=sendbuf@entry=0xffffffffcb38, scount=scount@entry=1, sdatatype=sdatatype@entry=0x431350 <ompi_mpi_int>, dest=dest@entry=30, stag=stag@entry=-12, recvbuf=recvbuf@entry=0x8aced0, rcount=rcount@entry=1, rdatatype=rdatatype@entry=0x431350 <ompi_mpi_int>, source=source@entry=30, rtag=rtag@entry=-12, comm=comm@entry=0x432560 <ompi_mpi_comm_world>, status=status@entry=0x0) at base/coll_base_util.c:59
#6  0x0000ffffb7f2fb44 in ompi_coll_base_allreduce_intra_recursivedoubling (sbuf=<optimized out>, rbuf=0xffffffffcb38, count=1, dtype=0x431350 <ompi_mpi_int>, op=0x431760 <ompi_mpi_op_max>, comm=0x432560 <ompi_mpi_comm_world>, module=<optimized out>) at base/coll_base_allreduce.c:217
#7  0x0000ffffb7f08514 in PMPI_Allreduce (sendbuf=<optimized out>, recvbuf=<optimized out>, count=<optimized out>, datatype=<optimized out>, op=0x431760 <ompi_mpi_op_max>, comm=0x432560 <ompi_mpi_comm_world>) at pallreduce.c:110
#8  0x00000000004027d4 in main ()
```

**Comment by amaslenn** [comment]
It could be unstable setup, but I was able to reproduce it at least once, so worth to mention.

**Comment by yosefe** [comment]
related to https://gitlab.com/Mellanox/huawei/issues/19

**Comment by yosefe** [comment]
closing this since it's related to a particular setup

**Comment by duqi-hnu** [comment]
How is this problem solved? What is this particular setting?

**Comment by yosefe** [comment]
> How is this problem solved? What is this particular setting?

@duqi-hnu seems there was an issue with the setup
if you also see a similar issue, pls open a separate ticket :)

**Comment by duqi-hnu** [comment]
@yosefe  The bug information has been submitted.[https://github.com/openucx/ucx/issues/9819](url)
