### ISSUE TITLE
uct_hello_world segfaults over tcp

### ISSUE THREAD

**Issue by bbenton** [openucx/ucx#2861]
uct_hello_world over a tcp transport appears to transmit data properly, but then segfaults when freeing resources.  This failure occurs with both master and v1.4.x.  UCX was configured with defaults  plus `--enable-debug-data` and uct_hello_world was built with `-O0 -g`.

Here is a stack backtrace of the failure

```
bbenton@sm-7:ucx-master$ test/examples/uct_hello_world -d eno2 -t tcp -b
INFO: UCT_HELLO_WORLD AM function = uct_ep_am_bcopy server = (null) port = 13337
Using eno2 with tcp.
Waiting for connection...


----- UCT TEST SUCCESS ----

[callback] uct_ep_am_bcopy sent MQXFIDMNFJKZMBM

---------------------------


----- UCT TEST SUCCESS ----

[main] uct_ep_am_bcopy sent MQXFIDMNFJKZMBM

---------------------------
[sm-7:19318:0:19318] Caught signal 11 (Segmentation fault: address not mapped to object at address 0xfffffffffffffff9)
==== backtrace ====
    0  /home/bbenton/opt/lib/libucs.so.0(+0x1db4d) [0x7f8f1469bb4d]
    1  /home/bbenton/opt/lib/libucs.so.0(+0x1dd90) [0x7f8f1469bd90]
    2  /lib/x86_64-linux-gnu/libc.so.6(cfree+0x22) [0x7f8f14338512]
    3  test/examples/uct_hello_world() [0x403ba9]
    4  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f8f142d4830]
    5  test/examples/uct_hello_world() [0x401909]
===================
[sm-7:19318:0:19318] Process frozen, press Enter to attach a debugger...

Attaching to process 19318
[New LWP 19322]
[New LWP 19323]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f8f143800cb in __GI___waitpid (pid=pid@entry=19324, stat_loc=stat_loc@entry=0x7f8f14d72a5c,
    options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
29  ../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
#0  0x00007f8f143800cb in __GI___waitpid (pid=pid@entry=19324, stat_loc=stat_loc@entry=0x7f8f14d72a5c,
    options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
#1  0x00007f8f1469a376 in ucs_debugger_attach () at debug/debug.c:703
#2  0x00007f8f1469b7fc in ucs_error_freeze (
    message=0x7f8f14d72d50 "Caught signal 11 (Segmentation fault: address not mapped to object at address 0x", 'f' <repeats 15 times>, "9)", error_type=0x7f8f146aed45 "address not mapped to object")
    at debug/debug.c:822
#3  ucs_handle_error (error_type=error_type@entry=0x7f8f146aed45 "address not mapped to object",
    message=message@entry=0x7f8f146aeb8f "Caught signal %d (%s: %s%s)") at debug/debug.c:997
#4  0x00007f8f1469bb4d in ucs_debug_handle_error_signal (signo=signo@entry=11,
    cause=0x7f8f146aed45 "address not mapped to object", fmt=fmt@entry=0x7f8f146aede7 " at address %p")
    at debug/debug.c:934
#5  0x00007f8f1469bd90 in ucs_error_signal_handler (signo=11, info=0x7f8f14d735f0,
    context=<optimized out>) at debug/debug.c:957
#6  <signal handler called>
#7  __GI___libc_free (mem=0x1) at malloc.c:2951
#8  0x0000000000403ba9 in main (argc=6, argv=0x7ffef8ced7a8)
    at /home/bbenton/opt/share/ucx/examples/uct_hello_world.c:646
24  in ../sysdeps/unix/sysv/linux/waitpid.c
(gdb) up 8
#8  0x0000000000403ba9 in main (argc=6, argv=0x7ffef8ced7a8)
    at /home/bbenton/opt/share/ucx/examples/uct_hello_world.c:646
646     free(own_ep);
(gdb) l
641     close(oob_sock);
642
643 out_free_ep:
644     uct_ep_destroy(ep);
645 out_free_ep_addrs:
646     free(own_ep);
647     free(peer_ep);
648 out_free_if_addrs:
649     free(own_iface);
650     free(peer_iface);
(gdb) p own_ep
$1 = (uct_ep_addr_t *) 0x1
(gdb) p peer_ep
$2 = (uct_ep_addr_t *) 0x0
(gdb)
```

Is this supposed to work?  Or is it a known problem?

**Comment by shamisp** [comment]
Adding @hoopoepg
