### ISSUE TITLE
[mtt] slow execution with lanes in OSU

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#3045]
Configuration
```
OMPI: 4.0.0rc5
MOFED: MLNX_OFED_LINUX-4.4-2.0.7.0
Module: hpcx-gcc (2018-11-15)
Test module: mtt-tests/hpcx-gcc
Nodes: hercules x47 (ppn=32(x47), nodelist=clx-hercules-[031-032,061-064,073-113])
```

MTT log: http://e2e-gw.mellanox.com:4080/mnt/lustre/users/mtt/scratch/ucx_ompi/20181116_231231_21435_232844_clx-hercules-031/html/test_stdout_dzA5OQ.txt

Works well with `-x UCX_MAX_EAGER_LANES=1 -x UCX_MAX_RNDV_LANES=1`.

Cmd (original NP=32):
`mpirun -np 4 -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_2:1,mlx5_3:1 -mca osc '^ucx' -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=all -x UCX_RC_TM_ENABLE=n -mca pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0 -x UCX_MAX_EAGER_LANES=3 -x UCX_MAX_RNDV_LANES=3 -x UCX_IB_TRAFFIC_CLASS=106 -x UCX_IB_GID_INDEX=auto --map-by node /hpc/local/benchmarks/hpcx_install_2018-11-15/mtt-tests-gcc/installs/uuGb/tests/osu_micro_benchmark/osu-micro-benchmarks-5.3.2/mpi/collective/osu_igather`

Output:
```sh
 =============================================================Sat Nov 17 00:20:52 2018[1,0]<stdout>:
Sat Nov 17 00:20:52 2018[1,0]<stdout>:# OSU MPI Non-blocking Gather Latency Test v5.3.2
Sat Nov 17 00:20:52 2018[1,0]<stdout>:# Overall = Coll. Init + Compute + MPI_Test + MPI_Wait
Sat Nov 17 00:20:52 2018[1,0]<stdout>:
Sat Nov 17 00:20:52 2018[1,0]<stdout>:# Size           Overall(us)       Compute(us)    Pure Comm.(us)        Overlap(%)Sat Nov 17 00:20:52 2018[1,0]<stdout>:1                       1.93              1.11              0.71              0.00
Sat Nov 17 00:20:52 2018[1,0]<stdout>:2                       1.91              1.11              0.70              0.00
Sat Nov 17 00:20:52 2018[1,0]<stdout>:4                       1.94              1.14              0.71              0.00
Sat Nov 17 00:20:52 2018[1,0]<stdout>:8                       1.94              1.13              0.71              0.00
Sat Nov 17 00:20:52 2018[1,0]<stdout>:16                      1.94              1.13              0.71              0.00
Sat Nov 17 00:20:52 2018[1,0]<stdout>:32                      1.92              1.11              0.70              0.00
Sat Nov 17 00:20:52 2018[1,0]<stdout>:64                      2.13              1.22              0.85              0.00
Sat Nov 17 00:20:53 2018[1,0]<stdout>:128                     2.23              1.27              0.90              0.00
Sat Nov 17 00:20:53 2018[1,0]<stdout>:256                     2.41              1.30              1.08              0.00
Sat Nov 17 00:20:53 2018[1,0]<stdout>:512                     2.48              1.33              1.12              0.00
Sat Nov 17 00:20:53 2018[1,0]<stdout>:1024                    2.74              1.44              1.26              0.00
Sat Nov 17 00:20:53 2018[1,0]<stdout>:2048                    7.08              5.51              4.85             67.81
Sat Nov 17 00:20:53 2018[1,0]<stdout>:4096                   14.76             12.72             11.74             82.67
Sat Nov 17 00:20:55 2018[1,0]<stdout>:8192                   20.08             16.97             15.95             80.45
Sat Nov 17 00:27:48 2018[1,0]<stdout>:16384              347946.62         218750.21         211417.46             38.89
Sat Nov 17 00:34:21 2018[1,0]<stdout>:32768              298321.70         183948.39         177641.39             35.62
Sat Nov 17 00:41:12 2018[1,0]<stdout>:65536             1550958.09         312435.74         301784.64              0.00
Sat Nov 17 00:42:40 2018[1,0]<stdout>:131072             323108.01          39908.73          38556.18              0.00
Sat Nov 17 00:46:09 2018[1,0]<stdout>:262144             980128.85         129178.80         124812.66              0.00

node=clx-hercules-031, pid=13595:
Thread 4 (Thread 0x7ffff3b84700 (LWP 13600)):
#0  0x00007ffff6de0113 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007ffff67948c3 in epoll_dispatch (base=0x66cab0, tv=<optimized out>) at epoll.c:407
#2  0x00007ffff6798310 in opal_libevent2022_event_base_loop (base=0x66cab0, flags=flags@entry=1) at event.c:1630
#3  0x00007ffff6754c3e in progress_engine (obj=<optimized out>) at runtime/opal_progress_threads.c:105
#4  0x00007ffff70b5dd5 in start_thread () from /usr/lib64/libpthread.so.0
#5  0x00007ffff6ddfb3d in clone () from /usr/lib64/libc.so.6
Thread 3 (Thread 0x7ffff0da7700 (LWP 13601)):
#0  0x00007ffff6de0113 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007ffff67948c3 in epoll_dispatch (base=0x6abd90, tv=<optimized out>) at epoll.c:407
#2  0x00007ffff6798310 in opal_libevent2022_event_base_loop (base=0x6abd90, flags=flags@entry=1) at event.c:1630
#3  0x00007ffff2ceb75e in progress_engine (obj=<optimized out>) at runtime/pmix_progress_threads.c:109
#4  0x00007ffff70b5dd5 in start_thread () from /usr/lib64/libpthread.so.0
#5  0x00007ffff6ddfb3d in clone () from /usr/lib64/libc.so.6
Thread 2 (Thread 0x7fffe2b66700 (LWP 13622)):
#0  0x00007ffff6de0113 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007fffe8d25214 in ucs_async_thread_func (arg=0x73aa20) at async/thread.c:93
#2  0x00007ffff70b5dd5 in start_thread () from /usr/lib64/libpthread.so.0
#3  0x00007ffff6ddfb3d in clone () from /usr/lib64/libc.so.6
Thread 1 (Thread 0x7ffff7fc8780 (LWP 13595)):
#0  opal_sys_timer_get_cycles () at ../../../../opal/include/opal/sys/x86_64/timer.h:42
#1  opal_timer_linux_get_cycles_sys_timer () at timer_linux_component.c:232
#2  0x00007ffff674eed9 in opal_progress_events () at runtime/opal_progress.c:183
#3  opal_progress () at runtime/opal_progress.c:245
#4  0x00007ffff7b34805 in ompi_request_wait_completion (req=0x9fa5b8) at ../ompi/request/request.h:415
#5  ompi_request_default_wait (req_ptr=0x7fffffffb968, status=0x7fffffffb970) at request/req_wait.c:42
#6  0x00007ffff7b5cd2a in PMPI_Wait (request=request@entry=0x7fffffffb968, status=status@entry=0x7fffffffb970) at pwait.c:74
#7  0x0000000000401361 in main (argc=1, argv=0x7fffffffba98) at osu_igather.c:109

node=clx-hercules-032, pid=15596:
Thread 4 (Thread 0x7ffff3b84700 (LWP 15599)):
#0  0x00007ffff6de0113 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007ffff67948c3 in epoll_dispatch (base=0x66cba0, tv=<optimized out>) at epoll.c:407
#2  0x00007ffff6798310 in opal_libevent2022_event_base_loop (base=0x66cba0, flags=flags@entry=1) at event.c:1630
#3  0x00007ffff6754c3e in progress_engine (obj=<optimized out>) at runtime/opal_progress_threads.c:105
#4  0x00007ffff70b5dd5 in start_thread () from /usr/lib64/libpthread.so.0
#5  0x00007ffff6ddfb3d in clone () from /usr/lib64/libc.so.6
Thread 3 (Thread 0x7ffff0da7700 (LWP 15600)):
#0  0x00007ffff6de0113 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007ffff67948c3 in epoll_dispatch (base=0x6abea0, tv=<optimized out>) at epoll.c:407
#2  0x00007ffff6798310 in opal_libevent2022_event_base_loop (base=0x6abea0, flags=flags@entry=1) at event.c:1630
#3  0x00007ffff2ceb75e in progress_engine (obj=<optimized out>) at runtime/pmix_progress_threads.c:109
#4  0x00007ffff70b5dd5 in start_thread () from /usr/lib64/libpthread.so.0
#5  0x00007ffff6ddfb3d in clone () from /usr/lib64/libc.so.6
Thread 2 (Thread 0x7fffe2b66700 (LWP 15617)):
#0  0x00007ffff6de0113 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007fffe8d25214 in ucs_async_thread_func (arg=0x73bd70) at async/thread.c:93
#2  0x00007ffff70b5dd5 in start_thread () from /usr/lib64/libpthread.so.0
#3  0x00007ffff6ddfb3d in clone () from /usr/lib64/libc.so.6
Thread 1 (Thread 0x7ffff7fc8780 (LWP 15596)):
#0  0x00007fffe9f9c572 in mca_pml_ucx_progress () at pml_ucx.c:452
#1  0x00007ffff674edbc in opal_progress () at runtime/opal_progress.c:231
#2  0x00007ffff7b34805 in ompi_request_wait_completion (req=0xa2b428) at ../ompi/request/request.h:415
#3  ompi_request_default_wait (req_ptr=0x7fffffffb4c0, status=0x7fffffffb4d0) at request/req_wait.c:42
#4  0x00007ffff7b786c4 in ompi_coll_base_sendrecv_zero (stag=-16, rtag=-16, comm=0x605b40 <ompi_mpi_comm_world>, source=0, dest=0) at base/coll_base_barrier.c:64
#5  ompi_coll_base_barrier_intra_recursivedoubling (comm=0x605b40 <ompi_mpi_comm_world>, module=<optimized out>) at base/coll_base_barrier.c:215
#6  0x00007ffff7b48618 in PMPI_Barrier (comm=0x605b40 <ompi_mpi_comm_world>) at pbarrier.c:74
#7  0x000000000040138b in main (argc=1, argv=0x7fffffffb768) at osu_igather.c:116
```

**Comment by yosefe** [comment]
hercules was not lossless
