### ISSUE TITLE
[mtt] segfault in many tests with TLS=rc

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#3259]
Configuration
```
OMPI: 4.0.1rc1
MOFED: MLNX_OFED_LINUX-4.5-1.0.1.0
Module: hpcx-gcc (2019-02-23)
Test module: mtt-tests/hpcx-gcc
Nodes: hercules x8 (ppn=32(x8), nodelist=clx-hercules-[087-094])
Job: ucx-hwtm-rc
```

MTT log: http://e2e-gw.mellanox.com:4080/hpc/scrap/users/mtt/scratch/ucx_ompi/20190223_204135_11069_314975_clx-hercules-087/html/test_stdout_BVIgpN.txt

Works OK with `rc_x`, `dc/dc_x`, `ud/ud_x`.

Cmd (orig `np` was 256):
`mpirun -np 64 --report-bindings -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_2:1 -mca osc ucx -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=rc,self,sm -x UCX_RC_VERBS_TM_ENABLE=y -mca pmix_base_async_modex 0 -mca mpi_add_procs_cutoff 100000 -mca pmix_base_collect_data 1 --map-by node /hpc/local/benchmarks/hpcx_install_2019-02-23/mtt-tests-gcc/installs/qQmc/tests/ibm-tests/ompi-tests/ibm/pt2pt/test1`

```sh
Sat Feb 23 20:47:48 2019[1,109]<stderr>:[clx-hercules-092:5133 :0:5133] address not mapped to object
Sat Feb 23 20:47:48 2019[1,69]<stderr>:[clx-hercules-092:5128 :0:5128] address not mapped to object
Sat Feb 23 20:47:48 2019[1,109]<stderr>:==== backtrace ====
Sat Feb 23 20:47:48 2019[1,109]<stderr>: 0 0x0000000000043140 ucs_list_insert_replace()  /hpc/local/benchmarks/hpcx_install_2019-02-23/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/datastruct/list.h:47
Sat Feb 23 20:47:48 2019[1,109]<stderr>: 1 0x000000000003e889 ucs_arbiter_dispatch()  /hpc/local/benchmarks/hpcx_install_2019-02-23/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/datastruct/arbiter.h:318
Sat Feb 23 20:47:48 2019[1,109]<stderr>: 2 0x0000000000038fcf uct_ud_iface_async_progress()  /hpc/local/benchmarks/hpcx_install_2019-02-23/src/hpcx-gcc-redhat7.4/ucx-master/src/uct/ib/ud/base/ud_iface.c:831
Sat Feb 23 20:47:48 2019[1,109]<stderr>: 3 0x000000000003c19f __ucs_async_poll_missed()  /hpc/local/benchmarks/hpcx_install_2019-02-23/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/async/async.c:579
Sat Feb 23 20:47:48 2019[1,109]<stderr>: 4 0x0000000000019103 ucs_async_check_miss()  /hpc/local/benchmarks/hpcx_install_2019-02-23/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/async/async.h:78
Sat Feb 23 20:47:48 2019[1,109]<stderr>: 5 0x000000000000540a mca_pml_ucx_send_nbr()  /hpc/local/benchmarks/hpcx_install_2019-02-23/src/hpcx-gcc-redhat7.4/ompi/ompi/mca/pml/ucx/pml_ucx.c:817
Sat Feb 23 20:47:48 2019[1,109]<stderr>: 6 0x000000000008fc28 ompi_coll_base_sendrecv_zero()  /hpc/local/benchmarks/hpcx_install_2019-02-23/src/hpcx-gcc-redhat7.4/ompi/ompi/mca/coll/base/coll_base_barrier.c:60
Sat Feb 23 20:47:48 2019[1,109]<stderr>: 7 0x000000000005f928 PMPI_Barrier()  /hpc/local/benchmarks/hpcx_install_2019-02-23/src/hpcx-gcc-redhat7.4/ompi/ompi/mpi/c/profile/pbarrier.c:74
Sat Feb 23 20:47:48 2019[1,109]<stderr>: 8 0x0000000000401069 main()  /hpc/local/benchmarks/hpcx_install_2019-02-23/mtt-tests-gcc/installs/qQmc/tests/ibm-tests/ompi-tests/ibm/pt2pt/test1.c:74
Sat Feb 23 20:47:48 2019[1,109]<stderr>: 9 0x00000000000223d5 __libc_start_main()  ???:0
Sat Feb 23 20:47:48 2019[1,109]<stderr>:10 0x0000000000400e49 _start()  ???:0
Sat Feb 23 20:47:48 2019[1,109]<stderr>:===================Sat Feb 23 20:47:48 2019[1,69]<stderr>:==== backtrace ====
```

**Comment by amaslenn** [comment]
Similar trace in `ctxalloc`:
`mpirun -np 256 --report-bindings -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_2:1 -mca osc ucx -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=rc,self,sm -x UCX_RC_VERBS_TM_ENABLE=y -mca pmix_base_async_modex 0 -mca mpi_add_procs_cutoff 100000 -mca pmix_base_collect_data 1 --map-by node /hpc/local/benchmarks/hpcx_install_2019-02-23/mtt-tests-gcc/installs/qQmc/tests/mpi-small-tests/hpc_tests.git/mpi/misc/ctxalloc 2 1500 100`

Output:
```sh
Sun Feb 24 04:46:55 2019[1,55]<stderr>:==== backtrace ====
Sun Feb 24 04:46:55 2019[1,55]<stderr>: 0 0x0000000000043140 ucs_list_insert_replace()  /hpc/local/benchmarks/hpcx_install_2019-02-23/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/datastruct/list.h:47
Sun Feb 24 04:46:55 2019[1,55]<stderr>: 1 0x000000000003f127 ucs_arbiter_dispatch()  /hpc/local/benchmarks/hpcx_install_2019-02-23/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/datastruct/arbiter.h:318
Sun Feb 24 04:46:55 2019[1,55]<stderr>: 2 0x00000000000190d2 ucs_callbackq_dispatch()  /hpc/local/benchmarks/hpcx_install_2019-02-23/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/datastruct/callbackq.h:209
Sun Feb 24 04:46:55 2019[1,55]<stderr>: 3 0x00000000000036d7 mca_pml_ucx_progress()  /hpc/local/benchmarks/hpcx_install_2019-02-23/src/hpcx-gcc-redhat7.4/ompi/ompi/mca/pml/ucx/pml_ucx.c:509
Sun Feb 24 04:46:55 2019[1,55]<stderr>: 4 0x0000000000036dbc opal_progress()  /hpc/local/benchmarks/hpcx_install_2019-02-23/src/hpcx-gcc-redhat7.4/ompi/opal/runtime/opal_progress.c:231
Sun Feb 24 04:46:55 2019[1,55]<stderr>: 5 0x00000000000336cd ompi_request_wait_completion()  /hpc/local/benchmarks/hpcx_install_2019-02-23/src/hpcx-gcc-redhat7.4/ompi/ompi/../ompi/request/request.h:415
Sun Feb 24 04:46:55 2019[1,55]<stderr>: 6 0x000000000003544d ompi_comm_nextcid()  /hpc/local/benchmarks/hpcx_install_2019-02-23/src/hpcx-gcc-redhat7.4/ompi/ompi/communicator/comm_cid.c:293
Sun Feb 24 04:46:55 2019[1,55]<stderr>: 7 0x00000000000306db ompi_comm_dup_with_info()  /hpc/local/benchmarks/hpcx_install_2019-02-23/src/hpcx-gcc-redhat7.4/ompi/ompi/communicator/comm.c:1007
Sun Feb 24 04:46:55 2019[1,55]<stderr>: 8 0x0000000000061476 PMPI_Comm_dup()  /hpc/local/benchmarks/hpcx_install_2019-02-23/src/hpcx-gcc-redhat7.4/ompi/ompi/mpi/c/profile/pcomm_dup.c:63
Sun Feb 24 04:46:55 2019[1,55]<stderr>: 9 0x0000000000400b6b main()  /hpc/local/benchmarks/hpcx_install_2019-02-23/mtt-tests-gcc/installs/qQmc/tests/mpi-small-tests/hpc_tests.git/mpi/misc/ctxalloc.c:38
Sun Feb 24 04:46:55 2019[1,55]<stderr>:10 0x00000000000223d5 __libc_start_main()  ???:0
Sun Feb 24 04:46:55 2019[1,55]<stderr>:11 0x0000000000400969 _start()  ???:0
Sun Feb 24 04:46:55 2019[1,55]<stderr>:===================--------------------------------------------------------------------------
```

And many other tests here: http://e2e-gw.mellanox.com:4080/hpc/scrap/users/mtt/scratch/ucx_ompi/20190224_044449_5885_315459_clx-hercules-049/

**Comment by yosefe** [comment]
@brminich seems related to arbiter changes

**Comment by brminich** [comment]
yes

**Comment by yosefe** [comment]
```
[‎25/‎02/‎2019 11:33]  Mikhail Brinskii:  
#6  0x00007ffff69ecd0b in ucs_arbiter_dispatch_nonempty (... 
#6  0x00007ffff69ecd0b in ucs_arbiter_dispatch_nonempty (arbiter=0x7bdd20, per_group=1, cb=0x7fffecb7a518 <uct_ud_ep_do_pending>, cb_arg=0x1) at datastruct/arbiter.c:213
#7  0x00007fffecb7bc0c in ucs_arbiter_dispatch (arbiter=0x7bdd20, per_group=1, cb=0x7fffecb7a518 <uct_ud_ep_do_pending>, cb_arg=0x1) at /labhome/mikhailb/ucx/src/ucs/datastruct/arbiter.h:318
#8  0x00007fffecb80e71 in uct_ud_iface_progress_pending (is_async=<optimized out>, iface=0x7bd670) at /labhome/mikhailb/ucx/src/uct/ib/ud/base/ud_iface.h:389
#9  uct_ud_verbs_iface_async_progress (ud_iface=0x7bd670) at ud/verbs/ud_verbs.c:370
#10 0x00007fffecb74068 in uct_ud_iface_async_progress (iface=0x7bd670) at ud/base/ud_iface.c:831
#11 0x00007fffecb74265 in uct_ud_iface_timer (timer_id=1000000, arg=0x7bd670) at ud/base/ud_iface.c:846
#12 0x00007ffff69e4971 in __ucs_async_poll_missed (async=0x7ffff7f1d018) at async/async.c:579
#13 0x00007ffff7b3e171 in ucs_async_check_miss (async=0x7ffff7f1d018) at /labhome/mikhailb/ucx/src/ucs/async/async.h:78
#14 0x00007ffff7b4340b in ucp_worker_progress (worker=0x7ffff7f1d010) at core/ucp_worker.c:1633
#15 0x00007fffed1bb6d7 in mca_pml_ucx_progress () at pml_ucx.c:509
#16 0x00007ffff59c4dbc in opal_progress () at runtime/opal_progress.c:231
#17 0x00007ffff755e6cd in ompi_request_wait_completion (req=0xfab3a8) at ../ompi/request/request.h:415
#18 0x00007ffff756044d in ompi_comm_nextcid (newcomm=<optimized out>, comm=comm@entry=0x602480 <ompi_mpi_comm_world>, bridgecomm=bridgecomm@entry=0x0, arg0=arg0@entry=0x0, arg1=arg1@entry=0x0, send_first=send_first@entry=false,
    mode=mode@entry=32) at communicator/comm_cid.c:293
#19 0x00007ffff755b6db in ompi_comm_dup_with_info (comm=comm@entry=0x602480 <ompi_mpi_comm_world>, info=info@entry=0x0, newcomm=0x7fffffffbe68) at communicator/comm.c:1007
#20 0x00007ffff755b7da in ompi_comm_dup (comm=comm@entry=0x602480 <ompi_mpi_comm_world>, newcomm=<optimized out>) at communicator/comm.c:972
#21 0x00007ffff758c476 in PMPI_Comm_dup (comm=0x602480 <ompi_mpi_comm_world>, newcomm=<optimized out>) at pcomm_dup.c:63
#22 0x0000000000400b6b in main (argc=4, argv=0x7fffffffbfb8) at ctxalloc.c:38 
 ```
