### ISSUE TITLE
Getting: UCX Assertion `length >= hdr_len' failed

### ISSUE THREAD

**Issue by akesandgren** [openucx/ucx#3270]
We're getting
eager_rcv.c:83   UCX Assertion `length >= hdr_len' failed
from time to time, consistently for a specific test case, and probably at least one more.

Sometime prior to that we also see repeated occurances of
[t-cn0303][[28739,25948],74][btl_tcp.c:559:mca_btl_tcp_recv_blocking] recv(52) failed: Connection reset by peer (104)
from various nodes/tasks.

Job started with srun.
Slurm 18.08.4 built with
./configure --disable-debug --prefix=/lap/slurm/${version} --sysconfdir=/etc/slurm --with-munge --with-pam_dir=/lap/slurm/${version}/lib/pam --with-ucx=/lap/ucx/1.4.0 --with-pmix=/lap/pmix/3.1.1:/lap/pmix/2.2.1:/lap/pmix/1.2.5 --enable-salloc-kill-cmd

OpenMPI 3.1.1 built with
./configure --prefix=/hpc2n/eb/software/Compiler/GCC/7.3.0-2.30/OpenMPI/3.1.1 --enable-shared --with-verbs --enable-mpirun-prefix-by-default --with-hwloc=/.../hwloc/1.11.10  --with-pmix=/.../pmix/2.2.1 --with-libevent=/.../libevent/2.1.8 --with-ucx=/.../ucx/1.4.0 --with-cma --with-lustre

Also tested using UCX 1.5.0 for both slurm and OpenMPI.

Code in question is VASP so not easily used for testing, but we have seen it in another code (just can't remember which one at the moment).

**Comment by yosefe** [comment]
@akesandgren thanks for the report, it means a sent message is shorter than expected.
1. what fabric type is used?
1. which versions of OFED/MLNX_OFED/verbs are installed?
1. what was the command line to run VASP? 
1. How many ranks?
1. How long does it take to fail?
1. can you pls run with UCX_LOG_LEVEL=data and provide the output?

**Comment by akesandgren** [comment]
We see the same issue on both our clusters.
1 - One has ConnectX-2 cards (mlx4 driver) and the other has Connect-IB (mlx5 driver)

2 - OFED is currently MOFED 3.3 (and I do know it is old but we're still on Ubuntu 16.04 and haven't bothered upgrading until we move to 18.04)

3 - We do use ( in this case)
srun vasp_std
to start VASP

4 - In the VASP case we used 84 mpi-tasks (sbatch -n 84)
5 - Time to failure varies, last run took 31 hours
6 - will try...

**Comment by akesandgren** [comment]
Running with UCX_LOG_LEVEL=data resulted in a core dump in a different way.
The output with the UCX_LOG data is ~134G
The core dumps say:
```
#0  0x00002ae08ab73428 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00002ae08ab7502a in __GI_abort () at abort.c:89
#2  0x00002ae0935ffda7 in ucs_fatal_error (
    error_type=error_type@entry=0x2ae09339a5be "fatal error", 
    file=file@entry=0x2ae09339a060 "ib/ud/base/ud_iface.c", 
    line=line@entry=732, 
    function=function@entry=0x2ae09339aa30 <__FUNCTION__.40850> "uct_ud_ep_dispatch_err_comp", format=format@entry=0x2ae09339a714 "Fatal: transport error: %s")
    at debug/assert.c:35
#3  0x00002ae093374472 in uct_ud_ep_dispatch_err_comp (skb=<optimized out>, 
    ep=0xb1b7160) at ib/ud/base/ud_iface.c:732
#4  uct_ud_iface_dispatch_async_comps_do (iface=iface@entry=0xb131250)
    at ib/ud/base/ud_iface.c:754
#5  0x00002ae09337ad90 in uct_ud_iface_dispatch_zcopy_comps (iface=0xb131250)
    at /scratch/eb-ake/UCX/1.5.0/GCCcore-7.3.0/ucx-1.5.0/src/uct/ib/ud/base/ud_iface.h:445
#6  uct_ud_verbs_iface_progress (tl_iface=0xb131250)
    at ib/ud/verbs/ud_verbs.c:376
```

Do you want the UCX_LOG output or parts of it?

**Comment by yosefe** [comment]
@akesandgren thanks, the error abouve is a timeout and may happen because of log write slowdown
is there an option to upgrade MLNX_OFED? the latest release is 4.5

**Comment by akesandgren** [comment]
As I said above, it will happen when we upgrade to Ubuntu 18.04 sometime before summer.
