### ISSUE TITLE
dcx/test_ucp_rma_mt.put_get timeout on ThunderX2

### ISSUE THREAD

**Issue by shamisp** [openucx/ucx#3704]
``` make -C test/gtest/ test -j 32 GTEST_FILTER=*dcx/test_ucp_rma_mt.put_get*```
```
/home/pavsha01/ucx.master/contrib/../test/gtest/common/test_helpers.cc:46: Failure
Failed
Connection timed out - abort testing
```

The test hangs for a while and then aborts. Tested with master.

**Comment by shamisp** [comment]
@yosefe I sent you trace in email.

**Comment by shamisp** [comment]
@yosefe It seems like it has something to do with multi-rail. I have one ROCE and one IB NIC one the node. When I explicitly set UCX_NET_DEVICES to one of the devices, it passes the test. I don't think it has anything to do with Arm specifically.

**Comment by shamisp** [comment]
```OFED-internal-4.3-1.0.1:
```

**Comment by shamisp** [comment]
backtrace:
```
#0  syscall () at ../ports/sysdeps/unix/sysv/linux/aarch64/syscall.S:38
#1  0x0000ffffbb2c7c18 in futex_wait (val=0, addr=<optimized out>) at ../../../libgomp/config/linux/futex.h:45
#2  do_wait (val=0, addr=<optimized out>) at ../../../libgomp/config/linux/wait.h:67
#3  gomp_team_barrier_wait_end (bar=<optimized out>, state=0) at ../../../libgomp/config/linux/bar.c:112
#4  0x0000ffffbb2c7d94 in gomp_team_barrier_wait_final (bar=<optimized out>) at ../../../libgomp/config/linux/bar.c:136
#5  0x0000ffffbb2c6344 in gomp_team_end () at ../../../libgomp/team.c:877
#6  0x00000000006db24c in test_ucp_rma_mt_put_get_Test::test_body (this=0x2c4dc2b0) at /home/XXXX/ucx.master/contrib/../test/gtest/ucp/test_ucp_rma_mt.cc:99
#7  0x000000000055e704 in run (this=0x2c4dc2b0) at /home/XXXX/ucx.master/contrib/../test/gtest/common/test.cc:276
#8  ucs::test_base::TestBodyProxy (this=0x2c4dc2b0) at /home/XXXX/ucx.master/contrib/../test/gtest/common/test.cc:302
#9  0x00000000005484bc in HandleSehExceptionsInMethodIfSupported<testing::Test, void> (location=0x8f8f50 "the test body", method=<optimized out>, object=0x2c4dc330)
    at /home/XXXX/ucx.master/contrib/../test/gtest/common/gtest-all.cc:3562
#10 testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=0x2c4dc330, method=<optimized out>, location=0x8f8f50 "the test body")
    at /home/XXXX/ucx.master/contrib/../test/gtest/common/gtest-all.cc:3598
#11 0x00000000005407ec in testing::Test::Run (this=0x2c4dc330) at /home/XXXX/ucx.master/contrib/../test/gtest/common/gtest-all.cc:3634
#12 0x0000000000540afc in Run (this=0x2c4dc330) at /home/XXXX/ucx.master/contrib/../test/gtest/common/gtest-all.cc:3626
#13 testing::TestInfo::Run (this=0x2c23b2a0) at /home/XXXX/ucx.master/contrib/../test/gtest/common/gtest-all.cc:3812
#14 0x0000000000540dac in Run (this=<optimized out>) at /home/XXXX/ucx.master/contrib/../test/gtest/common/gtest-all.cc:3940
#15 testing::TestCase::Run (this=0x2c23b390) at /home/XXXX/ucx.master/contrib/../test/gtest/common/gtest-all.cc:3930
#16 0x0000000000541b50 in Run (this=<optimized out>) at /home/XXXX/ucx.master/contrib/../test/gtest/common/gtest-all.cc:3916
#17 testing::internal::UnitTestImpl::RunAllTests (this=this@entry=0x2bf939a0) at /home/XXXX/ucx.master/contrib/../test/gtest/common/gtest-all.cc:5802
#18 0x0000000000541e14 in RunAllTests (this=0x2bf939a0) at /home/XXXX/ucx.master/contrib/../test/gtest/common/gtest-all.cc:5719
#19 HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (location=0x8f90b0 "auxiliary test code (environments or event listeners)", method=<optimized out>, 
    object=0x2bf939a0) at /home/XXXX/ucx.master/contrib/../test/gtest/common/gtest-all.cc:3562
#20 HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (location=0x8f90b0 "auxiliary test code (environments or event listeners)", 
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x541d58 <testing::internal::UnitTestImpl::RunAllTests()>, object=0x2bf939a0)
    at /home/XXXX/ucx.master/contrib/../test/gtest/common/gtest-all.cc:3598
#21 testing::UnitTest::Run (this=<optimized out>) at /home/XXXX/ucx.master/contrib/../test/gtest/common/gtest-all.cc:5413
#22 0x00000000004ec4c0 in RUN_ALL_TESTS () at /home/XXXX/ucx.master/contrib/../test/gtest/common/gtest.h:20059
#23 main (argc=<optimized out>, argv=0xfffff7275d38) at /home/XXXX/ucx.master/contrib/../test/gtest/common/main.cc:101
```

**Comment by shamisp** [comment]
The test is passing with MOFED ```MLNX_OFED_LINUX-4.6-1.0.1.1```

**Comment by shamisp** [comment]
@yosefe probably we should make it as a requirement somewhere

**Comment by yosefe** [comment]
it already is
https://github.com/openucx/ucx/blob/master/NEWS#L33
