### ISSUE TITLE
UCT: rkey unpack issue

### ISSUE THREAD

**Issue by tonycurtis** [openucx/ucx#3731]
Seen since b144885e9c59b26e382f7f8e7c766aea1b885ef3

(Note: I'm not using UCT directly, rather UCP.  UCT is what is throwing up the error.)

```shell
[1560949085.201521] [login2:14815:0]         uct_md.c:353  UCX  ERROR invalid component for rkey unpack; expected: rte_local_daemon, actual: self
[1560949085.201588] [login2:14815:0]       ucp_rkey.c:257  UCX  ERROR Failed to unpack remote key from remote md[2]: Invalid parameter

Program received signal SIGSEGV, Segmentation fault.
0x00002aaaac8ce1f5 in uct_rkey_release (component=0x0, rkey_ob=0x7db1d0)
    at ../../../ucx-git/src/uct/base/uct_md.c:372
372	    return component->rkey_release(component, rkey_ob->rkey, rkey_ob->handle);

(gdb) bt
#0  0x00002aaaac8ce1f5 in uct_rkey_release (component=0x0, rkey_ob=0x7db1d0)
    at ../../../ucx-git/src/uct/base/uct_md.c:372
#1  0x00002aaaabbe3698 in ucp_rkey_destroy (rkey=rkey@entry=0x7db170)
    at ../../../ucx-git/src/ucp/core/ucp_rkey.c:343
#2  0x00002aaaabbe444f in ucp_ep_rkey_unpack (ep=0x2aab3c325000,
    rkey_buffer=<optimized out>, rkey_p=0x7b4600)
    at ../../../ucx-git/src/ucp/core/ucp_rkey.c:270
#3  0x00002aaaaaf64f77 in shmemc_ucx_make_eps ()
   from /gpfs/home/arcurtis/opt/osss-ucx/pmix/git/ucx/git/lib/libshmemc-ucx.so.0
#4  0x00002aaaaaf62e0d in shmemc_init ()
   from /gpfs/home/arcurtis/opt/osss-ucx/pmix/git/ucx/git/lib/libshmemc-ucx.so.0
#5  0x00002aaaaacf506d in init_thread_helper ()
   from /gpfs/home/arcurtis/opt/osss-ucx/pmix/git/ucx/git/lib/libshmem.so.0
#6  0x00002aaaaacf51d2 in shmem_init ()
   from /gpfs/home/arcurtis/opt/osss-ucx/pmix/git/ucx/git/lib/libshmem.so.0
#7  0x000000000040093c in main () at hello.c:60

```

**Comment by tonycurtis** [comment]
Working again for me.  thnx.

**Comment by tonycurtis** [comment]
Still happening on standalone machine

```shell
1561392227.061916] [fedvm:61644:0]         uct_md.c:352  UCX  ERROR invalid component for rkey unpack; expected: , actual: self
[1561392227.061960] [fedvm:61644:0]       ucp_rkey.c:256  UCX  ERROR Failed to unpack remote key from remote md[2]: Invalid parameter

Thread 1 "a.out" received signal SIGSEGV, Segmentation fault.
372	../../../ucx-git/src/uct/base/uct_md.c: No such file or directory.
0x00007ffff78b2ea4 in uct_rkey_release (component=0x0, rkey_ob=0x497100)
    at ../../../ucx-git/src/uct/base/uct_md.c:372
(gdb) bt
#0  0x00007ffff78b2ea4 in uct_rkey_release (component=0x0, rkey_ob=0x497100)
    at ../../../ucx-git/src/uct/base/uct_md.c:372
#1  0x00007ffff7ca7cb0 in ucp_rkey_destroy (rkey=0x4970a0)
    at ../../../ucx-git/src/ucp/core/ucp_rkey.c:343
#2  0x00007ffff7ca7a15 in ucp_ep_rkey_unpack (ep=0x7ffff4196000, 
    rkey_buffer=<optimized out>, rkey_p=0x4966d0)
    at ../../../ucx-git/src/ucp/core/ucp_rkey.c:270
#3  0x00007ffff7f89799 in shmemc_ucx_make_eps (
    ch=0x7ffff7f96d60 <shmemc_default_context>)
    at ../../../osss-ucx-git/src/shmemc/ucx/eps.c:174
#4  0x00007ffff7f88a7a in shmemc_init ()
    at ../../../osss-ucx-git/src/shmemc/shmemc_init.c:36
#5  0x00007ffff7fb27dd in init_thread_helper (provided=0x0, requested=0)
    at ../../osss-ucx-git/src/init.c:118
#6  init_thread_helper (provided=0x0, requested=0)
    at ../../osss-ucx-git/src/init.c:81
#7  shmem_init () at ../../osss-ucx-git/src/init.c:182
#8  0x0000000000401195 in main () at hello.c:60
```

```shell
$ ucx_info -p -u r
#
# UCP context
#
#     component 0  :  posix
#     component 1  :  sysv
#     component 2  :  self
#     component 3  :  tcp
#     component 4  :  sockcm
#     component 5  :  ib
#     component 6  :  rdmacm
#     component 7  :  cma
#     component 8  :  knem
#     component 9  :  xpmem
#
#            md 0  :  component 0  posix 
#            md 1  :  component 1  sysv 
#            md 2  :  component 2  self 
#            md 3  :  component 3  tcp 
#            md 4  :  component 4  sockcm 
#            md 5  :  component 7  cma 
#            md 6  :  component 8  knem 
#            md 7  :  component 9  xpmem 
#
#      resource 0  :  md 0  dev 0  flags -- mm/posix
#      resource 1  :  md 1  dev 1  flags -- mm/sysv
#      resource 2  :  md 2  dev 2  flags -- self/self
#      resource 3  :  md 3  dev 3  flags -- tcp/ens33
#      resource 4  :  md 4  dev 4  flags -s sockcm/sockaddr
#      resource 5  :  md 5  dev 5  flags -- cma/cma
#      resource 6  :  md 6  dev 6  flags -- knem/knem
#      resource 7  :  md 7  dev 7  flags -- mm/xpmem
#
# memory: 1.48MB, file descriptors: 2
# create time: 4.762 ms
#
```

**Comment by yosefe** [comment]
@tonycurtis do you mean it happens with the latest version of https://github.com/openucx/ucx/pull/3763?

**Comment by tonycurtis** [comment]
It was working again after a regular git-pull on our cluster, but then I tested it on a standalone machine.  I'll try patching that with the PR.

**Comment by tonycurtis** [comment]
PR looks good for me.
