### ISSUE TITLE
Posix mm bugs

### ISSUE THREAD

**Issue by shamisp** [openucx/ucx#392]
1) Posix mm leaks file descriptors and memory.
```
-rw-rw-r--.  1 pasha pasha   2113632 Sep 11 18:10 ucx_shared_mr_uuid_2993235199799482679
-rw-rw-r--.  1 pasha pasha      8319 Sep 11 18:10 ucx_shared_mr_uuid_3354061294756630810
-rw-rw-r--.  1 pasha pasha 258078721 Sep 11 18:10 ucx_shared_mr_uuid_5272271466218107439
-rw-rw-r--.  1 pasha pasha 258078723 Sep 11 18:10 ucx_shared_mr_uuid_6719757301157159119
-rw-rw-r--.  1 pasha pasha   2113632 Sep 11 18:10 ucx_shared_mr_uuid_672568375605478219
-rw-rw-r--.  1 pasha pasha      8319 Sep 11 18:10 ucx_shared_mr_uuid_771297532477256058
```

it is easy to reproduce on system with shared memory limits. Eventually you get segfault because you can't access memory. I was able to reproduce the problem on Fedora 22, default configuration, regular user. (it works with root)

2) ftruncate in src/uct/sm/mm/mm_posix.c  does not consider the "header" that is allocated for tracer
```
if (ftruncate(shm_fd, *length_p) == -1) {                                   
        ucs_error("Error returned from ftruncate %m");                          
        status = UCS_ERR_SHMEM_SEGMENT;                                         
        goto err_shm_unlink;                                                    
    }                                          
```

(see in ucs_mmap how to fix it)

**Comment by yosefe** [comment]
Thanks Pasha.
@alinask pls handle
By "tracer" - i guess you mean memtrack

**Comment by shamisp** [comment]
tracer - yes memtrack. You allocate one struct in the beginning of the memory but ftruncate prepare file space for it.

**Comment by shamisp** [comment]
I still observe segfaults in the code:
```
#0  0x00007f0a88593fdb in waitpid () from /lib64/libpthread.so.0
#1  0x00007f0a8923adca in ucs_debugger_attach () at /home/pasha/work/ucx_shamisp/contrib/../src/ucs/debug/debug.c:537
#2  0x00007f0a8923b2e7 in ucs_error_freeze () at /home/pasha/work/ucx_shamisp/contrib/../src/ucs/debug/debug.c:582
#3  ucs_handle_error () at /home/pasha/work/ucx_shamisp/contrib/../src/ucs/debug/debug.c:623
#4  0x00007f0a8923b6b4 in ucs_error_signal_handler (signo=7) at /home/pasha/work/ucx_shamisp/contrib/../src/ucs/debug/debug.c:605
#5  <signal handler called>
#6  pattern_fill (seed=2459565876494606882, this=0x7ffc4c172df0) at /home/pasha/work/ucx_shamisp/contrib/../test/gtest/uct/uct_test.cc:359
#7  uct_test::mapped_buffer::mapped_buffer (this=0x7ffc4c172df0, size=258078720, seed=2459565876494606882, entity=..., offset=3)
    at /home/pasha/work/ucx_shamisp/contrib/../test/gtest/uct/uct_test.cc:335
#8  0x0000000000464799 in uct_p2p_rma_test::test_xfer (this=0xda7020, send=
    (ucs_status_t (uct_p2p_test::*)(uct_p2p_test * const, uct_ep_h, const uct_test::mapped_buffer &, const uct_test::mapped_buffer &)) 0x45f9f0 <uct_p2p_rma_test::put_short(uct_ep*, uct_test::mapped_buffer const&, uct_test::mapped_buffer const&)>, length=258078720, direction=uct_p2p_test::DIRECTION_SEND_TO_RECV)
    at /home/pasha/work/ucx_shamisp/contrib/../test/gtest/uct/test_p2p_rma.cc:62
#9  0x0000000000479db7 in uct_p2p_test::test_xfer_print<ucs::detail::message_stream> (this=this@entry=0xda7020, os=..., send=
    (ucs_status_t (uct_p2p_test::*)(uct_p2p_test * const, uct_ep_h, const uct_test::mapped_buffer &, const uct_test::mapped_buffer &)) 0x45f9f0 <uct_p2p_rma_test::put_short(uct_ep*, uct_test::mapped_buffer const&, uct_test::mapped_buffer const&)>, length=length@entry=258078720, direction=direction@entry=uct_p2p_test::DIRECTION_SEND_TO_RECV)
    at /home/pasha/work/ucx_shamisp/contrib/../test/gtest/uct/uct_p2p_test.cc:138
#10 0x0000000000476572 in uct_p2p_test::test_xfer_multi (this=this@entry=0xda7020, send=
    (ucs_status_t (uct_p2p_test::*)(uct_p2p_test * const, uct_ep_h, const uct_test::mapped_buffer &, const uct_test::mapped_buffer &)) 0x45f9f0 <uct_p2p_rma_test::put_short(uct_ep*, uct_test::mapped_buffer const&, uct_test::mapped_buffer const&)>, min_length=min_length@entry=0, max_length=258078720, 
    direction=direction@entry=uct_p2p_test::DIRECTION_SEND_TO_RECV) at /home/pasha/work/ucx_shamisp/contrib/../test/gtest/uct/uct_p2p_test.cc:169
#11 0x000000000045e6c5 in uct_p2p_rma_test_put_short_Test::test_body (this=0xda7020) at /home/pasha/work/ucx_shamisp/contrib/../test/gtest/uct/test_p2p_rma.cc:81
#12 0x00007f0a88bfab4a in ucs::test_base::TestBodyProxy (this=0xda7038) at /home/pasha/work/ucx_shamisp/contrib/../src/ucs/gtest/test.cc:118
#13 0x00007f0a887e1723 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
   from /lib64/libgtest.so.0
#14 0x00007f0a887d621a in testing::Test::Run() () from /lib64/libgtest.so.0
#15 0x00007f0a887d6368 in testing::TestInfo::Run() () from /lib64/libgtest.so.0
#16 0x00007f0a887d6445 in testing::TestCase::Run() () from /lib64/libgtest.so.0
#17 0x00007f0a887d6750 in testing::internal::UnitTestImpl::RunAllTests() () from /lib64/libgtest.so.0
#18 0x00007f0a887e1c93 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) () from /lib64/libgtest.so.0
#19 0x00007f0a887d6a13 in testing::UnitTest::Run() () from /lib64/libgtest.so.0
#20 0x00007f0a88bf9b3c in RUN_ALL_TESTS () at /usr/include/gtest/gtest.h:2288
#21 main (argc=1, argv=<optimized out>) at /home/pasha/work/ucx_shamisp/contrib/../src/ucs/gtest/main.cc:40
#22 0x00007f0a87537700 in __libc_start_main () from /lib64/libc.so.6
#23 0x0000000000418299 in _start ()

```

**Comment by shamisp** [comment]
Also the /dev/shm/ is not clean. It seems like #393 does fix this issue.

**Comment by alinask** [comment]
@shamisp 
1. https://github.com/openucx/ucx/pull/393 should fix the creation of non unique files. because if the files are not unique, the tests fail on "File exists." 
2. the second issue you mentioned, with the memtrack, should be fixed once https://github.com/openucx/ucx/issues/394 is fixed.
3. the error you sent - of not being able to access memory is because /dev/shm becomes full. the quick solution is to clean this directory. i'm working on a permanent fix for this case.
