### ISSUE TITLE
[SparkUCX] Arbiter assertion when submitting requests from ep_flush callback

### ISSUE THREAD

**Issue by petro-rudenko** [openucx/ucx#4267]
Here's pseudocode what happens at the heart of [SparkUCX](https://github.com/openucx/sparkucx/pull/6/files#diff-fae1b3825d9911fcacb67248ff4093a3R114-R170):
```
void submit_n_nb_requests(endpoint ep) {
   for (i = 0; i < n; i++) {
       ucp_get_nbi(ep, ...);
   }
}

for (Endpoint ep: all_endpoints) { // fails when # of enpoints > 25
    submit_n_nb_requests(ep); // Submit n get requests
    ucp_ep_flush_nb({
        submit_n_nb_requests(ep); //Submit another one n requests -- fails here
        ucp_ep_flush_nb(do_something_else);
    });
}

}
```

When a number of nodes > 23-25 it starts to fail with a next exception:
```
[clx-hercules-063:6190 :0:6349]     arbiter.c:213  Assertion `(arbiter)->guard == 0' failed: scheduling group from the arbiter callback
[clx-hercules-063:6190 :1:6346]     arbiter.c:213  Assertion `(arbiter)->guard == 0' failed: scheduling group from the arbiter callback

/hpc/scrap/users/swat/jenkins/ucx/contrib/../src/ucs/datastruct/arbiter.c: [ ucs_arbiter_group_schedule_nonempty() ]
      ...
      210     ucs_arbiter_elem_t *current, *head;
      211
      212     UCS_ARBITER_GUARD_CHECK(arbiter);
==>   213
      214     ucs_assert(tail != NULL);
      215     head = tail->next;
      216


/hpc/scrap/users/swat/jenkins/ucx/contrib/../src/ucs/datastruct/arbiter.c: [ ucs_arbiter_group_schedule_nonempty() ]
      ...
      210     ucs_arbiter_elem_t *current, *head;
      211
      212     UCS_ARBITER_GUARD_CHECK(arbiter);
==>   213
      214     ucs_assert(tail != NULL);
      215     head = tail->next;
      216

==== backtrace (tid:   6349) ====
 0 0x000000000004d4d4 ucs_arbiter_group_schedule_nonempty()  /hpc/scrap/users/swat/jenkins/ucx/contrib/../src/ucs/datastruct/arbiter.c:213
 1 0x0000000000023293 ucs_arbiter_group_schedule()  /hpc/scrap/users/swat/jenkins/ucx/contrib/../src/ucs/datastruct/arbiter.h:261
 2 0x0000000000022342 uct_ep_pending_add()  /hpc/scrap/users/swat/jenkins/ucx/contrib/../src/uct/api/uct.h:2570
 3 0x000000000003362d ucp_request_try_send()  /hpc/scrap/users/swat/jenkins/ucx/contrib/../src/ucp/core/ucp_request.inl:188
 4 0x000000000003362d ucp_rma_nonblocking()  /hpc/scrap/users/swat/jenkins/ucx/contrib/../src/ucp/rma/rma_send.c:172
 5 0x000000000003362d ucp_get_nbi()  /hpc/scrap/users/swat/jenkins/ucx/contrib/../src/ucp/rma/rma_send.c:291
 6 0x00000000000040dc Java_org_openucx_jucx_ucp_UcpEndpoint_getNonBlockingImplicitNative()  ???:0
```

**Comment by yosefe** [comment]
seems like a bug in UCP flush implementation that progress callback calls user callback instead of scheduling it as a deferred callback on the progress queue

**Comment by yosefe** [comment]
@petro-rudenko can u pls add all stack frames from gdb?

**Comment by petro-rudenko** [comment]
Still reproduces from master:
```
#1  0x00007fdb76bc99e5 in ucs_debug_freeze () at /hpc/scrap/users/peterr/ucx/contrib/../src/ucs/debug/debug.c:792
#2  0x00007fdb76bcce75 in ucs_error_freeze (message=0x7fdb7c0bd570 "Assertion `(group)->guard == 0' failed: scheduling arbiter group 0
x7fda5869a8d0 while it's being dispatched") at /hpc/scrap/users/peterr/ucx/contrib/../src/ucs/debug/debug.c:911
#3  ucs_handle_error (message=message@entry=0x7fdb7c0bd570 "Assertion `(group)->guard == 0' failed: scheduling arbiter group 0x7fda586
9a8d0 while it's being dispatched") at /hpc/scrap/users/peterr/ucx/contrib/../src/ucs/debug/debug.c:1074
#4  0x00007fdb76bc93c8 in ucs_fatal_error_message (file=file@entry=0x7fdb76c8ec38 "/hpc/scrap/users/peterr/ucx/contrib/../src/ucs/data
struct/arbiter.c", line=line@entry=40, function=function@entry=0x7fdb76c8ee80 <__FUNCTION__.3726> "ucs_arbiter_group_push_elem_always"
, message_buf=message_buf@entry=0x7fdb7c0bd570 "Assertion `(group)->guard == 0' failed: scheduling arbiter group 0x7fda5869a8d0 while
it's being dispatched") at /hpc/scrap/users/peterr/ucx/contrib/../src/ucs/debug/assert.c:33
#5  0x00007fdb76bc9556 in ucs_fatal_error_format (file=file@entry=0x7fdb76c8ec38 "/hpc/scrap/users/peterr/ucx/contrib/../src/ucs/datas
truct/arbiter.c", line=line@entry=40, function=function@entry=0x7fdb76c8ee80 <__FUNCTION__.3726> "ucs_arbiter_group_push_elem_always",
 format=format@entry=0x7fdb76c8ec80 "Assertion `%s' failed: scheduling arbiter group %p while it's being dispatched") at /hpc/scrap/us
ers/peterr/ucx/contrib/../src/ucs/debug/assert.c:49
#6  0x00007fdb76bc016b in ucs_arbiter_group_push_elem_always (group=group@entry=0x7fda5869a8d0, elem=<optimized out>) at /hpc/scrap/us
ers/peterr/ucx/contrib/../src/ucs/datastruct/arbiter.c:40
#7  0x00007fdb75ca6418 in ucs_arbiter_group_push_elem (elem=<optimized out>, group=0x7fda5869a8d0) at /hpc/scrap/users/peterr/ucx/cont
rib/../src/ucs/datastruct/arbiter.h:361
#8  uct_rc_ep_pending_add (tl_ep=0x7fda5869a890, n=<optimized out>, flags=<optimized out>) at /hpc/scrap/users/peterr/ucx/contrib/../s
rc/uct/ib/rc/base/rc_ep.c:228
#9  0x00007fdb7626d4fe in uct_ep_pending_add (flags=0, req=0x7fda5acc6168, ep=0x7fda5869a890) at /hpc/scrap/users/peterr/ucx/contrib/.
./src/uct/api/uct.h:2606
#10 ucp_request_pending_add (req=req@entry=0x7fda5acc60c0, req_status=req_status@entry=0x7fdb7c0bdbb0, pending_flags=pending_flags@ent
ry=0) at /hpc/scrap/users/peterr/ucx/contrib/../src/ucp/core/ucp_request.c:172
#11 0x00007fdb7627f83d in ucp_request_try_send (pending_flags=0, req_status=0x7fdb7c0bdbb0, req=<optimized out>) at /hpc/scrap/users/p
eterr/ucx/contrib/../src/ucp/core/ucp_request.inl:188
#12 ucp_request_send (pending_flags=0, req=<optimized out>) at /hpc/scrap/users/peterr/ucx/contrib/../src/ucp/core/ucp_request.inl:206
#13 ucp_rma_nonblocking (zcopy_thresh=1094, progress_cb=0x7fdb7627c630 <ucp_rma_basic_progress_get>, rkey=<optimized out>, remote_addr
=140577937956430, length=<optimized out>, buffer=<optimized out>, ep=<optimized out>) at /hpc/scrap/users/peterr/ucx/contrib/../src/uc
p/rma/rma_send.c:172
#14 ucp_get_nbi (ep=0x7fd9562b1310, buffer=<optimized out>, length=<optimized out>, remote_addr=140577937956430, rkey=<optimized out>)
 at /hpc/scrap/users/peterr/ucx/contrib/../src/ucp/rma/rma_send.c:291
#15 0x00007fdb77125743 in Java_org_openucx_jucx_ucp_UcpEndpoint_getNonBlockingImplicitNative () from /scrap/users/peterr/hadoop_tmp/nm
-local-dir/usercache/peterr/appcache/application_1584874259017_0007/container_1584874259017_0007_01_000018/tmp/jucx895032571663107413/
libjucx.so
```

```
4597 /hpc/scrap/users/peterr/ucx/contrib/../src/ucs/datastruct/arbiter.c: [ ucs_arbiter_group_push_elem_always() ]
4598       ...
4599        37     ucs_arbiter_elem_t *tail = group->tail;
4600        38
4601        39     UCS_ARBITER_GROUP_GUARD_CHECK(group);
4602 ==>    40
4603        41     if (tail == NULL) {
4604        42         ucs_arbiter_group_head_reset(elem);
4605        43         elem->next = elem;        /* Connect to itself */
4606
4607 20/03/22 13:22:46 INFO reducer.ReducerCallback: Endpoint 140579006079536 fetched 369 blocks of total size 2.6 MB in 201ms
4608
4609 /hpc/scrap/users/peterr/ucx/contrib/../src/ucs/datastruct/arbiter.c: [ ucs_arbiter_group_push_elem_always() ]
4610       ...
4611        37     ucs_arbiter_elem_t *tail = group->tail;
4612        38
4613        39     UCS_ARBITER_GROUP_GUARD_CHECK(group);
4614 ==>    40
4615        41     if (tail == NULL) {
4616        42         ucs_arbiter_group_head_reset(elem);
4617        43         elem->next = elem;        /* Connect to itself */
4618
4619 ==== backtrace (tid:  13777) ====
4620  0 0x0000000000058888 ucs_debug_print_backtrace()  /hpc/scrap/users/peterr/ucx/contrib/../src/ucs/debug/debug.c:628
4621  1 0x000000000004e16b ucs_arbiter_group_push_elem_always()  /hpc/scrap/users/peterr/ucx/contrib/../src/ucs/datastruct/arbiter.c:4     0
4622  2 0x0000000000026418 ucs_arbiter_group_push_elem()  /hpc/scrap/users/peterr/ucx/contrib/../src/ucs/datastruct/arbiter.h:361
4623  3 0x00000000000264fe uct_ep_pending_add()  /hpc/scrap/users/peterr/ucx/contrib/../src/uct/api/uct.h:2606
4624  4 0x000000000003883d ucp_request_try_send()  /hpc/scrap/users/peterr/ucx/contrib/../src/ucp/core/ucp_request.inl:188
4625  5 0x000000000003883d ucp_rma_nonblocking()  /hpc/scrap/users/peterr/ucx/contrib/../src/ucp/rma/rma_send.c:172
4626  6 0x000000000003883d ucp_get_nbi()  /hpc/scrap/users/peterr/ucx/contrib/../src/ucp/rma/rma_send.c:291
4627  7 0x0000000000004743 Java_org_openucx_jucx_ucp_UcpEndpoint_getNonBlockingImplicitNative()  ???:0
4628 =================================
4629 [clx-hercules-054:13573:1:13777] Process frozen...```

**Comment by yosefe** [comment]
thanks @petro-rudenko , i'll work on additional fix

**Comment by yosefe** [comment]
@petro-rudenko can you pls test with https://github.com/yosefe/ucx/tree/topic/arbiter-sched-self ?

**Comment by petro-rudenko** [comment]
@yosefe  it works!

**Comment by yosefe** [comment]
> @yosefe it works!

Thanks! i'll start pushing it to UCX master..
