### ISSUE TITLE
segfault in ucx_perftest + cuda memory

### ISSUE THREAD

**Issue by angainor** [openucx/ucx#4272]
I compiled 1.6.1 with GCC/7.3.0-2.30 and CUDA/9.2.88. When I try to run the `ucx_perftest` on our InfiniBand cluster with `-m cuda` or `-m cuda-managed`, I see the following segfault:

```
./ucx_perftest -t ucp_put_bw -s 1 -n 5000000 c7-1 -m cuda

[c7-1:35806:0:35806] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x8)

/cluster/home/marcink/src/ucx-1.6.1/src/ucp/core/ucp_rkey.c: [ ucp_rkey_pack() ]
      ...
      114     UCP_THREAD_CS_ENTER(&context->mt_lock);
      115 
      116     ucs_trace("packing rkeys for buffer %p memh %p md_map 0x%lx",
==>   117               memh->address, memh, memh->md_map);
      118 
      119     if (memh->length == 0) {
      120         /* dummy memh, return dummy key */

==== backtrace (tid:  35806) ====
 0 0x000000000001b2fe ucp_rkey_pack()  /cluster/home/marcink/src/ucx-1.6.1/src/ucp/core/ucp_rkey.c:117
 1 0x000000000040981f ucp_perf_test_setup_endpoints()  /cluster/home/marcink/src/ucx-1.6.1/src/tools/perf/lib/libperf.c:1084
 2 0x000000000040981f ucp_perf_setup()  /cluster/home/marcink/src/ucx-1.6.1/src/tools/perf/lib/libperf.c:1406
 3 0x0000000000409c56 ucx_perf_run()  /cluster/home/marcink/src/ucx-1.6.1/src/tools/perf/lib/libperf.c:1488
 4 0x0000000000405a37 run_test_recurs()  /cluster/home/marcink/src/ucx-1.6.1/src/tools/perf/perftest.c:1430
 5 0x0000000000403d06 run_test()  /cluster/home/marcink/src/ucx-1.6.1/src/tools/perf/perftest.c:1479
 6 0x0000000000403d06 main()  /cluster/home/marcink/src/ucx-1.6.1/src/tools/perf/perftest.c:1537
 7 0x0000000000022495 __libc_start_main()  ???:0
 8 0x00000000004042da _start()  ???:0
=================================
Segmentation fault (core dumped)
```
Similar segfault is seen with the UCX shipped with HPCX 2.4. Here is the backtrace from that one:
```
#0  ucp_rkey_pack (context=0xabbd90, memh=0x0, rkey_buffer_p=rkey_buffer_p@entry=0x7ffc1b685820, size_p=size_p@entry=0x7ffc1b685858)
    at core/ucp_rkey.c:120
#1  0x0000000000406454 in ucp_perf_test_setup_endpoints (features=<optimized out>, perf=0xa69e10) at libperf.c:1084
#2  ucp_perf_setup (perf=0xa69e10) at libperf.c:1406
#3  0x00000000004092eb in ucx_perf_run (params=params@entry=0x7ffc1b685c80, result=result@entry=0x7ffc1b685ad0) at libperf.c:1488
#4  0x0000000000405473 in run_test_recurs (ctx=ctx@entry=0x7ffc1b685c80, parent_params=parent_params@entry=0x7ffc1b685c80, 
    depth=depth@entry=0) at perftest.c:1400
#5  0x0000000000403a07 in run_test (ctx=0x7ffc1b685c80) at perftest.c:1437
#6  main (argc=<optimized out>, argv=<optimized out>) at perftest.c:1495

```

The same test runs fine with `-m host`. Do I need anything special to run with `-m cuda`, or is this a bug? 

Thanks!

**Comment by hoopoepg** [comment]
hi

it seems this is bug in libperf module, will fix

thank you for help

**Comment by angainor** [comment]
@hoopoepg Great, thanks! Please let me know when you commit a fix, I'd like to test this here..

**Comment by lytofd** [comment]
l hava met the same error,waiting for response ~
