### ISSUE TITLE
MPI application that uses XPMEM catches "Bus error: nonexistent physical address"

### ISSUE THREAD

**Issue by dmitrygx** [openucx/ucx#4710]
When using MPI application with `UCX_TLS=sm` (and XPMEM is available for RNDV):
```
# UCP endpoint
#
#               peer: hali001:51817
#                 lane[0]:  0:posix/memory md[0] <proxy>  -> md[0]/posix    am am_bw#0
#                 lane[1]:  6:xpmem/memory md[6]          -> md[6]/xpmem    rma_bw#1
#                 lane[2]:  5:knem/memory md[5]           -> md[5]/knem     rma_bw#0
#
#                tag_send: 0..<egr/short>..93..<egr/bcopy>..8256..<rndv>..(inf)
#            tag_send_nbr: 0..<egr/short>..93..<egr/bcopy>..262144..<rndv>..(inf)
#           tag_send_sync: 0..<egr/short>..93..<egr/bcopy>..8256..<rndv>..(inf)
#
#                  rma_bw: mds [5] [6] rndv_rkey_size 83
```
it fails with the following backtrace:
```
[hali001:51586:0:51586] Caught signal 7 (Bus error: nonexistent physical address)
==== backtrace (tid:  51586) ====
 0  /root/ucx/install/lib/libucs.so.0(ucs_handle_error+0x78) [0xffff9117b368]
 1  /root/ucx/install/lib/libucs.so.0(+0x2b184) [0xffff9117b184]
 2  /root/ucx/install/lib/libucs.so.0(+0x2b240) [0xffff9117b240]
 3  [0xffff93f6066c]
 4  /lib64/libc.so.6(+0x88e90) [0xffff939f8e90]
 5  /lib64/libc.so.6(memcpy+0xc0) [0xffff939f8d98]
 6  /root/ucx/install/lib/libucp.so.0(+0x77924) [0xffff912a7924]
 7  /root/ucx/install/lib/libucp.so.0(+0x7dd78) [0xffff912add78]
 8  /root/ucx/install/lib/libucp.so.0(ucp_rndv_matched+0x5f0) [0xffff912ae9fc]
 9  /root/ucx/install/lib/libucp.so.0(ucp_rndv_process_rts+0x3b8) [0xffff912af0a0]
10  /root/ucx/install/lib/libucp.so.0(ucp_rndv_rts_handler+0x94) [0xffff912af630]
11  /root/ucx/install/lib/libuct.so.0(+0x16ba0) [0xffff911e6ba0]
12  /root/ucx/install/lib/libuct.so.0(+0x172d8) [0xffff911e72d8]
13  /root/ucx/install/lib/libuct.so.0(+0x17714) [0xffff911e7714]
14  /root/ucx/install/lib/libuct.so.0(uct_mm_iface_progress+0x1c) [0xffff911e7878]
15  /root/ucx/install/lib/libucp.so.0(+0x324b4) [0xffff912624b4]
16  /root/ucx/install/lib/libucp.so.0(ucp_worker_progress+0x158) [0xffff91268e3c]
17  /root/hpcx-v2.5.0-gcc-MLNX_OFED_LINUX-4.6-1.0.1.1-redhat7.5-aarch64/ompi/lib/openmpi/mca_pml_ucx.so(mca_pml_ucx_recv+0xe8) [0xffff91383af4]
18  /root/hpcx-v2.5.0-gcc-MLNX_OFED_LINUX-4.6-1.0.1.1-redhat7.5-aarch64/ompi/lib/libmpi.so.40(MPI_Recv+0x3c) [0xffff93dee540]
19  /root/hpcx-v2.5.0-gcc-MLNX_OFED_LINUX-4.6-1.0.1.1-redhat7.5-aarch64/ompi/lib/libmpi_mpifh.so.40(pmpi_recv_+0x8c) [0xffff93eeaf94]
20  ./home/cfl3d/CFL3D/build/cfl/mpi/cfl3d_mpi() [0x76f16c]
21  ./home/cfl3d/CFL3D/build/cfl/mpi/cfl3d_mpi() [0x6d9920]
22  ./home/cfl3d/CFL3D/build/cfl/mpi/cfl3d_mpi() [0x6e1f8c]
23  ./home/cfl3d/CFL3D/build/cfl/mpi/cfl3d_mpi() [0x56bc8c]
24  ./home/cfl3d/CFL3D/build/cfl/mpi/cfl3d_mpi() [0x6c3c94]
25  ./home/cfl3d/CFL3D/build/cfl/mpi/cfl3d_mpi() [0x402aac]
26  /lib64/libc.so.6(__libc_start_main+0xf0) [0xffff939915d4]
27  ./home/cfl3d/CFL3D/build/cfl/mpi/cfl3d_mpi() [0x402adc]
=================================
```

It works fine w/o XPMEM (i.e. `UCX_TLS=posix`/`UCX_TLS=posix,cma,knem`)

**Comment by dmitrygx** [comment]
```
#0  0x0000ffff8e8b0108 in pause () from /lib64/libpthread.so.0
#1  0x0000ffff8c02a8dc in ucs_debug_freeze () at debug/debug.c:789
#2  0x0000ffff8c02ad08 in ucs_error_freeze (message=0xffff8c04c220 "nonexistent physical address") at debug/debug.c:908
#3  0x0000ffff8c02b3dc in ucs_handle_error (message=0xffff8c04c220 "nonexistent physical address") at debug/debug.c:1071
#4  0x0000ffff8c02b1d4 in ucs_debug_handle_error_signal (signo=7, cause=0xffff8c04c220 "nonexistent physical address", fmt=0xffff8c04c370 "") at debug/debug.c:1020
#5  0x0000ffff8c02b290 in ucs_error_signal_handler (signo=7, info=0xffff87e437a0, context=0xffff87e43820) at debug/debug.c:1036
#6  <signal handler called>
#7  0x0000ffff8e798e64 in _wordcopy_fwd_aligned () from /lib64/libc.so.6
#8  0x0000ffff8e798d98 in memcpy () from /lib64/libc.so.6
#9  0x0000ffff87f57b18 in ucs_memcpy_relaxed (dst=0xffff5a7d1268, src=0xfffedf0edf28, len=23120) at /root/ucx/src/ucs/arch/aarch64/cpu.h:203
#10 0x0000ffff87f5df8c in ucp_request_unpack_contig (length=23120, data=0xfffedf0edf28, buf=0xffff5a7d1268, req=0x2b2097c0) at /root/ucx/src/ucp/core/ucp_request.inl:409
#11 ucp_request_recv_data_unpack (last=1, offset=0, length=23120, data=0xfffedf0edf28, req=0x2b2097c0) at /root/ucx/src/ucp/core/ucp_request.inl:445
#12 ucp_rndv_do_rkey_ptr (rndv_req=0x2b2cb880, rreq=0x2b2097c0, rndv_rts_hdr=0xffff87ed0fdc) at tag/rndv.c:729
#13 0x0000ffff87f5ec10 in ucp_rndv_matched_inner (rndv_rts_hdr=0xffff87ed0fdc, rreq=0x2b2097c0, worker=0x2a0405e0) at tag/rndv.c:788
#14 ucp_rndv_matched (worker=0x2a0405e0, rreq=0x2b2097c0, rndv_rts_hdr=0xffff87ed0fdc) at tag/rndv.c:738
#15 0x0000ffff87f5f2b4 in ucp_rndv_process_rts (arg=0x2a0405e0, data=0xffff87ed0fdc, length=90, tl_flags=0) at tag/rndv.c:840
#16 0x0000ffff87f5f844 in ucp_rndv_rts_handler_inner (tl_flags=0, length=90, data=0xffff87ed0fdc, arg=0x2a0405e0) at tag/rndv.c:864
#17 ucp_rndv_rts_handler (arg=0x2a0405e0, data=0xffff87ed0fdc, length=90, tl_flags=0) at tag/rndv.c:860
#18 0x0000ffff8c097060 in uct_iface_invoke_am (iface=0x2a04d590, id=9 '\t', data=0xffff87ed0fdc, length=90, flags=0) at /root/ucx/src/uct/base/uct_iface.h:628
#19 0x0000ffff8c097798 in uct_mm_iface_invoke_am (flags=0, length=90, data=0xffff87ed0fdc, am_id=9 '\t', iface=0x2a04d590) at sm/mm/base/mm_iface.h:211
#20 uct_mm_iface_process_recv (iface=0x2a04d590, elem=0xffff87ed0fc0) at sm/mm/base/mm_iface.c:225
#21 0x0000ffff8c097bd4 in uct_mm_iface_poll_fifo (iface=0x2a04d590) at sm/mm/base/mm_iface.c:270
#22 0x0000ffff8c097d38 in uct_mm_iface_progress (arg=0x2a04d590) at sm/mm/base/mm_iface.c:294
#23 0x0000ffff87f1224c in ucs_callbackq_dispatch (cbq=0x2a042f30) at /root/ucx/src/ucs/datastruct/callbackq.h:211
#24 0x0000ffff87f18bdc in uct_worker_progress (worker=0x2a042f30) at /root/ucx/src/uct/api/uct.h:2217
#25 ucp_worker_progress (worker=0x2a0405e0) at core/ucp_worker.c:1949
#26 0x0000ffff8c1238c4 in mca_pml_ucx_progress () at pml_ucx.c:515
#27 0x0000ffff8e55619c in opal_progress () at runtime/opal_progress.c:231
#28 0x0000ffff8eb6c020 in sync_wait_st (sync=<optimized out>) at ../opal/threads/wait_sync.h:83
#29 ompi_request_default_wait_some (count=12620, requests=0x2ba2a140, outcount=0xfffff638c890, indices=0xffff7ae310a0, statuses=0x2ba42ba0) at request/req_wait.c:442
#30 0x0000ffff8eb94674 in PMPI_Waitsome (incount=12620, requests=requests@entry=0x2ba2a140, outcount=outcount@entry=0xfffff638c890, indices=indices@entry=0xffff7ae310a0, statuses=statuses@entry=0x2ba42ba0) at pwaitsome.c:85
#31 0x0000ffff8ec8dba8 in ompi_waitsome_f (incount=0xfffff638c780, array_of_requests=0xffff7adaa7f8, outcount=0xfffff638c890, array_of_indices=0xffff7ae310a0, array_of_statuses=0xffff84ac0010, ierr=0xfffff638c760) at pwaitsome_f.c:110
#32 0x00000000004afc30 in bc_blkint_ ()
#33 0x00000000006d07e0 in mgblk_ ()
#34 0x00000000006e1f8c in mgbl_ ()
#35 0x000000000056bc8c in cfl3d_ ()
#36 0x00000000006c3c94 in MAIN__ ()
#37 0x0000000000402aac in main ()
```

**Comment by dmitrygx** [comment]
```
[ RUN      ] shm_ib/test_ucp_atomic32.atomic_add/0 <shm,ib>
[New Thread 0xffffbdb8f160 (LWP 10806)]
[New Thread 0xffffba76f160 (LWP 10809)]

Program received signal SIGBUS, Bus error.
0x0000ffffbe6e4b78 in ucs_atomic_add32 (ptr=0xffffb1680000, value=984801581) at /root/ucx/src/ucs/arch/atomic.h:75
75      UCS_DEFINE_ATOMIC_ADD(32, l);
Missing separate debuginfos, use: debuginfo-install glibc-2.17-260.el7.aarch64 libgcc-4.8.5-28.el7.aarch64 libgomp-4.8.5-28.el7.aarch64 libibcm-41mlnx1-OFED.4.1.0.1.0.46101.aarch64 libibverbs-41mlnx1-OFED.4.6.0.4.1.46101.aarch64 libmlx5-41mlnx1-OFED.4.6.0.0.4.46101.aarch64 libnl3-3.2.28-4.el7.aarch64 librdmacm-41mlnx1-OFED.4.6.0.0.1.46101.aarch64 libstdc++-4.8.5-28.el7.aarch64 numactl-libs-2.0.9-7.el7.aarch64
(gdb) bt
#0  0x0000ffffbe6e4b78 in ucs_atomic_add32 (ptr=0xffffb1680000, value=984801581) at /root/ucx/src/ucs/arch/atomic.h:75
#1  0x0000ffffbe6e5380 in uct_sm_ep_atomic32_post (ep=0x1901230, opcode=0, value=984801581, remote_addr=281473660289024, rkey=18446744073707388928) at sm/base/sm_ep.c:67
#2  0x0000ffffbe5ad210 in uct_ep_atomic32_post (rkey=18446744073707388928, remote_addr=281473660289024, value=984801581, opcode=UCT_ATOMIC_OP_ADD, ep=0x1901230) at /root/ucx/src/uct/api/uct.h:2516
#3  ucp_amo_basic_progress_post (self=0x190b0a8) at rma/amo_basic.c:48
#4  0x0000ffffbe5b02b4 in ucp_request_try_send (pending_flags=0, req_status=0xffffffffd407, req=0x190b000) at /root/ucx/src/ucp/core/ucp_request.inl:171
#5  ucp_request_send (pending_flags=0, req=0x190b000) at /root/ucx/src/ucp/core/ucp_request.inl:206
#6  ucp_rma_send_request_cb (cb=0x509b90 <ucs_empty_function@plt>, req=0x190b000) at rma/rma.inl:20
#7  ucp_atomic_post (ep=0xffffb1ac0000, opcode=UCP_ATOMIC_POST_OP_ADD, value=984801581, op_size=4, remote_addr=281473660289024, rkey=0x1901bc0) at rma/amo_send.c:188
#8  0x0000ffffbe5b0a7c in ucp_atomic_add32_inner (rkey=0x1901bc0, remote_addr=281473660289024, add=984801581, ep=0xffffb1ac0000) at rma/amo_send.c:216
#9  ucp_atomic_add32 (ep=0xffffb1ac0000, add=984801581, remote_addr=281473660289024, rkey=0x1901bc0) at rma/amo_send.c:213
#10 0x00000000006c241c in test_ucp_atomic::blocking_add<unsigned int> (this=0x141ffd0, e=0xee60a0, max_size=3072, memheap_addr=0xffffb1890000, rkey=0x1901bc0,
    expected_data=";\325\022_\000\000\000\000_T\274\266\003\000\000\000\307K[#%\000\000\000\327\365\220as\001\000\000w\232\251ρ\016\000\000\267\b\240\034\022\221\000\000\067W@\036\265\252\005\000\067h\203.\023\253\070\000\067\022\"ѿ\256\066\002\067\266T+~\323\"\026\067\036O\261\355B\\\335\067.\027\355H\235\232\245\067\316\347B\331$\nx7\016\016\235|pe\260\067\216\214\"\336d\366\343\067\216}Y\255\360\237\347\067\216\347~\305f?\f7\216\v\365\266\003zz7\216s\222%%\304\310\067\216\203\270ws\251\327\067\216#5\255\202\236l7\216c\023\304\032\061>7\216\343\301\250\v\353m7\216㒗t.K7\216\343\274\353\215\320\357\067\216\343`"...) at ucp/test_ucp_atomic.cc:50
#11 0x00000000006d0690 in test_ucp_memheap::test_blocking_xfer (this=0x141ffd0, send=
    (void (test_ucp_memheap::*)(test_ucp_memheap * const, ucp_test_base::entity *, size_t, void *, ucp_rkey_h, std::string &)) 0x6c2390 <test_ucp_atomic::blocking_add<unsigned int>(ucp_test_base::entity*, unsigned long, void*, ucp_rkey*, std::string&)>, memheap_size=3072, max_iter=300, alignment=4, malloc_allocate=false, is_ep_flush=false) at ucp/test_ucp_memheap.cc:230
#12 0x00000000006c25d4 in test_ucp_atomic::test<unsigned int, void (test_ucp_atomic::*)(ucp_test_base::entity*, unsigned long, void*, ucp_rkey*, std::string&)> (this=0x141ffd0, f=
    (void (test_ucp_atomic::*)(test_ucp_atomic * const, ucp_test_base::entity *, unsigned long, void *, ucp_rkey *, std::basic_string<char, std::char_traits<char>, std::allocator<char> > &)) 0x6c2390 <test_ucp_atomic::blocking_add<unsigned int>(ucp_test_base::entity*, unsigned long, void*, ucp_rkey*, std::string&)>, malloc_allocate=false) at ucp/test_ucp_atomic.cc:188
#13 0x00000000006bcf9c in test_ucp_atomic32_atomic_add_Test::test_body (this=0x141ffd0) at ucp/test_ucp_atomic.cc:205
#14 0x000000000054c368 in ucs::test_base::run (this=0x141ffd0) at common/test.cc:280
#15 0x000000000054c564 in ucs::test_base::TestBodyProxy (this=0x141ffd0) at common/test.cc:306
#16 0x000000000067fff4 in ucp_test::TestBody (this=0x141ffd0) at ucp/ucp_test.h:144
#17 0x000000000052d748 in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void> (object=0x1420050, method=&virtual testing::Test::TestBody(), location=0x97b738 "the test body") at common/gtest-all.cc:3562
#18 0x00000000005288cc in testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=0x1420050, method=&virtual testing::Test::TestBody(), location=0x97b738 "the test body") at common/gtest-all.cc:3598
#19 0x00000000005114f4 in testing::Test::Run (this=0x1420050) at common/gtest-all.cc:3635
#20 0x0000000000511c48 in testing::TestInfo::Run (this=0xf2cd60) at common/gtest-all.cc:3812
#21 0x00000000005122c8 in testing::TestCase::Run (this=0xf2ce20) at common/gtest-all.cc:3930
#22 0x00000000005181c4 in testing::internal::UnitTestImpl::RunAllTests (this=0xc719b0) at common/gtest-all.cc:5808
#23 0x000000000052ea18 in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0xc719b0,
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x517f28 <testing::internal::UnitTestImpl::RunAllTests()>, location=0x97c110 "auxiliary test code (environments or event listeners)")
    at common/gtest-all.cc:3562
#24 0x00000000005296f8 in testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0xc719b0,
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x517f28 <testing::internal::UnitTestImpl::RunAllTests()>, location=0x97c110 "auxiliary test code (environments or event listeners)")
    at common/gtest-all.cc:3598
#25 0x0000000000516fe4 in testing::UnitTest::Run (this=0xc631c8 <testing::UnitTest::GetInstance()::instance>) at common/gtest-all.cc:5422
#26 0x00000000005381d4 in RUN_ALL_TESTS () at common/gtest.h:20059
#27 0x00000000005380a4 in main (argc=1, argv=0xffffffffe2b8) at common/main.cc:102
```

**Comment by dmitrygx** [comment]
fixed by https://github.com/hjelmn/xpmem/pull/31
