### ISSUE TITLE
SparkUCX: UCX_SOCKADDR_CM_ENABLE + UCX_NET_DEVICES segfault null ep

### ISSUE THREAD

**Issue by petro-rudenko** [openucx/ucx#5053]
### Describe the bug
```
>>> t 29
[Switching to thread 29 (Thread 0x2b808a3c9700 (LWP 146386))]
#0  0x00002b667018b199 in waitpid () from /lib64/libpthread.so.0
>>> bt
#0  0x00002b667018b199 in waitpid () from /lib64/libpthread.so.0
#1  0x00002b667149f270 in os::fork_and_exec(char*) () from /global/software/centos-7.x86_64/modules/langs/java/1.8.0_121/jre/lib/amd64/server/libjvm.so
#2  0x00002b667164763c in VMError::report_and_die() () from /global/software/centos-7.x86_64/modules/langs/java/1.8.0_121/jre/lib/amd64/server/libjvm.so
#3  0x00002b66714aa5bf in JVM_handle_linux_signal () from /global/software/centos-7.x86_64/modules/langs/java/1.8.0_121/jre/lib/amd64/server/libjvm.so
#4  0x00002b66714a0b03 in signalHandler(int, siginfo*, void*) () from /global/software/centos-7.x86_64/modules/langs/java/1.8.0_121/jre/lib/amd64/server/libjvm.so
#5  <signal handler called>
#6  0x00002b8094ee7a9f in uct_ep_am_bcopy (flags=0, arg=0x2b7fa1e94f00, pack_cb=0x2b8094ee75b0 <ucp_rma_sw_put_pack_cb>, id=17 '\021', ep=0x0) at /global/scratch/groups/mellanox/for_pengzhi_spark/sparkucx/ucx/contrib/../src/uct/api/uct.h:2532
#7  ucp_rma_sw_progress_put (self=0x2b7fa1e94fa8) at /global/scratch/groups/mellanox/for_pengzhi_spark/sparkucx/ucx/contrib/../src/ucp/rma/rma_sw.c:45
#8  0x00002b8094ee57ec in ucp_request_try_send (pending_flags=0, req_status=0x2b808a3c7c30, req=<optimized out>) at /global/scratch/groups/mellanox/for_pengzhi_spark/sparkucx/ucx/contrib/../src/ucp/core/ucp_request.inl:171
#9  ucp_request_send (pending_flags=0, req=<optimized out>) at /global/scratch/groups/mellanox/for_pengzhi_spark/sparkucx/ucx/contrib/../src/ucp/core/ucp_request.inl:206
#10 ucp_rma_send_request_cb (cb=0x2b809428e650 <jucx_request_callback(void*, ucs_status_t)>, req=<optimized out>) at /global/scratch/groups/mellanox/for_pengzhi_spark/sparkucx/ucx/contrib/../src/ucp/rma/rma.inl:20
#11 ucp_rma_nonblocking_cb (cb=0x2b809428e650 <jucx_request_callback(void*, ucs_status_t)>, zcopy_thresh=18446744073709551615, progress_cb=0x2b8094ee7a50 <ucp_rma_sw_progress_put>, rkey=<optimized out>, remote_addr=46973776325288, length=<optimized out>, buffer=<optimized out>, ep=0x2b816386f000) at /global/scratch/groups/mellanox/for_pengzhi_spark/sparkucx/ucx/contrib/../src/ucp/rma/rma_send.c:195
#12 ucp_put_nb (ep=0x2b816386f000, buffer=<optimized out>, length=<optimized out>, remote_addr=46973776325288, rkey=<optimized out>, cb=0x2b809428e650 <jucx_request_callback(void*, ucs_status_t)>) at /global/scratch/groups/mellanox/for_pengzhi_spark/sparkucx/ucx/contrib/../src/ucp/rma/rma_send.c:265
#13 0x00002b809428d5ae in Java_org_openucx_jucx_ucp_UcpEndpoint_putNonBlockingNative () from /local/scratch/groups/mellanox/for_pengzhi_spark/sparkucx/data/nm-local-dir/usercache/peterr/appcache/application_1587120586881_0024/container_1587120586881_0024_01_000006/tmp/jucx6628841211317215358/libjucx.so
#14 0x00002b6678017a14 in ?? ()
#15 0x00002b7fa1e8af00 in ?? ()
#16 0x0000000000000000 in ?? ()
>>> f 6
#6  0x00002b8094ee7a9f in uct_ep_am_bcopy (flags=0, arg=0x2b7fa1e94f00, pack_cb=0x2b8094ee75b0 <ucp_rma_sw_put_pack_cb>, id=17 '\021', ep=0x0) at /global/scratch/groups/mellanox/for_pengzhi_spark/sparkucx/ucx/contrib/../src/uct/api/uct.h:2532
2532        return ep->iface->ops.ep_am_bcopy(ep, id, pack_cb, arg, flags);
>>> p ep
$1 = (struct uct_ep *) 0x0
```

### Steps to Reproduce

Set both `UCX_SOCKADDR_CM_ENABLE` and  `UCX_NET_DEVICES`.

**Comment by petro-rudenko** [comment]
Seems like doesn't reproduce any more with latest master. Closing for now, will reopen if will appear.
