### ISSUE TITLE
check at runtime cpu features compatibility

### ISSUE THREAD

**Issue by miked-mellanox** [openucx/ucx#559]
## Problem

* UCX can be compiled on machines with new cpu features available (avx, ...)
* The binary version of UCX can be executed on same arch machine but w/ lower cpu features support
* The ucx will fail with unclear stack trace:

``` 
#0  0x00007f159fc16605 in sglib_hashed_ucs_async_handler_t_init (table=0x7f159fee0b78) at async/async.c:23
#1  0x00007f159fc17400 in ucs_async_global_init () at async/async.c:402
#2  0x00007f159fca9b46 in __do_global_ctors_aux () from /hpc/local/benchmarks/hpc-stack-gcc-Saturday/install/ucx/lib/libucs.so.2
#3  0x00007f159fc14b4b in _init () from /hpc/local/benchmarks/hpc-stack-gcc-Saturday/install/ucx/lib/libucs.so.2
#4  0x0000003900000000 in ?? ()
#5  0x000000399020e555 in _dl_init_internal () from /lib64/ld-linux-x86-64.so.2
#6  0x0000003990212cb5 in dl_open_worker () from /lib64/ld-linux-x86-64.so.2
#7  0x000000399020e1b6 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#8  0x00000039902124fa in _dl_open () from /lib64/ld-linux-x86-64.so.2
#9  0x0000003990e00f66 in dlopen_doit () from /lib64/libdl.so.2
#10 0x000000399020e1b6 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#11 0x0000003990e0129c in _dlerror_run () from /lib64/libdl.so.2
#12 0x0000003990e00ee1 in dlopen@@GLIBC_2.2.5 () from /lib64/libdl.so.2
#13 0x00007f15a4e6d137 in do_dlopen (fname=0xcb68fa "/hpc/local/benchmarks/hpc-stack-gcc-Saturday/install/ompi-v1.10/lib/openmpi/mca_coll_hcoll", use_ext=<value optimized out>, 
    private_namespace=<value optimized out>, handle=0x7fff86d70338, err_msg=0x7fff86d70328) at dl_dlopen_module.c:38
#14 dlopen_open (fname=0xcb68fa "/hpc/local/benchmarks/hpc-stack-gcc-Saturday/install/ompi-v1.10/lib/openmpi/mca_coll_hcoll", use_ext=<value optimized out>, 
    private_namespace=<value optimized out>, handle=0x7fff86d70338, err_msg=0x7fff86d70328) at dl_dlopen_module.c:95
#15 0x00007f15a4e5030a in open_component (target_file=0xcb5870, found_components=0x7fff86d70480) at mca_base_component_find.c:557
#16 0x00007f15a4e51684 in find_dyn_components (directory=0x0, type=0x7f15a580f72c "coll", static_components=<value optimized out>, requested_components=<value optimized out>, 
    found_components=<value optimized out>, open_dso_components=true) at mca_base_component_find.c:446
#17 mca_base_component_find (directory=0x0, type=0x7f15a580f72c "coll", static_components=<value optimized out>, requested_components=<value optimized out>, 
    found_components=<value optimized out>, open_dso_components=true) at mca_base_component_find.c:190
#18 0x00007f15a4e5aed2 in mca_base_framework_components_register (framework=0x7f15a5a2dba0, flags=<value optimized out>) at mca_base_components_register.c:57
#19 0x00007f15a4e5b354 in mca_base_framework_register (framework=0x7f15a5a2dba0, flags=MCA_BASE_REGISTER_DEFAULT) at mca_base_framework.c:115
#20 0x00007f15a4e5b4d2 in mca_base_framework_open (framework=0x7f15a5a2dba0, flags=MCA_BASE_OPEN_DEFAULT) at mca_base_framework.c:134
#21 0x00007f15a57ce483 in ompi_mpi_init (argc=3, argv=0x7fff86d70d38, requested=0, provided=<value optimized out>) at runtime/ompi_mpi_init.c:583
#22 0x00007f15a57e3390 in PMPI_Init (argc=0x7fff86d70c4c, argv=0x7fff86d70c40) at pinit.c:84
#23 0x00000000004ab50b in gasneti_bootstrapInit_mpi ()
#24 0x0000000000430377 in gasnetc_init ()
#25 0x0000000000430e6e in gasnet_init_GASNET_SEQpshmFASTnodebugnotracenostatsnodebugmallocnosrclines ()
#26 0x000000000041a34c in upcr_startup_init ()
#27 0x000000000041f7b8 in bupc_init_reentrant ()
#28 0x000000000041577e in main ()
```

## Proposal

* Ucx will check at run-time available cpu features and fail in it was compiled w. higher level than system it is running now on
* UCX can provide fallback implementation for internal flows using specific cpu features

## More details for options are here:

* https://software.intel.com/en-us/articles/how-to-manually-target-2nd-generation-intel-core-processors-with-support-for-intel-avx

* https://gcc.gnu.org/onlinedocs/gcc/x86-Built-in-Functions.html

* https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Developer_Guide/compilers.html

**Comment by igor-ivanov** [comment]
@igor-ivanov

**Comment by igor-ivanov** [comment]
@miked-mellanox is ucx library located at /hpc/local/benchmarks/hpc-stack-gcc-Saturday/install/ucx/lib/  compiled using --with-vax option?

**Comment by miked-mellanox** [comment]
i dont know. it was compiled on sandybridge machine. should fail on mir (westmere)

**Comment by igor-ivanov** [comment]
I see that this option is set by default. 
The first question: is it a correct way to build optimized (non portable) library by default?
The second: if we would like to fix issue for daily build only I guess we need to add --without-vax or --with-vax=no.

**Comment by yosefe** [comment]
@igor-ivanov we just want to detect at library load time that it was build for another architecture, print a descriptive error message, and bail. at this point no need for a method to recover from this problem.

**Comment by igor-ivanov** [comment]
@yosefe I see
