### ISSUE TITLE
Error when running UcxBenchmark

### ISSUE THREAD

**Issue by gitzhangjingfang** [openucx/ucx#6124]
### Describe the bug
When I run benchmark, but it not work, I get these errors:

``` /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -javaagent:/opt/tools/idea/idea-IC-201.8743.12/lib/idea_rt.jar=43451:/opt/tools/idea/idea-IC-201.8743.12/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/icedtea-sound.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/java-atk-wrapper.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/management-agent.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/rt.jar:/opt/code/ucx-1.9.0/bindings/java/src/main/native/build-java/classes org.openucx.jucx.examples.UcxReadBWBenchmarkReceiver
Waiting for connections on /127.0.0.1:54321 ...
[1610532563.621748] [openlookeng-jf:4458 :0]         select.c:445  UCX  ERROR no remote registered memory access transport to <no debug data>: posix/memory - no peer failure handler, sysv/memory - no peer failure handler, self/memory - no peer failure handler, tcp/eth0 - no put short, sockcm/sockaddr - no pending, cma/memory - no put short
[1610532563.621774] [openlookeng-jf:4458 :0]         ucp_ep.c:530  UCX  ERROR connection request failed on listener 0x7f18183d0700 with status Destination is unreachable
[1610532563.621817] [openlookeng-jf:4458 :0]      endpoint.cc:96   UCX  ERROR JUCX: Destination is unreachable
Exception in thread "main" org.openucx.jucx.UcxException: Destination is unreachable
	at org.openucx.jucx.ucp.UcpEndpoint.createEndpointNative(Native Method)
	at org.openucx.jucx.ucp.UcpEndpoint.<init>(UcpEndpoint.java:33)
	at org.openucx.jucx.ucp.UcpWorker.newEndpoint(UcpWorker.java:42)
	at org.openucx.jucx.examples.UcxReadBWBenchmarkReceiver.main(UcxReadBWBenchmarkReceiver.java:45)
Process finished with exit code 1
```
And 

``` /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -javaagent:/opt/tools/idea/idea-IC-201.8743.12/lib/idea_rt.jar=45613:/opt/tools/idea/idea-IC-201.8743.12/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/icedtea-sound.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/java-atk-wrapper.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/management-agent.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/rt.jar:/opt/code/ucx-1.9.0/bindings/java/src/main/native/build-java/classes org.openucx.jucx.examples.UcxReadBWBenchmarkSender
Exception in thread "main" java.lang.NullPointerException
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:447)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at org.openucx.jucx.ucp.UcpEndpoint.lambda$new$0(UcpEndpoint.java:27)
	at org.openucx.jucx.ucp.UcpWorker.progressWorkerNative(Native Method)
	at org.openucx.jucx.ucp.UcpWorker.progress(UcpWorker.java:63)
	at org.openucx.jucx.ucp.UcpWorker.progressRequest(UcpWorker.java:71)
	at org.openucx.jucx.examples.UcxReadBWBenchmarkSender.main(UcxReadBWBenchmarkSender.java:63)
Process finished with exit code 1
```
### Steps to Reproduce
-  root ./autogen.sh 
-  root ./contrib/configure-release  --with-java  --disable-numa
-  root make -j8 install
-  Run benchmark receiver and sender.

### Setup and versions
- OS version (e.g Linux distro) + CPU architecture (x86_64/aarch64/ppc64le/...)
   - `cat /etc/issue` or `cat /etc/redhat-release` + `uname -a`
   - Ubuntu 18.04.4 LTS
- For RDMA/IB/RoCE related issues:
    - Driver version:
        - `rpm -q rdma-core` or `rpm -q libibverbs`
        - or: MLNX_OFED version `ofed_info -s`
   - HW information from `ibstat` or `ibv_devinfo -vv` command
- For GPU related issues:
  - GPU type
  - Cuda: 
      - Drivers version
      - Check if peer-direct is loaded: `lsmod|grep nv_peer_mem` and/or gdrcopy: `lsmod|grep gdrdrv`

### Additional information (depending on the issue)
- OpenMPI version
- Output of `ucx_info -d` to show transports and devices recognized by UCX
- Configure result - config.log
- Log file - configure UCX with "--enable-logging" - and run with "UCX_LOG_LEVEL=data"
``` 
root@openlookeng-jf:/opt/code/ucx-1.9.0/bindings/java# ucx_info -d
#
# Memory domain: posix
#     Component: posix
#             allocate: unlimited
#           remote key: 24 bytes
#           rkey_ptr is supported
#
#   Transport: posix
#      Device: memory
#
#      capabilities:
#            bandwidth: 0.00/ppn + 12179.00 MB/sec
#              latency: 80 nsec
#             overhead: 10 nsec
#            put_short: <= 4294967295
#            put_bcopy: unlimited
#            get_bcopy: unlimited
#             am_short: <= 100
#             am_bcopy: <= 8256
#               domain: cpu
#           atomic_add: 32, 64 bit
#           atomic_and: 32, 64 bit
#            atomic_or: 32, 64 bit
#           atomic_xor: 32, 64 bit
#          atomic_fadd: 32, 64 bit
#          atomic_fand: 32, 64 bit
#           atomic_for: 32, 64 bit
#          atomic_fxor: 32, 64 bit
#          atomic_swap: 32, 64 bit
#         atomic_cswap: 32, 64 bit
#           connection: to iface
#      device priority: 0
#     device num paths: 1
#              max eps: inf
#       device address: 8 bytes
#        iface address: 8 bytes
#       error handling: none
#
#
# Memory domain: sysv
#     Component: sysv
#             allocate: unlimited
#           remote key: 12 bytes
#           rkey_ptr is supported
#
#   Transport: sysv
#      Device: memory
#
#      capabilities:
#            bandwidth: 0.00/ppn + 12179.00 MB/sec
#              latency: 80 nsec
#             overhead: 10 nsec
#            put_short: <= 4294967295
#            put_bcopy: unlimited
#            get_bcopy: unlimited
#             am_short: <= 100
#             am_bcopy: <= 8256
#               domain: cpu
#           atomic_add: 32, 64 bit
#           atomic_and: 32, 64 bit
#            atomic_or: 32, 64 bit
#           atomic_xor: 32, 64 bit
#          atomic_fadd: 32, 64 bit
#          atomic_fand: 32, 64 bit
#           atomic_for: 32, 64 bit
#          atomic_fxor: 32, 64 bit
#          atomic_swap: 32, 64 bit
#         atomic_cswap: 32, 64 bit
#           connection: to iface
#      device priority: 0
#     device num paths: 1
#              max eps: inf
#       device address: 8 bytes
#        iface address: 8 bytes
#       error handling: none
#
#
# Memory domain: self
#     Component: self
#             register: unlimited, cost: 0 nsec
#           remote key: 0 bytes
#
#   Transport: self
#      Device: memory
#
#      capabilities:
#            bandwidth: 0.00/ppn + 6911.00 MB/sec
#              latency: 0 nsec
#             overhead: 10 nsec
#            put_short: <= 4294967295
#            put_bcopy: unlimited
#            get_bcopy: unlimited
#             am_short: <= 8K
#             am_bcopy: <= 8K
#               domain: cpu
#           atomic_add: 32, 64 bit
#           atomic_and: 32, 64 bit
#            atomic_or: 32, 64 bit
#           atomic_xor: 32, 64 bit
#          atomic_fadd: 32, 64 bit
#          atomic_fand: 32, 64 bit
#           atomic_for: 32, 64 bit
#          atomic_fxor: 32, 64 bit
#          atomic_swap: 32, 64 bit
#         atomic_cswap: 32, 64 bit
#           connection: to iface
#      device priority: 0
#     device num paths: 1
#              max eps: inf
#       device address: 0 bytes
#        iface address: 8 bytes
#       error handling: none
#
#
# Memory domain: tcp
#     Component: tcp
#             register: unlimited, cost: 0 nsec
#           remote key: 0 bytes
#
#   Transport: tcp
#      Device: eth0
#
#      capabilities:
#            bandwidth: 11.32/ppn + 0.00 MB/sec
#              latency: 10960 nsec
#             overhead: 50000 nsec
#            put_zcopy: <= 18446744073709551590, up to 6 iov
#  put_opt_zcopy_align: <= 1
#        put_align_mtu: <= 0
#             am_short: <= 8K
#             am_bcopy: <= 8K
#             am_zcopy: <= 64K, up to 6 iov
#   am_opt_zcopy_align: <= 1
#         am_align_mtu: <= 0
#            am header: <= 8037
#           connection: to iface
#      device priority: 1
#     device num paths: 1
#              max eps: 256
#       device address: 4 bytes
#        iface address: 2 bytes
#       error handling: none
#
#
# Connection manager: tcp
#      max_conn_priv: 2032 bytes
#
# Memory domain: sockcm
#     Component: sockcm
#           supports client-server connection establishment via sockaddr
#   < no supported devices found >
#
# Memory domain: cma
#     Component: cma
#             register: unlimited, cost: 9 nsec
#
#   Transport: cma
#      Device: memory
#
#      capabilities:
#            bandwidth: 0.00/ppn + 11145.00 MB/sec
#              latency: 80 nsec
#             overhead: 400 nsec
#            put_zcopy: unlimited, up to 16 iov
#  put_opt_zcopy_align: <= 1
#        put_align_mtu: <= 1
#            get_zcopy: unlimited, up to 16 iov
#  get_opt_zcopy_align: <= 1
#        get_align_mtu: <= 1
#           connection: to iface
#      device priority: 0
#     device num paths: 1
#              max eps: inf
#       device address: 8 bytes
#        iface address: 4 bytes
#       error handling: none
#

```

**Comment by Blopeur** [comment]
It seems that the Java Benchmark doesn't handle TCP based transport.

It requires:  [.requestRmaFeature()](https://github.com/openucx/ucx/blob/c1560bd8488b6caeada4af9a05f3ad4531b916de/bindings/java/src/main/java/org/openucx/jucx/examples/UcxBenchmark.java#L87) 

And also .setPeerErrorHandlingMode() 

Which are both incompatible with TCP transport. 


I have removed these two requirements and the benchmark seems to start fine. 

and then Hang on : 

```
[1610715263.232882] [benoit-ThinkPad-X260:241169:0]      uct_iface.c:67   UCX  WARN  got active message id 18, but no handler installed
[1610715263.232915] [benoit-ThinkPad-X260:241169:0]      uct_iface.c:68   UCX  WARN  payload 32 of 32 bytes:
[1610715263.232915] [benoit-ThinkPad-X260:241169:0]      uct_iface.c:68   UCX  WARN  00f069ed:f57f0000:10270000:00000000
[1610715263.232915] [benoit-ThinkPad-X260:241169:0]      uct_iface.c:68   UCX  WARN  001095ec:f57f0000:00bc2a00:3d7f0000
[1610715263.233099] [benoit-ThinkPad-X260:241169:0]            log.c:488  UCX  WARN  ==== backtrace (tid: 241170) ====
[1610715263.233111] [benoit-ThinkPad-X260:241169:0]            log.c:491  UCX  WARN   0  /home/benoit/huawei/ucx-1.9.0/src/ucs/.libs/libucs.so.0(ucs_log_print_backtrace+0x36) [0x7ff5ed716e16]
[1610715263.233118] [benoit-ThinkPad-X260:241169:0]            log.c:491  UCX  WARN   1  /home/benoit/huawei/ucx-1.9.0/src/uct/.libs/libuct.so.0(+0x11cc2) [0x7ff5ed6c9cc2]
[1610715263.233127] [benoit-ThinkPad-X260:241169:0]            log.c:491  UCX  WARN   2  /home/benoit/huawei/ucx-1.9.0/src/uct/.libs/libuct.so.0(+0x1aabf) [0x7ff5ed6d2abf]
[1610715263.233133] [benoit-ThinkPad-X260:241169:0]            log.c:491  UCX  WARN   3  /home/benoit/huawei/ucx-1.9.0/src/uct/.libs/libuct.so.0(+0x1b038) [0x7ff5ed6d3038]
[1610715263.233140] [benoit-ThinkPad-X260:241169:0]            log.c:491  UCX  WARN   4  /home/benoit/huawei/ucx-1.9.0/src/uct/.libs/libuct.so.0(+0x1c4bb) [0x7ff5ed6d44bb]
[1610715263.233146] [benoit-ThinkPad-X260:241169:0]            log.c:491  UCX  WARN   5  /home/benoit/huawei/ucx-1.9.0/src/ucs/.libs/libucs.so.0(ucs_event_set_wait+0xf5) [0x7ff5ed71b1b5]
[1610715263.233156] [benoit-ThinkPad-X260:241169:0]            log.c:491  UCX  WARN   6  /home/benoit/huawei/ucx-1.9.0/src/uct/.libs/libuct.so.0(uct_tcp_iface_progress+0x7b) [0x7ff5ed6d456b]
[1610715263.233163] [benoit-ThinkPad-X260:241169:0]            log.c:491  UCX  WARN   7  /home/benoit/huawei/ucx-1.9.0/src/ucp/.libs/libucp.so.0(ucp_worker_progress+0x2a) [0x7ff5ed76248a]
[1610715263.233169] [benoit-ThinkPad-X260:241169:0]            log.c:491  UCX  WARN   8  /tmp/jucx1292205559869580618/libjucx.so(Java_org_openucx_jucx_ucp_UcpWorker_progressWorkerNative+0x24) [0x7ff5ed7b5272]
[1610715263.233176] [benoit-ThinkPad-X260:241169:0]            log.c:491  UCX  WARN   9  [0x7ff60517ea31]
[1610715263.233180] [benoit-ThinkPad-X260:241169:0]            log.c:493  UCX  WARN  =================================

```

Any idea what's the reason for the error above?
