### ISSUE TITLE
Segfault in recvAmData on error request

### ISSUE THREAD

**Issue by petro-rudenko** [openucx/ucx#6596]
### Describe the bug
```
#8  0x00007f2cc4e20894 in uct_iface_release_desc (desc=0x7f28005aadb2) at /gpfs/fs1/prudenko/rapids/ucx/contrib/../src/uct/api/uct.h:2
627
#9  ucp_recv_desc_release (rdesc=0x7f28005aadd2) at /gpfs/fs1/prudenko/rapids/ucx/contrib/../src/ucp/core/ucp_request.inl:694
#10 ucp_request_complete_am_recv (status=UCS_ERR_IO_ERROR, req=0x7f282d9dee00) at /gpfs/fs1/prudenko/rapids/ucx/contrib/../src/ucp/co$
e/ucp_request.inl:716
#11 ucp_rndv_recv_req_complete (status=UCS_ERR_IO_ERROR, req=0x7f282d9dee00) at /gpfs/fs1/prudenko/rapids/ucx/contrib/../src/ucp/rndv$
rndv.c:296
#12 ucp_rndv_get_completion_inner (self=0x7f282d9deae0) at /gpfs/fs1/prudenko/rapids/ucx/contrib/../src/ucp/rndv/rndv.c:603
#13 ucp_rndv_get_completion (self=0x7f282d9deae0) at /gpfs/fs1/prudenko/rapids/ucx/contrib/../src/ucp/rndv/rndv.c:562
#14 0x00007f2cc4e1fedc in ucp_rndv_progress_rma_zcopy_common (req=0x7f282d9dea40, lane=2 '\002', uct_rkey=139811028882080, proto=2) a$
 /gpfs/fs1/prudenko/rapids/ucx/contrib/../src/ucp/rndv/rndv.c:508
#15 0x00007f2cc4e2004e in ucp_rndv_progress_rma_get_zcopy_inner (self=0x7f282d9deb18) at /gpfs/fs1/prudenko/rapids/ucx/contrib/../src$
ucp/rndv/rndv.c:543
#16 ucp_rndv_progress_rma_get_zcopy (self=0x7f282d9deb18) at /gpfs/fs1/prudenko/rapids/ucx/contrib/../src/ucp/rndv/rndv.c:532
#17 0x00007f2cc4e22202 in ucp_request_try_send (pending_flags=0, req=0x7f282d9dea40) at /gpfs/fs1/prudenko/rapids/ucx/contrib/../src/$
cp/core/ucp_request.inl:295
#18 ucp_request_send (pending_flags=0, req=0x7f282d9dea40) at /gpfs/fs1/prudenko/rapids/ucx/contrib/../src/ucp/core/ucp_request.inl:3$
0
#19 ucp_rndv_req_send_rma_get (rndv_req=0x7f282d9dea40, rreq=0x7f282d9dee00, rndv_rts_hdr=0x7f28005aae02, rkey_buf=0x7f28005aae2c) at
/gpfs/fs1/prudenko/rapids/ucx/contrib/../src/ucp/rndv/rndv.c:810
#20 0x00007f2cc4e27f6a in ucp_rndv_receive_inner (rkey_buf=0x7f28005aae2c, rndv_rts_hdr=0x7f28005aae02, rreq=0x7f282d9dee00, worker=0$
7f2d8a576060) at /gpfs/fs1/prudenko/rapids/ucx/contrib/../src/ucp/rndv/rndv.c:1376
#21 ucp_rndv_receive (worker=0x7f2d8a576060, rreq=0x7f282d9dee00, rndv_rts_hdr=0x7f28005aae02, rkey_buf=0x7f28005aae2c) at /gpfs/fs1/$
rudenko/rapids/ucx/contrib/../src/ucp/rndv/rndv.c:1307
#22 0x00007f2cc4da15e7 in ucp_am_recv_data_nbx_inner (param=0x7f2db7aa1040, count=192, buffer=0x7f294c000100, data_desc=0x7f28005aae0$
, worker=0x7f2d8a576060) at /gpfs/fs1/prudenko/rapids/ucx/contrib/../src/ucp/core/ucp_am.c:1074
#23 ucp_am_recv_data_nbx (worker=0x7f2d8a576060, data_desc=0x7f28005aae02, buffer=0x7f294c000100, count=192, param=0x7f2db7aa1040) at
/gpfs/fs1/prudenko/rapids/ucx/contrib/../src/ucp/core/ucp_am.c:1011
#24 0x00007f2cc4b6e187 in Java_org_openucx_jucx_ucp_UcpWorker_recvAmDataNonBlockingNative (env=0x7f2c794e0340, cls=<optimized out>, u$
p_worker_ptr=139833571237984, data_descr_ptr=139809781362178, address=139815345455360, length=192, callback=0x7f2db7aa1180, memory_ty$
e=1) at worker.cc:333

>>> f 8
#8  0x00007f2cc4e20894 in uct_iface_release_desc (desc=0x7f28005aadb2) at /gpfs/fs1/prudenko/rapids/ucx/contrib/../src/uct/api/uct.h:2627
2627        release_desc->cb(release_desc, desc);
>>> l
2622     * @param [in]  desc  Descriptor to release.
2623     */
2624    UCT_INLINE_API void uct_iface_release_desc(void *desc)
2625    {
2626        uct_recv_desc_t *release_desc = uct_recv_desc(desc);
2627        release_desc->cb(release_desc, desc);
2628    }
2629
2630
2631    /**
>>> p desc
$19 = (void *) 0x7f28005aadb2
>>> p release_desc
$20 = (uct_recv_desc_t *) 0x0

```

**Comment by brminich** [comment]
is there a reproducer?

**Comment by petro-rudenko** [comment]
It's SparkUCX on prometheus. There are other issues that cause the request to fail with IO_ERROR.

**Comment by brminich** [comment]
what is the UCX version?

**Comment by petro-rudenko** [comment]
master
