### ISSUE TITLE
ucp_ep_Create corrupted worker->all_eps

### ISSUE THREAD

**Issue by petro-rudenko** [openucx/ucx#6618]
```
#7  <signal handler called>
#8  0x00007f55fc6e0253 in ucs_list_insert_replace (prev=0x0, next=0x7f5562ef21d0, elem=0x7f56f8024cb0) at /gpfs/fs1/prudenko/rapids/ucx/contrib/../src/ucs/datastruct/list.h:58
#9  0x00007f55fc6e028f in ucs_list_insert_before (pos=0x7f5562ef21d0, new_link=0x7f56f8024cb0) at /gpfs/fs1/prudenko/rapids/ucx/contrib/../src/ucs/datastruct/list.h:95
#10 0x00007f55fc6e3a78 in ucp_worker_create_ep (worker=0x7f5562ef2090, ep_init_flags=54, peer_name=0x7f56aa5f4c80 "192.168.40.22:21819", message=0x7f55fc813470 "from api call", ep_p=0x7f56aa
5f4c78) at /gpfs/fs1/prudenko/rapids/ucx/contrib/../src/ucp/core/ucp_ep.c:318
#11 0x00007f55fc6e4fc4 in ucp_ep_create_to_sock_addr (worker=0x7f5562ef2090, params=0x7f56aa5f4da0, ep_p=0x7f56aa5f4d30) at /gpfs/fs1/prudenko/rapids/ucx/contrib/../src/ucp/core/ucp_ep.c:590
#12 0x00007f55fc6e5903 in ucp_ep_create (worker=0x7f5562ef2090, params=0x7f56aa5f4da0, ep_p=0x7f56aa5f4df0) at /gpfs/fs1/prudenko/rapids/ucx/contrib/../src/ucp/core/ucp_ep.c:806
#13 0x00007f55fc4a22a1 in Java_org_openucx_jucx_ucp_UcpEndpoint_createEndpointNative (env=0x7f5560946b40, jucx_ep=0x7f56aa5f4f58, ucp_ep_params=0x7f56aa5f4f50, worker_ptr=140004708786320) at
 endpoint.cc:94
```

To track issues in SparkUCX.

**Comment by petro-rudenko** [comment]
Seems like MT issue
