### ISSUE TITLE
[mtt] ucx-cuda segfault 

### ISSUE THREAD

**Issue by avildema** [openucx/ucx#6706]
Configuration
```
OMPI: 4.1.1rc1
MOFED: MLNX_OFED_LINUX-5.2-2.2.0.0
Module: hpcx-gcc (2021-04-23)
Test module: none
Nodes: vulcan x3 (ppn=24(x3), nodelist=vulcan[02-04])
```
 
MTT log:

http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20210423_145643_31475_8033_vulcan02.swx.labs.mlnx/html/test_stdout_CtRuwP.txt
 
Cmd:
`/hpc/local/benchmarks/daily/next/2021-04-23/hpcx-gcc-redhat7.6/ompi/bin/mpirun -np 72 --display-map -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' -x UCX_ERROR_SIGNALS=SIGILL,SIGSEGV,SIGBUS,SIGFPE,SIGABRT -x UCX_HANDLE_ERRORS=bt -x UCX_IB_PCI_RELAXED_ORDERING=off --bind-to core -x UCX_NET_DEVICES=mlx5_0:1 -mca osc ucx -x UCX_IB_REG_METHODS=rcache,direct -x UCX_UD_TIMEOUT=10m -mca pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0 -x UCX_IB_NUM_PATHS=4 -x UCX_MAX_EAGER_LANES=4 -x UCX_MAX_RNDV_LANES=4 --map-by node /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20210423_145643_31475_8033_vulcan02.swx.labs.mlnx/installs/1_pz/tests/mpi-test-suite/ompi-tests/mpi_test_suite/mpi_test_suite -x relaxed -t 'All,^One-sided,^IO,^Environment' -n 300`
 
Output:
```sh
Sat Apr 24 01:46:19 2021[1,0]<stdout>:Collective tests Bcast (31/44), comm MPI_COMM_WORLD (1/14), type MPI_HINDEXED_INT (25/28)

node=vulcan02, pid=2705:
Thread 5 (Thread 0x7fc0ff307700 (LWP 2720)):
#0  0x00007fc102c7b483 in epoll_wait () from /lib64/libc.so.6
#1  0x00007fc102432133 in epoll_dispatch (base=0x7d08e0, tv=<optimized out>) at epoll.c:407
#2  0x00007fc102435b80 in opal_libevent2022_event_base_loop (base=0x7d08e0, flags=flags@entry=1) at event.c:1630
#3  0x00007fc1023f046e in progress_engine (obj=<optimized out>) at runtime/opal_progress_threads.c:105
#4  0x00007fc102f51dd5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007fc102c7aead in clone () from /lib64/libc.so.6
Thread 4 (Thread 0x7fc0fbcf3700 (LWP 2729)):
#0  0x00007fc102c7b483 in epoll_wait () from /lib64/libc.so.6
#1  0x00007fc102432133 in epoll_dispatch (base=0x7f6540, tv=<optimized out>) at epoll.c:407
#2  0x00007fc102435b80 in opal_libevent2022_event_base_loop (base=0x7f6540, flags=flags@entry=1) at event.c:1630
#3  0x00007fc0fe43c34e in progress_engine (obj=<optimized out>) at runtime/pmix_progress_threads.c:232
#4  0x00007fc102f51dd5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007fc102c7aead in clone () from /lib64/libc.so.6
Thread 3 (Thread 0x7fc0f1169700 (LWP 2789)):
#0  0x00007fc102c7c33f in accept4 () from /lib64/libc.so.6
#1  0x00007fc0f2afccd3 in ?? () from /lib64/libcuda.so.1
#2  0x00007fc0f2b9ebd6 in ?? () from /lib64/libcuda.so.1
#3  0x00007fc102f51dd5 in start_thread () from /lib64/libpthread.so.0
#4  0x00007fc102c7aead in clone () from /lib64/libc.so.6
Thread 2 (Thread 0x7fc0e5fff700 (LWP 2796)):
#0  0x00007fc102c7b483 in epoll_wait () from /lib64/libc.so.6
#1  0x00007fc0f88be19c in ucs_event_set_wait (event_set=<optimized out>, num_events=num_events@entry=0x7fc0e5ffeec0, timeout_ms=<optimized out>, event_set_handler=event_set_handler@entry=0x7fc0f88a6930 <ucs_async_thread_ev_handler>, arg=arg@entry=0x7fc0e5ffeed0) at sys/event_set.c:198
#2  0x00007fc0f88a6c8c in ucs_async_thread_func (arg=0x8d1600) at async/thread.c:130
#3  0x00007fc102f51dd5 in start_thread () from /lib64/libpthread.so.0
#4  0x00007fc102c7aead in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x7fc10365e740 (LWP 2705)):
#0  0x00007fc1023ea5c2 in opal_progress () at runtime/opal_progress.c:230
#1  0x00007fc1031b30d5 in ompi_request_wait_completion (req=0xcf8210) at ../ompi/request/request.h:415
#2  ompi_request_default_wait (req_ptr=0x7ffd6442ce70, status=0x0) at request/req_wait.c:42
#3  0x00007fc1031e92ca in ompi_coll_base_bcast_intra_generic (buffer=<optimized out>, original_count=<optimized out>, datatype=<optimized out>, root=<optimized out>, comm=<optimized out>, module=<optimized out>, count_by_segment=300, tree=0xf616c0) at base/coll_base_bcast.c:210
#4  0x00007fc0e49b8c29 in ompi_coll_tuned_bcast_intra_dec_fixed (buff=<optimized out>, count=<optimized out>, datatype=<optimized out>, root=<optimized out>, comm=<optimized out>, module=<optimized out>) at coll_tuned_decision_fixed.c:649
#5  0x00007fc1031c6351 in PMPI_Bcast (buffer=<optimized out>, count=<optimized out>, datatype=<optimized out>, root=<optimized out>, comm=0x6564e0 <ompi_mpi_comm_world>) at pbcast.c:114
#6  0x0000000000406a39 in tst_coll_bcast_run (env=0x7ffd6442d2a0) at coll/tst_coll_bcast.c:72
#7  0x0000000000436a44 in tst_test_run_func (env=0x7ffd6442d2a0) at tst_tests.c:1461
#8  0x0000000000412de1 in main (argc=7, argv=0x7ffd6442d558) at mpi_test_suite.c:636

```

**Comment by brminich** [comment]
duplication of #6579 
fixed by #6802
