### ISSUE TITLE
[mtt][ucx-hwtm][mpich_tests_mpi_pt2pt] Hung many_isend test

### ISSUE THREAD

**Issue by avildema** [openucx/ucx#7636]
Configuration
```
OMPI: 4.1.2rc2
MOFED: MLNX_OFED_LINUX-5.4-1.0.3.0
Module: hpcx-gcc (2021-10-29)
Test module: none
Nodes: jazz x4 (ppn=28(x4), nodelist=jazz[17,20,22,24])
```
 
MTT log:
http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20211108_202535_190904_80562_jazz17.swx.labs.mlnx/html/test_stdout_dvtMAT.txt

Cmd:
`/hpc/local/benchmarks/daily/next/2021-10-29/hpcx-gcc-redhat7/ompi/bin/mpirun -np 112 --display-map -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' -x UCX_ERROR_SIGNALS=SIGILL,SIGSEGV,SIGBUS,SIGFPE,SIGABRT -x UCX_HANDLE_ERRORS=bt -x UCX_IB_PCI_RELAXED_ORDERING=off --bind-to core -x UCX_NET_DEVICES=mlx5_2:1 -mca osc ucx -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=dc_x,self,sm -x UCX_DC_MLX5_TM_ENABLE=y -x UCX_TM_SW_RNDV=y -x UCX_DC_MLX5_TX_POLICY=rand -mca pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0 --map-by node /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20211108_202535_190904_80562_jazz17.swx.labs.mlnx/installs/I8XV/tests/mpich_tests/mtt-tests.git/mpich/test/mpi/pt2pt/many_isend`
 
Output:
```sh
 =============================================================
node=jazz17, pid=22664:
Thread 4 (Thread 0x7efd32d8a700 (LWP 22679)):
#0  0x00007efd364fe483 in epoll_wait () from /lib64/libc.so.6
#1  0x00007efd35eb5cc3 in epoll_dispatch (base=0x1f83af0, tv=<optimized out>) at epoll.c:407
#2  0x00007efd35eb9710 in opal_libevent2022_event_base_loop (base=0x1f83af0, flags=flags@entry=1) at event.c:1630
#3  0x00007efd35e735de in progress_engine (obj=<optimized out>) at runtime/opal_progress_threads.c:105
#4  0x00007efd367d4dd5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007efd364fdead in clone () from /lib64/libc.so.6
Thread 3 (Thread 0x7efd2f779700 (LWP 22689)):
#0  0x00007efd364fe483 in epoll_wait () from /lib64/libc.so.6
#1  0x00007efd35eb5cc3 in epoll_dispatch (base=0x1fa9720, tv=<optimized out>) at epoll.c:407
#2  0x00007efd35eb9710 in opal_libevent2022_event_base_loop (base=0x1fa9720, flags=flags@entry=1) at event.c:1630
#3  0x00007efd320c534e in progress_engine (obj=<optimized out>) at runtime/pmix_progress_threads.c:232
#4  0x00007efd367d4dd5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007efd364fdead in clone () from /lib64/libc.so.6
Thread 2 (Thread 0x7efd26aae700 (LWP 22818)):
#0  0x00007efd364fe483 in epoll_wait () from /lib64/libc.so.6
#1  0x00007efd2c322aec in ucs_event_set_wait (event_set=<optimized out>, num_events=num_events@entry=0x7efd26aadec0, timeout_ms=<optimized out>, event_set_handler=event_set_handler@entry=0x7efd2c306a90 <ucs_async_thread_ev_handler>, arg=arg@entry=0x7efd26aaded0) at sys/event_set.c:198
#2  0x00007efd2c306dec in ucs_async_thread_func (arg=0x2033390) at async/thread.c:130
#3  0x00007efd367d4dd5 in start_thread () from /lib64/libpthread.so.0
#4  0x00007efd364fdead in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x7efd36ee3740 (LWP 22664)):
#0  opal_progress () at runtime/opal_progress.c:260
#1  0x00007efd36a366c5 in ompi_request_wait_completion (req=0x22107d8) at ../ompi/request/request.h:440
#2  ompi_request_default_wait (req_ptr=0x7ffca40d6a00, status=0x7ffca40d6a10) at request/req_wait.c:42
#3  0x00007efd36a7bd29 in ompi_coll_base_sendrecv_zero (stag=-16, rtag=-16, comm=0x60cdc0 <ompi_mpi_comm_world>, source=106, dest=<optimized out>) at base/coll_base_barrier.c:64
#4  ompi_coll_base_barrier_intra_bruck (comm=0x60cdc0 <ompi_mpi_comm_world>, module=<optimized out>) at base/coll_base_barrier.c:271
#5  0x00007efd36a497d8 in PMPI_Barrier (comm=0x60cdc0 <ompi_mpi_comm_world>) at pbarrier.c:74
#6  0x000000000040249d in main ()

```

**Comment by brminich** [comment]
fixed by #7637
