### ISSUE TITLE
rc/test_ucp_wireup_errh_peer.stress_connect_force_disconnect/3 fails on hwi

### ISSUE THREAD

**Issue by dmitrygx** [openucx/ucx#7886]
```
[ RUN      ] rc/test_ucp_wireup_errh_peer.stress_connect_force_disconnect/3 <rc_v/rma,unified,no_ep_match>
[swx-rdmz-ucx-arm-hwi:14650:0:14650] Caught signal 11 (Segmentation fault: address not mapped to object at address 0xc8)
==== backtrace (tid:  14650) ====
 0  /scrap/azure/agent-12/AZP_WORKSPACE/1/s/build-test/src/ucs/.libs/libucs.so.0(ucs_handle_error+0x164) [0xffffb63970f4]
 1  /scrap/azure/agent-12/AZP_WORKSPACE/1/s/build-test/src/ucs/.libs/libucs.so.0(+0x34448) [0xffffb6397448]
 2  /scrap/azure/agent-12/AZP_WORKSPACE/1/s/build-test/src/ucs/.libs/libucs.so.0(+0x345c4) [0xffffb63975c4]
 3  linux-vdso.so.1(__kernel_rt_sigreturn+0) [0xffffb6429688]
 4  /scrap/azure/agent-12/AZP_WORKSPACE/1/s/build-test/src/ucs/.libs/libucs.so.0(ucs_callbackq_remove_if+0x2c) [0xffffb6389d1c]
 5  /scrap/azure/agent-12/AZP_WORKSPACE/1/s/build-test/src/ucp/.libs/libucp.so.0(ucp_ep_destroy_base+0x60) [0xffffb61b89d0]
 6  /scrap/azure/agent-12/AZP_WORKSPACE/1/s/build-test/src/ucp/.libs/libucp.so.0(+0x7ff78) [0xffffb6208f78]
 7  /scrap/azure/agent-12/AZP_WORKSPACE/1/s/build-test/src/ucs/.libs/libucs.so.0(+0x256a0) [0xffffb63886a0]
 8  /scrap/azure/agent-12/AZP_WORKSPACE/1/s/build-test/src/ucp/.libs/libucp.so.0(ucp_worker_progress+0x68) [0xffffb61d7cf8]
 9  /scrap/azure/agent-12/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0x7e7234) [0xaaaac1b09234]
10  /scrap/azure/agent-12/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0x71db44) [0xaaaac1a3fb44]
11  /scrap/azure/agent-12/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0x36ea88) [0xaaaac1690a88]
12  /scrap/azure/agent-12/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0xaabaac) [0xaaaac1dcdaac]
13  /scrap/azure/agent-12/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0xa9e568) [0xaaaac1dc0568]
14  /scrap/azure/agent-12/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0xa9e70c) [0xaaaac1dc070c]
15  /scrap/azure/agent-12/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0xa9e970) [0xaaaac1dc0970]
16  /scrap/azure/agent-12/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0xaa4f1c) [0xaaaac1dc6f1c]
17  /scrap/azure/agent-12/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0xaa510c) [0xaaaac1dc710c]
18  /scrap/azure/agent-12/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0x2eac70) [0xaaaac160cc70]
19  /lib/aarch64-linux-gnu/libc.so.6(__libc_start_main+0xe0) [0xffffb5c5a6e0]
20  /scrap/azure/agent-12/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0x350cd0) [0xaaaac1672cd0]
=================================
```
https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=36060&view=logs&j=fa9b49c1-d497-5b0a-6030-ccf18faa6d8c&t=93e5fb16-3d78-5d11-31b7-7eefd335b140&l=39417
https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/36060/logs/445

**Comment by dmitrygx** [comment]
```
0x0000fffff7f5bd7c in ucs_recursive_spin_is_owner (lock=0xc0, self=281474842435408) at /labhome/dmitrygla/ucx/src/ucs/type/spinlock.h:78
78          return lock->owner == self;
(gdb) bt
#0  0x0000fffff7f5bd7c in ucs_recursive_spin_is_owner (lock=0xc0, self=281474842435408) at /labhome/dmitrygla/ucx/src/ucs/type/spinlock.h:78
#1  0x0000fffff7f5bdd8 in ucs_recursive_spin_lock (lock=0xc0) at /labhome/dmitrygla/ucx/src/ucs/type/spinlock.h:90
#2  0x0000fffff7f5c0d8 in ucs_callbackq_enter (cbq=0x0) at datastruct/callbackq.c:62
#3  0x0000fffff7f5dfe0 in ucs_callbackq_remove_if (cbq=0x0, pred=0xfffff7c9ef4c <ucp_ep_remove_filter>, arg=0xfffff2447c00) at datastruct/callbackq.c:575
#4  0x0000fffff7c9f240 in ucp_ep_destroy_base (ep=0xfffff2447c00) at core/ucp_ep.c:328
#5  0x0000fffff7d2c960 in ucp_worker_flush_req_set_next_ep (next_ep_iter=0xaaaaae369328, is_current_ep_valid=1, req=0xaaaaad8a5f00) at rma/flush.c:441
#6  ucp_worker_flush_complete_one (req=0xaaaaad8a5f00, status=UCS_OK, force_progress_unreg=1) at rma/flush.c:463
#7  0x0000fffff7d2cef8 in ucp_worker_flush_progress (arg=0xaaaaad8a5f00) at rma/flush.c:495
#8  0x0000fffff7f5d6e8 in ucs_callbackq_slow_proxy (arg=0xaaaaad09a760) at datastruct/callbackq.c:402
#9  0x0000fffff7cc3008 in ucs_callbackq_dispatch (cbq=0xaaaaad09a760) at /labhome/dmitrygla/ucx/src/ucs/datastruct/callbackq.h:211
#10 0x0000fffff7cd0f08 in uct_worker_progress (worker=0xaaaaad09a760) at /labhome/dmitrygla/ucx/src/uct/api/uct.h:2600
#11 ucp_worker_progress (worker=0xaaaaae3691b0) at core/ucp_worker.c:2665
#12 0x0000aaaaab32ea98 in ucp_test_base::entity::progress (this=0xaaaab0ceeea0, worker_index=0) at ucp/ucp_test.cc:1047
#13 0x0000aaaaab329910 in ucp_test::progress (this=0xaaaaae3477c0, entities=std::vector of length 2, capacity 2 = {...}, worker_index=0)
    at ucp/ucp_test.cc:168
#14 0x0000aaaaab329db0 in ucp_test::check_events (this=0xaaaaae3477c0, entities=std::vector of length 2, capacity 2 = {...}, wakeup=false, worker_index=0)
    at ucp/ucp_test.cc:249
#15 0x0000aaaaab32a0f0 in ucp_test::request_process (this=0xaaaaae3477c0, req=0xaaaaad8a6018, worker_index=0, wait=true, wakeup=false) at ucp/ucp_test.cc:291
#16 0x0000aaaaab32a240 in ucp_test::request_wait (this=0xaaaaae3477c0, req=0xaaaaad8a6018, worker_index=0, wakeup=false) at ucp/ucp_test.cc:311
#17 0x0000aaaaab329a68 in ucp_test::flush_worker (this=0xaaaaae3477c0, e=..., worker_index=0) at ucp/ucp_test.cc:195
#18 0x0000aaaaab21808c in test_ucp_wireup_errh_peer_stress_connect_force_disconnect_Test::test_body (this=0xaaaaae3477c0) at ucp/test_ucp_wireup.cc:968
#19 0x0000aaaaaadc98d8 in ucs::test_base::run (this=0xaaaaae3477c0) at common/test.cc:356
#20 0x0000aaaaaadc9b08 in ucs::test_base::TestBodyProxy (this=0xaaaaae3477c0) at common/test.cc:382
#21 0x0000aaaaab010328 in ucp_test::TestBody (this=0xaaaaae3477c0) at ucp/ucp_test.h:202
#22 0x0000aaaaab6d610c in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void> (object=0xaaaaae347840,
    method=&virtual testing::Test::TestBody(), location=0xaaaaab781a00 "the test body") at gtest.cc:2433
#23 0x0000aaaaab6d1628 in testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=0xaaaaae347840,
    method=&virtual testing::Test::TestBody(), location=0xaaaaab781a00 "the test body") at gtest.cc:2469
#24 0x0000aaaaab6baab8 in testing::Test::Run (this=0xaaaaae347840) at gtest.cc:2508
#25 0x0000aaaaab6bb3e4 in testing::TestInfo::Run (this=0xaaaaac87de80) at gtest.cc:2687
#26 0x0000aaaaab6bbb08 in testing::TestSuite::Run (this=0xaaaaac85dd20) at gtest.cc:2819
#27 0x0000aaaaab6c6788 in testing::internal::UnitTestImpl::RunAllTests (this=0xaaaaabbe0900) at gtest.cc:5350
#28 0x0000aaaaab6d7280 in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0xaaaaabbe0900,
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0xaaaaab6c63a8 <testing::internal::UnitTestImpl::RunAllTests()
>, location=0xaaaaab782508 "auxiliary test code (environments or event listeners)") at gtest.cc:2433
#29 0x0000aaaaab6d2550 in testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0xaaaaabbe0900,
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0xaaaaab6c63a8 <testing::internal::UnitTestImpl::RunAllTests()
>, location=0xaaaaab782508 "auxiliary test code (environments or event listeners)") at gtest.cc:2469
#30 0x0000aaaaab6c51d4 in testing::UnitTest::Run (this=0xaaaaabbcb450 <testing::UnitTest::GetInstance()::instance>) at gtest.cc:4937
#31 0x0000aaaaaada9d9c in RUN_ALL_TESTS () at common/googletest/gtest.h:2473
#32 0x0000aaaaaada98c8 in main (argc=1, argv=0xfffffffff218) at common/main.cc:118
(gdb) f 4
#4  0x0000fffff7c9f240 in ucp_ep_destroy_base (ep=0xfffff2447c00) at core/ucp_ep.c:328
328         ucs_callbackq_remove_if(&ep->worker->uct->progress_q, ucp_ep_remove_filter,
(gdb) p ep->worker
$1 = (ucp_worker_h) 0xfffff2447980
(gdb) p ep->worker->uct
$2 = (uct_worker_h) 0x0
(gdb) p ep->refcount
$3 = 0 '\000'
(gdb) f 5
#5  0x0000fffff7d2c960 in ucp_worker_flush_req_set_next_ep (next_ep_iter=0xaaaaae369328, is_current_ep_valid=1, req=0xaaaaad8a5f00) at rma/flush.c:441
441         return ucp_ep_refcount_remove(current_ep, flush) ? NULL : current_ep;
(gdb) p worker
$4 = (ucp_worker_h) 0xaaaaae3691b0
```
