### ISSUE TITLE
Segmentation fault with UCX v1.12.1 with OpenMPI v5.0.x

### ISSUE THREAD

**Issue by awlauria** [openucx/ucx#8100]
### Describe the bug

I am able to hit a consistent segv with UCX v1.12.1 with a simple MPI init/finalize app. The segv happens in `MPI_Init()` with OMPI `main` or `v5.0.x` branches, I have not tried with the `v4` series. The issue does not reproduce with UCX `v1.11.2`.

The segv only happens when passing nothing to the configure line except `--prefix`. Configuring with `contrib/configure-release` will not reproduce the segv.

### Steps to Reproduce
- `mpirun --np 1 ./hello_world`
- Build/configuration:
```
# UCT version=1.12.1 revision dc92435
# configured with: --prefix=/path/to/local/dir
```

### Setup and versions
- OS version `RHEL 8.4 ppc64le`
- For RDMA/IB/RoCE related issues:
    - Driver version:
        - `MLNX_OFED_LINUX-4.9-4.1.1.1`, driver version: `16.32.1010`

### Additional information (depending on the issue)
- OpenMPI version: `main` or `v5.0.x`. Have not tried v4 series.
- Output of `ucx_info -d` to show transports and devices recognized by UCX. See attached.
- Configure result - config.log. See attached.

- Backtrace/signature

The issue will happen every time on a single rank MPI hello world app - or a simple Init/finalize. The segv happens in `MPI_Init()`:

```
$. mpirun --np 1 ./hello
Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
==== backtrace (tid:2482046) ====
 0  /u/awlauria/ucx-1.12.1/exports/lib/libucs.so.0(ucs_handle_error+0x374) [0x200000b5b984]
 1  /u/awlauria/ucx-1.12.1/exports/lib/libucs.so.0(+0x3bb50) [0x200000b5bb50]
 2  /u/awlauria/ucx-1.12.1/exports/lib/libucs.so.0(+0x3bf80) [0x200000b5bf80]
 3  linux-vdso64.so.1(__kernel_sigtramp_rt64+0) [0x2000000604d8]
 4  /u/awlauria/ucx-1.12.1/exports/lib/ucx/libuct_ib.so.0(+0x9652c) [0x200002d3652c]
 5  /u/awlauria/ucx-1.12.1/exports/lib/ucx/libuct_ib.so.0(+0x81a84) [0x200002d21a84]
 6  /u/awlauria/ucx-1.12.1/exports/lib/libucs.so.0(+0x16254) [0x200000b36254]
 7  /u/awlauria/ucx-1.12.1/exports/lib/libucs.so.0(+0x1648c) [0x200000b3648c]
 8  /u/awlauria/ucx-1.12.1/exports/lib/libucs.so.0(ucs_async_dispatch_handlers+0x88) [0x200000b37738]
 9  /u/awlauria/ucx-1.12.1/exports/lib/libucs.so.0(+0x1ca54) [0x200000b3ca54]
10  /u/awlauria/ucx-1.12.1/exports/lib/libucs.so.0(ucs_event_set_wait+0x12c) [0x200000b695ec]
11  /u/awlauria/ucx-1.12.1/exports/lib/libucs.so.0(+0x1cd34) [0x200000b3cd34]
12  /usr/lib64/power9/libpthread.so.0(+0x87c8) [0x2000005087c8]
13  /usr/lib64/power9/libc.so.6(clone+0x74) [0x2000006801b8]
=================================
```
core file backtrace:
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/power9/libthread_db.so.1".
Missing separate debuginfo for /lib/libgpfs.so
Core was generated by `./hello '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000200002d3652c in uct_ib_mlx5_update_db_cq_ci (cq=0x48aeaf88) at /usr/include/bits/byteswap.h:52
52	  return __builtin_bswap32 (__bsx);
[Current thread is 1 (Thread 0x2000034cef50 (LWP 2482046))]
bMissing separate debuginfos, use: yum debuginfo-install glibc-2.28-151.el8.ppc64le libblkid-2.32.1-27.el8.ppc64le libevent-2.1.8-5.el8.ppc64le libgcc-8.4.1-1.el8.ppc64le libibverbs-41mlnx1-OFED.4.9.3.0.0.49411.ppc64le libmlx4-41mlnx1-OFED.4.7.3.0.3.49411.ppc64le libmlx5-41mlnx1-OFED.4.9.0.1.2.49411.ppc64le libmount-2.32.1-27.el8.ppc64le libnl3-3.5.0-1.el8.ppc64le librdmacm-41mlnx1-OFED.4.7.3.0.6.49411.ppc64le libselinux-2.9-5.el8.ppc64le libuuid-2.32.1-27.el8.ppc64le numactl-libs-2.0.12-11.el8.ppc64le openssl-libs-1.1.1g-15.el8_3.ppc64le pcre2-10.32-2.el8.ppc64le systemd-libs-239-45.el8_4.6.ppc64le zlib-1.2.11-17.el8.ppc64le
(gdb) bt
#0  0x0000200002d3652c in uct_ib_mlx5_update_db_cq_ci (cq=0x48aeaf88) at /usr/include/bits/byteswap.h:52
#1  uct_ud_mlx5_iface_poll_rx (is_async=1, iface=0x48aea7b0) at ud/accel/ud_mlx5.c:514
#2  uct_ud_mlx5_iface_async_progress (ud_iface=0x48aea7b0) at ud/accel/ud_mlx5.c:580
#3  0x0000200002d21a84 in uct_ud_iface_async_progress (iface=<optimized out>) at ud/base/ud_iface.c:254
#4  uct_ud_iface_async_handler (fd=<optimized out>, events=<optimized out>, arg=<optimized out>) at ud/base/ud_iface.c:265
#5  0x0000200000b36254 in ucs_async_handler_invoke (handler=handler@entry=0x48a585a0, events=events@entry=1 '\001') at async/async.c:251
#6  0x0000200000b3648c in ucs_async_handler_dispatch (handler=0x48a585a0, events=events@entry=1 '\001') at async/async.c:273
#7  0x0000200000b37738 in ucs_async_dispatch_handlers (handler_ids=0x2000034ce290, count=1, events=<optimized out>) at async/async.c:305
#8  0x0000200000b3ca54 in ucs_async_thread_ev_handler (callback_data=<optimized out>, events=<optimized out>, arg=0x2000034ce4f0)
    at async/thread.c:87
#9  0x0000200000b695ec in ucs_event_set_wait (event_set=0x48634a50, num_events=0x2000034ce500, timeout_ms=<optimized out>, 
    event_set_handler=0x200000b3c9f0 <ucs_async_thread_ev_handler>, arg=0x2000034ce4f0) at sys/event_set.c:215
#10 0x0000200000b3cd34 in ucs_async_thread_func (arg=0x48634a00) at async/thread.c:130
#11 0x00002000005087c8 in start_thread () from /usr/lib64/power9/libpthread.so.0
#12 0x00002000006801b8 in clone () from /usr/lib64/power9/libc.so.6
(gdb) info threads
  Id   Target Id                           Frame 
* 1    Thread 0x2000034cef50 (LWP 2482046) 0x0000200002d3652c in uct_ib_mlx5_update_db_cq_ci (cq=0x48aeaf88)
    at /usr/include/bits/byteswap.h:52
  2    Thread 0x200001ecef50 (LWP 2482045) 0x000020000068068c in epoll_wait () from /usr/lib64/power9/libc.so.6
  3    Thread 0x20000005d580 (LWP 2482044) 0x0000200000512c40 in .annobin_pthread_spin_lock.end () from /usr/lib64/power9/libpthread.so.0
(gdb) thread 3
[Switching to thread 3 (Thread 0x20000005d580 (LWP 2482044))]
#0  0x0000200000512c40 in .annobin_pthread_spin_lock.end () from /usr/lib64/power9/libpthread.so.0
(gdb) bt
#0  0x0000200000512c40 in .annobin_pthread_spin_lock.end () from /usr/lib64/power9/libpthread.so.0
#1  0x0000200002d35f74 in ucs_spin_lock (lock=0x48942238) at /u/awlauria/ucx-1.12.1/src/ucs/type/spinlock.h:95
#2  ucs_recursive_spin_lock (lock=0x48942238) at /u/awlauria/ucx-1.12.1/src/ucs/type/spinlock.h:95
#3  uct_ud_enter (iface=0x48aea7b0) at /u/awlauria/ucx-1.12.1/src/uct/ib/ud/base/ud_iface.h:377
#4  uct_ud_mlx5_iface_progress (tl_iface=0x48aea7b0) at ud/accel/ud_mlx5.c:554
#5  0x0000200000b491b0 in ucs_callbackq_slow_proxy (arg=0x48a60c80) at datastruct/callbackq.c:404
#6  0x00002000009a4124 in ucs_callbackq_dispatch (cbq=<optimized out>) at /u/awlauria/ucx-1.12.1/src/ucs/datastruct/callbackq.h:211
#7  uct_worker_progress (worker=<optimized out>) at /u/awlauria/ucx-1.12.1/src/uct/api/uct.h:2589
#8  ucp_worker_progress (worker=0x48942230) at core/ucp_worker.c:2636
#9  0x00002000003a4434 in mca_pml_ucx_progress () from /u/awlauria/openmpi-5.0.0rc4/exports/lib/libmpi.so.80
#10 0x00002000007e74ec in opal_progress () from /u/awlauria/openmpi-5.0.0rc4/exports/lib/libopen-pal.so.80
#11 0x000020000017ff2c in ompi_mpi_instance_init_common () from /u/awlauria/openmpi-5.0.0rc4/exports/lib/libmpi.so.80
#12 0x0000200000180008 in ompi_mpi_instance_init () from /u/awlauria/openmpi-5.0.0rc4/exports/lib/libmpi.so.80
#13 0x000020000015e12c in ompi_mpi_init () from /u/awlauria/openmpi-5.0.0rc4/exports/lib/libmpi.so.80
#14 0x00002000001bb8f0 in PMPI_Init () from /u/awlauria/openmpi-5.0.0rc4/exports/lib/libmpi.so.80
#15 0x00000000100009bc in main (argc=1, argv=0x7ffff364da28) at hello_c.c:18
(gdb) 
```

Attached is the config.log output and the output of `ucx_info -d`
[ucx_d.txt](https://github.com/openucx/ucx/files/8427240/ucx_d.txt)

[config.log](https://github.com/openucx/ucx/files/8427232/config.log)

**Comment by yosefe** [comment]
@awlauria latest UCX releases no longer support MLNX_OFED_LINUX-4.x versions.
is it feasible to upgrader to MLNX_OFED 5.x series?

**Comment by awlauria** [comment]
Thanks for the quick response @yosefe . Not for these machines, no. We keep them at the current 4.9 levels.

If it's not supported I don't mind closing this issue. However, it could be a real bug considering the difference in configure line is what causes it to manifest. configure-release only adds ```--disable-logging --disable-debug --disable-assertions --disable-params-check ```

**Comment by shamisp** [comment]
@yosefe Also, IMHO it should not segfaul in a runtime - configure or runtime should detect and complain about older version. If it works with one configure and does not work with another, it is definitely a but.

**Comment by yosefe** [comment]
@Artemy-Mellanox can you pls add a minimal change that disables mlx5 over exp verbs during configure time?
cc @gleon99

**Comment by yosefe** [comment]
regarding this specific issue - it's a debugging code that was added recently (to detect CQ overrun)

**Comment by jjhursey** [comment]
I've hit this too. I would have thought that configure would tell me that this configuration is not supported rather than a segv at runtime.

Can you all clarify the last release UCX release that supports MOFED 4.9? Is it UCX 1.11?

**Comment by yosefe** [comment]
> Can you all clarify the last release UCX release that supports MOFED 4.9? Is it UCX 1.11?

It's UCX v1.10.
