### ISSUE TITLE
Segfault in `uct_rc_mlx5_txqp_process_tx_cqe` with UCX v1.13.x

### ISSUE THREAD

**Issue by wence-** [openucx/ucx#8461]
### Describe the bug

When running on 64 GPUs, I consistently see a segfault due to null pointer dereference in `uct_rc_mlx5_txqp_process_tx_cqe` when running python code using dask and UCX-Py.

Backtrace:
```
#1  0x00001525e5d6d195 in ucs_debug_freeze () at /root/ucx/contrib/../src/ucs/debug/debug.c:818
#2  0x00001525e5d700f4 in ucs_error_freeze (message=0x1525e5d8daa3 "address not mapped to object") at /root/ucx/contrib/../src/ucs/debug/debug.c:921
#3  ucs_handle_error (message=0x1525e5d8daa3 "address not mapped to object") at /root/ucx/contrib/../src/ucs/debug/debug.c:1084
#4  ucs_handle_error (message=0x1525e5d8daa3 "address not mapped to object") at /root/ucx/contrib/../src/ucs/debug/debug.c:1072
#5  0x00001525e5d702ff in ucs_debug_handle_error_signal (signo=signo@entry=11, cause=0x1525e5d8daa3 "address not mapped to object", fmt=fmt@entry=0x1525e5d8db45 " at address %p")
    at /root/ucx/contrib/../src/ucs/debug/debug.c:1033
#6  0x00001525e5d70634 in ucs_error_signal_handler (signo=11, info=0x1525e5cd55f0, context=<optimized out>) at /root/ucx/contrib/../src/ucs/debug/debug.c:1055
#7  <signal handler called>
#8  0x00001525e4293f43 in uct_rc_mlx5_txqp_process_tx_cqe (hw_ci=0, cqe=0x1525d916a7c0, txqp=0x8) at /root/ucx/contrib/../src/uct/ib/rc/accel/rc_mlx5.inl:41
#9  uct_rc_mlx5_iface_poll_tx (iface=0x55fdeab1a0c0) at /root/ucx/contrib/../src/uct/ib/rc/accel/rc_mlx5_iface.c:166
#10 uct_rc_mlx5_iface_progress (flags=2, arg=0x55fdeab1a0c0) at /root/ucx/contrib/../src/uct/ib/rc/accel/rc_mlx5_iface.c:186
#11 uct_rc_mlx5_iface_progress_cyclic (arg=0x55fdeab1a0c0) at /root/ucx/contrib/../src/uct/ib/rc/accel/rc_mlx5_iface.c:191
#12 0x00001525e5dedf1a in ucs_callbackq_dispatch (cbq=<optimized out>) at /root/ucx/contrib/../src/ucs/datastruct/callbackq.h:211
#13 uct_worker_progress (worker=<optimized out>) at /root/ucx/contrib/../src/uct/api/uct.h:2638
#14 ucp_worker_progress (worker=0x55fdea841060) at /root/ucx/contrib/../src/ucp/core/ucp_worker.c:2782
#15 0x00001525e5e9dfe1 in __pyx_pw_3ucp_5_libs_7ucx_api_9UCXWorker_9progress ()
   from /opt/conda/envs/ucx/lib/python3.8/site-packages/ucp/_libs/ucx_api.cpython-38-x86_64-linux-gnu.so
```

And:
```
(gdb) f 9
#9  uct_rc_mlx5_iface_poll_tx (iface=0x55fdeab1a0c0) at /root/ucx/contrib/../src/uct/ib/rc/accel/rc_mlx5_iface.c:166
166         uct_rc_mlx5_txqp_process_tx_cqe(&ep->super.txqp, cqe, hw_ci);
(gdb) p ep
$16 = (uct_rc_mlx5_ep_t *) 0x0
```

Bisection points to c9d7b8ea9368dc7fd6d050adc5005e3f77a71d10 (#7919).

### Steps to Reproduce

Reproduction is a little tricky (since I don't think I can do so purely with ucx components), but can provide instructions.

@dmitrygx proposes this patch on top of c9d7b8ea9368dc7fd6d050adc5005e3f77a71d10 which allows the code to run successfully.

```diff
diff --git a/src/ucp/wireup/wireup_ep.c b/src/ucp/wireup/wireup_ep.c
index 050efe5..63fbd30 100644
--- a/src/ucp/wireup/wireup_ep.c
+++ b/src/ucp/wireup/wireup_ep.c
@@ -476,21 +476,24 @@ static UCS_CLASS_CLEANUP_FUNC(ucp_wireup_ep_t)
     uct_worker_progress_unregister_safe(worker->uct, &self->progress_id);

     if (self->aux_ep != NULL) {
-        /* No pending operations should be scheduled */
-        uct_ep_pending_purge(self->aux_ep, ucp_destroyed_ep_pending_purge,
-                             ucp_ep);
-        ucp_ep_unprogress_uct_ep(ucp_ep, self->aux_ep, self->aux_rsc_index);
-        uct_ep_destroy(self->aux_ep);
+        /* Discard AUX UCT EP to purge all outstanding/pending operations.
+         * Normally, WIREUP EP should complete all outstanding operations prior
+         * destroying WIREUP EP - so, doing flush(CANCEL) won't take any affect,
+         * but it will make sure that no completions will be received if some
+         * error was detected.
+         * Note: No pending operations should be scheduled */
+        ucp_wireup_ep_discard_aux_ep(self, UCT_FLUSH_FLAG_CANCEL,
+                                     ucp_destroyed_ep_pending_purge, ucp_ep);
         self->aux_ep = NULL;
     }

     if (self->super.is_owner && (self->super.uct_ep != NULL)) {
         /* No pending operations should be scheduled */
-        uct_ep_pending_purge(self->super.uct_ep,
-                             ucp_destroyed_ep_pending_purge, ucp_ep);
-        ucp_ep_unprogress_uct_ep(ucp_ep, self->super.uct_ep,
-                                 self->super.rsc_index);
-        uct_ep_destroy(self->super.uct_ep);
+        ucp_worker_discard_uct_ep(self->super.ucp_ep, self->super.uct_ep,
+                                  self->super.rsc_index, UCT_FLUSH_FLAG_CANCEL,
+                                  ucp_destroyed_ep_pending_purge, ucp_ep,
+                                  (ucp_send_nbx_callback_t)ucs_empty_function,
+                                  NULL);
         ucp_proxy_ep_set_uct_ep(&self->super, NULL, 0, UCP_NULL_RESOURCE);
     }
```

**Comment by wence-** [comment]
Thanks @dmitrygx!
