### ISSUE TITLE
Segfault in thread sanitizer during thread join with UCX_MEM_MMAP_HOOK_MODE=bistro

### ISSUE THREAD

**Issue by PeterGottesman** [openucx/ucx#8475]
### Describe the bug
When running an application compiled using thread sanitizer, a segfault occurs when a thread is joined. 

### Steps to Reproduce
Using the conda-forge distributed `ucx` version with no UCX environment variables set:
```
$ ucx_info -v; ucx_info -c | grep HOOK_MODE
# UCT version=1.12.1 revision 5b3a1d3
# configured with: --build=x86_64-conda-linux-gnu --host=x86_64-conda-linux-gnu --prefix=<snip> --with-sysroot --enable-cma --enable-mt --enable-numa --with-gnu-ld --with-verbs --with-cuda=/usr/local/cuda
UCX_MEM_MMAP_HOOK_MODE=bistro
UCX_MEM_CUDA_HOOK_MODE=bistro
```

Minimal reproducer:
```C++
// Compiled with `gcc -isystem $CONDA_PREFIX/include -g -pthread -lucp --sanitize=thread ucx_san.c -o ucx_san`
#include <pthread.h>
#include <ucp/api/ucp.h>

void *nop(void *unused) {}
int main() {
        ucp_config_t* config;
        ucp_params_t params;
        ucp_context_h ctx;

        params.field_mask = 0;

        ucp_config_read(NULL, NULL, &config);
        ucp_init(&params, config, &ctx);

        pthread_t thread;
        pthread_create(&thread, NULL, &nop, NULL);
        pthread_join(thread, NULL);
}
```

This segfaults when run, the stacktrace shows that occurs when thread sanitizer intercepts an rwlock acquisition in UCM during thread join:
```
(gdb) bt
#0  __tsan::Callback::Callback (this=0x7fffea3fd138, thr=0x7fffea3fdac0, pc=140737342530991) at ../../../../libsanitizer/tsan/tsan_rtl.h:431
#1  0x00007ffff7533980 in __tsan::MutexPreReadLock (thr=thr@entry=0x7fffea3fdac0, pc=pc@entry=140737342530991, addr=addr@entry=140737335138912, flagz=3930050872, flagz@entry=0)
    at ../../../../libsanitizer/tsan/tsan_rtl_mutex.cpp:261
#2  0x00007ffff74ee60b in __interceptor_pthread_rwlock_rdlock (m=m@entry=0x7ffff6de1a60 <ucm_event_lock>) at ../../../../libsanitizer/tsan/tsan_interceptors_posix.cpp:1332
#3  0x00007ffff6dcb899 in ucm_event_enter () at event/event.c:161
#4  0x00007ffff6dcc96a in ucm_madvise (addr=0x7fffe9c3d000, length=8110080, advice=4) at event/event.c:441
#5  0x00007ffff71f1c61 in advise_stack_range (guardsize=<optimized out>, pd=140737123702336, size=<optimized out>, mem=0x7fffe9c3d000) at ./nptl/allocatestack.c:195
#6  start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:551
#7  0x00007ffff7283a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

(gdb) thread apply 1 bt
Thread 1 (Thread 0x7ffff6dc2340 (LWP 994343) "ucx_san_c"):
#0  __futex_abstimed_wait_common64 (private=128, cancel=true, abstime=0x0, op=265, expected=994348, futex_word=0x7fffea43d910) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=128, abstime=0x0, clockid=0, expected=994348, futex_word=0x7fffea43d910) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x7fffea43d910, expected=994348, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=128) at ./nptl/futex-internal.c:139
#3  0x00007ffff71f36a4 in __pthread_clockjoin_ex (threadid=140737123702336, thread_return=0x0, clockid=0, abstime=0x0, block=<optimized out>) at ./nptl/pthread_join_common.c:105
#4  0x00007ffff7508e42 in __interceptor_pthread_join (th=0x7fffea43d640, ret=0x0) at ../../../../libsanitizer/tsan/tsan_interceptors_posix.cpp:1021
#5  0x0000555555555294 in main ()
```

This will not segfault if `UCX_MEM_MMAP_HOOK_MODE` is not `bistro` (i.e. it is `reloc` or `none`), or if the hooks are disabled via UCX_MEM_EVENTS=no`. 

### Setup and versions
On Ubuntu 22.04.1 in a conda environment  - 
```
$ ucx_info -v
# UCT version=1.12.1 revision 5b3a1d3
# configured with: --build=x86_64-conda-linux-gnu --host=x86_64-conda-linux-gnu --prefix=<snip> --with-sysroot --enable-cma --enable-mt --enable-numa --with-gnu-ld --with-verbs --with-cuda=/usr/local/cuda
```

**Comment by MattBBaker** [comment]
Wanted to mention I ran into this too
