### ISSUE TITLE
Possible regression triggering assertion in `uct_ud_ep_process_ack`

### ISSUE THREAD

**Issue by planetA** [openucx/ucx#8743]
### Describe the bug

When launching an application with more than 64 processes, UCX triggers an assertion complaining about wrong PSN number. With less processes the behavior is probabilistic and is not observed with something like 16 processes, suggesting a race condition. Experiments are done with a single machine with 120 cores.

The behavior is only observed with custom libibverbs and Linux kernel that make `ibv_*` calls a bit slower.

The assertion is always triggered in UD transport. With less cores, I observe that instead of assertion, MPI gets stuck in `MPI_Finalize`.

```
mpirun -np 120 ~/nooby/nooby/npb/NPB3.4-MPI/bin/lu.C.x
[nooby-vm0:954564:a:954768]       ud_ep.c:675  Assertion `((int16_t)((ep->tx.acked_psn) - (ep->tx.psn)) < 0)' failed: ep 0x56338f1748c0: flags=0xd9 acked_psn=3 must be smaller than current_psn=3
[nooby-vm0:954515:a:954654]       ud_ep.c:675  Assertion `((int16_t)((ep->tx.acked_psn) - (ep->tx.psn)) < 0)' failed: ep 0x557adbe30df0: flags=0xd8 acked_psn=3 must be smaller than current_psn=3
BFD: DWARF error: section .debug_info is larger than its filesize! (0x93ef57 vs 0x530ea0)

/mnt/adminuser/nooby/nooby/ucx/src/uct/ib/ud/base/ud_ep.c: [ uct_ud_ep_process_ack() ]
      ...
      672     }
      673
      674     ep->tx.acked_psn = ack_psn;
==>   675     ucs_assertv(UCT_UD_PSN_COMPARE(ep->tx.acked_psn, <, ep->tx.psn),
      676                 "ep %p: flags=0x%x acked_psn=%u must be smaller than"
      677                 " current_psn=%u", ep, ep->flags, ep->tx.acked_psn,
      678                 ep->tx.psn);

BFD: DWARF error: section .debug_info is larger than its filesize! (0x93ef57 vs 0x530ea0)

/mnt/adminuser/nooby/nooby/ucx/src/uct/ib/ud/base/ud_ep.c: [ uct_ud_ep_process_ack() ]
      ...
      672     }
      673
      674     ep->tx.acked_psn = ack_psn;
==>   675     ucs_assertv(UCT_UD_PSN_COMPARE(ep->tx.acked_psn, <, ep->tx.psn),
      676                 "ep %p: flags=0x%x acked_psn=%u must be smaller than"
      677                 " current_psn=%u", ep, ep->flags, ep->tx.acked_psn,
      678                 ep->tx.psn);

BFD: DWARF error: section .debug_info is larger than its filesize! (0x93ef57 vs 0x530ea0)
==== backtrace (tid: 954768) ====
 0 0x000000000002f721 uct_ud_ep_process_ack()  /mnt/adminuser/nooby/nooby/ucx/src/uct/ib/ud/base/ud_ep.c:675
 1 0x000000000002f721 uct_ud_ep_process_rx()  /mnt/adminuser/nooby/nooby/ucx/src/uct/ib/ud/base/ud_ep.c:959
 2 0x0000000000035cea uct_ud_verbs_iface_poll_rx()  /mnt/adminuser/nooby/nooby/ucx/src/uct/ib/ud/verbs/ud_verbs.c:412
 3 0x0000000000035cea uct_ud_verbs_iface_async_progress()  /mnt/adminuser/nooby/nooby/ucx/src/uct/ib/ud/verbs/ud_verbs.c:432
 4 0x000000000002876f uct_ud_iface_async_progress()  /mnt/adminuser/nooby/nooby/ucx/src/uct/ib/ud/base/ud_iface.c:254
 5 0x000000000002876f uct_ud_iface_async_handler()  /mnt/adminuser/nooby/nooby/ucx/src/uct/ib/ud/base/ud_iface.c:265
 6 0x00000000000177d8 ucs_async_handler_invoke()  /mnt/adminuser/nooby/nooby/ucx/src/ucs/async/async.c:251
 7 0x00000000000179c1 ucs_async_handler_dispatch()  /mnt/adminuser/nooby/nooby/ucx/src/ucs/async/async.c:273
 8 0x0000000000017b3b ucs_async_dispatch_handlers()  /mnt/adminuser/nooby/nooby/ucx/src/ucs/async/async.c:305
 9 0x000000000001ae62 ucs_async_thread_ev_handler()  /mnt/adminuser/nooby/nooby/ucx/src/ucs/async/thread.c:87
10 0x000000000003a197 ucs_event_set_wait()  /mnt/adminuser/nooby/nooby/ucx/src/ucs/sys/event_set.c:215
11 0x000000000001b062 ucs_async_thread_func()  /mnt/adminuser/nooby/nooby/ucx/src/ucs/async/thread.c:130
12 0x0000000000008609 start_thread()  /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477
13 0x000000000011f133 clone()  ???:0
=================================

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
BFD: DWARF error: section .debug_info is larger than its filesize! (0x93ef57 vs 0x530ea0)
==== backtrace (tid: 954654) ====
 0 0x000000000002f721 uct_ud_ep_process_ack()  /mnt/adminuser/nooby/nooby/ucx/src/uct/ib/ud/base/ud_ep.c:675
 1 0x000000000002f721 uct_ud_ep_process_rx()  /mnt/adminuser/nooby/nooby/ucx/src/uct/ib/ud/base/ud_ep.c:959
 2 0x0000000000035cea uct_ud_verbs_iface_poll_rx()  /mnt/adminuser/nooby/nooby/ucx/src/uct/ib/ud/verbs/ud_verbs.c:412
 3 0x0000000000035cea uct_ud_verbs_iface_async_progress()  /mnt/adminuser/nooby/nooby/ucx/src/uct/ib/ud/verbs/ud_verbs.c:432
 4 0x000000000002876f uct_ud_iface_async_progress()  /mnt/adminuser/nooby/nooby/ucx/src/uct/ib/ud/base/ud_iface.c:254
 5 0x000000000002876f uct_ud_iface_async_handler()  /mnt/adminuser/nooby/nooby/ucx/src/uct/ib/ud/base/ud_iface.c:265
 6 0x00000000000177d8 ucs_async_handler_invoke()  /mnt/adminuser/nooby/nooby/ucx/src/ucs/async/async.c:251
 7 0x00000000000179c1 ucs_async_handler_dispatch()  /mnt/adminuser/nooby/nooby/ucx/src/ucs/async/async.c:273
 8 0x0000000000017b3b ucs_async_dispatch_handlers()  /mnt/adminuser/nooby/nooby/ucx/src/ucs/async/async.c:305
 9 0x000000000001ae62 ucs_async_thread_ev_handler()  /mnt/adminuser/nooby/nooby/ucx/src/ucs/async/thread.c:87
10 0x000000000003a197 ucs_event_set_wait()  /mnt/adminuser/nooby/nooby/ucx/src/ucs/sys/event_set.c:215
11 0x000000000001b062 ucs_async_thread_func()  /mnt/adminuser/nooby/nooby/ucx/src/ucs/async/thread.c:130
12 0x0000000000008609 start_thread()  /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477
13 0x000000000011f133 clone()  ???:0
=================================

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x7f23bc020d21 in ???
#1  0x7f23bc01fef5 in ???
#2  0x7f23bbe5108f in ???
	at /build/glibc-SzIz7B/glibc-2.31/signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
#3  0x7f23bbe5100b in __GI_raise
	at ../sysdeps/unix/sysv/linux/raise.c:51
#4  0x7f23bbe30858 in __GI_abort
	at /build/glibc-SzIz7B/glibc-2.31/stdlib/abort.c:79
#5  0x7f23bbdd051c in ucs_fatal_error_message
	at debug/assert.c:38
#6  0x7f23bbdd0644 in ucs_fatal_error_format
	at debug/assert.c:53
#7  0x7f23bb655720 in uct_ud_ep_process_ack
	at ud/base/ud_ep.c:675
#8  0x7f23bb655720 in uct_ud_ep_process_rx
	at ud/base/ud_ep.c:959
#9  0x7f23bb65bce9 in uct_ud_verbs_iface_poll_rx
	at ud/verbs/ud_verbs.c:412
#10  0x7f23bb65bce9 in uct_ud_verbs_iface_async_progress
	at ud/verbs/ud_verbs.c:432
#11  0x7f23bb64e76e in uct_ud_iface_async_progress
	at ud/base/ud_iface.c:254
#12  0x7f23bb64e76e in uct_ud_iface_async_handler
	at ud/base/ud_iface.c:265
#13  0x7f23bbdbb7d7 in ucs_async_handler_invoke
	at async/async.c:251
#14  0x7f23bbdbb9c0 in ucs_async_handler_dispatch
	at async/async.c:273
#15  0x7f23bbdbbb3a in ucs_async_dispatch_handlers
	at async/async.c:305
#16  0x7f23bbdbee61 in ucs_async_thread_ev_handler
	at async/thread.c:87
#17  0x7f23bbdde196 in ucs_event_set_wait
	at sys/event_set.c:215
#18  0x7f23bbdbf061 in ucs_async_thread_func
	at async/thread.c:130
#19  0x7f23bc324608 in start_thread
	at /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477
#20  0x7f23bbf2d132 in ???
	at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
#21  0xffffffffffffffff in ???
#0  0x7f721a820d21 in ???
#1  0x7f721a81fef5 in ???
#2  0x7f721a65108f in ???
	at /build/glibc-SzIz7B/glibc-2.31/signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
#3  0x7f721a65100b in __GI_raise
	at ../sysdeps/unix/sysv/linux/raise.c:51
#4  0x7f721a630858 in __GI_abort
	at /build/glibc-SzIz7B/glibc-2.31/stdlib/abort.c:79
#5  0x7f7219fa751c in ucs_fatal_error_message
	at debug/assert.c:38
#6  0x7f7219fa7644 in ucs_fatal_error_format
	at debug/assert.c:53
#7  0x7f7219296720 in uct_ud_ep_process_ack
	at ud/base/ud_ep.c:675
#8  0x7f7219296720 in uct_ud_ep_process_rx
	at ud/base/ud_ep.c:959
#9  0x7f721929cce9 in uct_ud_verbs_iface_poll_rx
	at ud/verbs/ud_verbs.c:412
#10  0x7f721929cce9 in uct_ud_verbs_iface_async_progress
	at ud/verbs/ud_verbs.c:432
#11  0x7f721928f76e in uct_ud_iface_async_progress
	at ud/base/ud_iface.c:254
#12  0x7f721928f76e in uct_ud_iface_async_handler
	at ud/base/ud_iface.c:265
#13  0x7f7219f927d7 in ucs_async_handler_invoke
	at async/async.c:251
#14  0x7f7219f929c0 in ucs_async_handler_dispatch
	at async/async.c:273
#15  0x7f7219f92b3a in ucs_async_dispatch_handlers
	at async/async.c:305
#16  0x7f7219f95e61 in ucs_async_thread_ev_handler
	at async/thread.c:87
#17  0x7f7219fb5196 in ucs_event_set_wait
	at sys/event_set.c:215
#18  0x7f7219f96061 in ucs_async_thread_func
	at async/thread.c:130
#19  0x7f721aadd608 in start_thread
	at /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477
#20  0x7f721a72d132 in ???
	at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
#21  0xffffffffffffffff in ???


 NAS Parallel Benchmarks 3.4 -- LU Benchmark

 Size:  162x 162x 162  (class C)
 Iterations:  250
 Total number of processes:    120

 Proc_grid for nprocs =   120:   12 x   10

--------------------------------------------------------------------------
prterun noticed that process rank 31 with PID 0 on node nooby-vm0 exited on signal 6 (Aborted).
--------------------------------------------------------------------------
```

### Steps to Reproduce
- Command line

```
~/nooby/nooby/openmpi-install/bin/mpirun -np 120 ~/nooby/nooby/npb/NPB3.4-MPI/bin/lu.C.x
```
 
- UCX version used

```
$ ~/nooby/nooby/ucx-install/bin/ucx_info -v
# Version 1.13.0
# Git branch '', revision 4eddc1b
# Configured with: --without-mlx5-dv --disable-cma --without-devx --with-rdmacm=no --enable-compiler-opt --enable-optimizations --with-verbs=/home/adminuser/nooby/nooby/rdma-core-install --with-rdmacm=/home/adminuser/nooby/nooby/rdma-core-install --prefix=/home/adminuser/nooby/nooby/ucx-install
```

Git bisect points to commit 4eddc1b508326a3a55b92d839de5d5a66e895468 as the root cause.

### Setup and versions

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```

Kernel is based on linux 6.0.0-rc7 x86_64 CPU

Rdma-core based on v42.0

```
$ ibv_devinfo
hca_id:	mlx5_0
	transport:			InfiniBand (0)
	fw_ver:				20.31.1014
	node_guid:			0015:5dff:fe33:ff31
	sys_image_guid:			1c34:da03:0071:3c02
	vendor_id:			0x02c9
	vendor_part_id:			4124
	hw_ver:				0x0
	board_id:			MT_0000000223
	phys_port_cnt:			1
	max_mr_size:			0xffffffffffffffff
	page_size_cap:			0xfffffffffffff000
	max_qp:				262144
	max_qp_wr:			32768
	device_cap_flags:		0x21361c36
					BAD_PKEY_CNTR
					BAD_QKEY_CNTR
					AUTO_PATH_MIG
					CHANGE_PHY_PORT
					PORT_ACTIVE_EVENT
					SYS_IMAGE_GUID
					RC_RNR_NAK_GEN
					MEM_WINDOW
					UD_IP_CSUM
					XRC
					MEM_MGT_EXTENSIONS
					MEM_WINDOW_TYPE_2B
					MANAGED_FLOW_STEERING
	max_sge:			30
	max_sge_rd:			30
	max_cq:				16777216
	max_cqe:			4194303
	max_mr:				16777216
	max_pd:				8388608
	max_qp_rd_atom:			16
	max_ee_rd_atom:			0
	max_res_rd_atom:		4194304
	max_qp_init_rd_atom:		16
	max_ee_init_rd_atom:		0
	atomic_cap:			ATOMIC_HCA (1)
	max_ee:				0
	max_rdd:			0
	max_mw:				16777216
	max_raw_ipv6_qp:		0
	max_raw_ethy_qp:		0
	max_mcast_grp:			2097152
	max_mcast_qp_attach:		240
	max_total_mcast_qp_attach:	503316480
	max_ah:				2147483647
	max_fmr:			0
	max_srq:			8388608
	max_srq_wr:			32767
	max_srq_sge:			31
	max_pkeys:			128
	local_ca_ack_delay:		16
	general_odp_caps:
					ODP_SUPPORT
					ODP_SUPPORT_IMPLICIT
	rc_odp_caps:
					SUPPORT_SEND
					SUPPORT_RECV
					SUPPORT_WRITE
					SUPPORT_READ
					SUPPORT_SRQ
	uc_odp_caps:
					NO SUPPORT
	ud_odp_caps:
					SUPPORT_SEND
	xrc_odp_caps:
					SUPPORT_SEND
					SUPPORT_WRITE
					SUPPORT_READ
					SUPPORT_SRQ
	completion timestamp_mask:			0x7fffffffffffffff
	hca_core_clock:			156250kHZ
	device_cap_flags_ex:		0x1021361C36
					PCI_WRITE_END_PADDING
	tso_caps:
		max_tso:			0
	rss_caps:
		max_rwq_indirection_tables:			0
		max_rwq_indirection_table_size:			0
		rx_hash_function:				0x0
		rx_hash_fields_mask:				0x0
	max_wq_type_rq:			0
	packet_pacing_caps:
		qp_rate_limit_min:	0kbps
		qp_rate_limit_max:	0kbps
	max_rndv_hdr_size:		0
	max_num_tags:			127
	max_ops:			32768
	max_sge:			1
	flags:

	cq moderation caps:
		max_cq_count:	65535
		max_cq_period:	4095 us

	num_comp_vectors:		19
		port:	1
			state:			PORT_ACTIVE (4)
			max_mtu:		4096 (5)
			active_mtu:		4096 (5)
			sm_lid:			338
			port_lid:		636
			port_lmc:		0x00
			link_layer:		InfiniBand
			max_msg_sz:		0x40000000
			port_cap_flags:		0x2251ec48
			port_cap_flags2:	0x0032
			max_vl_num:		4 (3)
			bad_pkey_cntr:		0x0
			qkey_viol_cntr:		0x0
			sm_sl:			0
			pkey_tbl_len:		128
			gid_tbl_len:		8
			subnet_timeout:		18
			init_type_reply:	0
			active_width:		4X (2)
			active_speed:		50.0 Gbps (64)
			phys_state:		LINK_UP (5)
			GID[  0]:		fe80:0000:0000:0000:0015:5dff:fd33:ff31
```

### Additional information (depending on the issue)
- OpenMPI version

```
ompi_info --version
Open MPI v5.0.0rc9
```

- Output of `ucx_info -d` to show transports and devices recognized by UCX

```
ucx_info -d
#
# Memory domain: self
#     Component: self
#             register: unlimited, cost: 0 nsec
#           remote key: 0 bytes
#
#      Transport: self
#         Device: memory0
#           Type: loopback
#  System device: <unknown>
#
#      capabilities:
#            bandwidth: 0.00/ppn + 6911.00 MB/sec
#              latency: 0 nsec
#             overhead: 10 nsec
#            put_short: <= 4294967295
#            put_bcopy: unlimited
#            get_bcopy: unlimited
#             am_short: <= 8K
#             am_bcopy: <= 8K
#               domain: cpu
#           atomic_add: 32, 64 bit
#           atomic_and: 32, 64 bit
#            atomic_or: 32, 64 bit
#           atomic_xor: 32, 64 bit
#          atomic_fadd: 32, 64 bit
#          atomic_fand: 32, 64 bit
#           atomic_for: 32, 64 bit
#          atomic_fxor: 32, 64 bit
#          atomic_swap: 32, 64 bit
#         atomic_cswap: 32, 64 bit
#           connection: to iface
#      device priority: 0
#     device num paths: 1
#              max eps: inf
#       device address: 0 bytes
#        iface address: 8 bytes
#       error handling: ep_check
#
#
# Memory domain: tcp
#     Component: tcp
#             register: unlimited, cost: 0 nsec
#           remote key: 0 bytes
#
#      Transport: tcp
#         Device: lo
#           Type: network
#  System device: <unknown>
#
#      capabilities:
#            bandwidth: 11.91/ppn + 0.00 MB/sec
#              latency: 10960 nsec
#             overhead: 50000 nsec
#            put_zcopy: <= 18446744073709551590, up to 6 iov
#  put_opt_zcopy_align: <= 1
#        put_align_mtu: <= 0
#             am_short: <= 8K
#             am_bcopy: <= 8K
#             am_zcopy: <= 64K, up to 6 iov
#   am_opt_zcopy_align: <= 1
#         am_align_mtu: <= 0
#            am header: <= 8037
#           connection: to ep, to iface
#      device priority: 1
#     device num paths: 1
#              max eps: 256
#       device address: 18 bytes
#        iface address: 2 bytes
#           ep address: 10 bytes
#       error handling: peer failure, ep_check, keepalive
#
#      Transport: tcp
#         Device: eth0
#           Type: network
#  System device: <unknown>
#
#      capabilities:
#            bandwidth: 5658.18/ppn + 0.00 MB/sec
#              latency: 5212 nsec
#             overhead: 50000 nsec
#            put_zcopy: <= 18446744073709551590, up to 6 iov
#  put_opt_zcopy_align: <= 1
#        put_align_mtu: <= 0
#             am_short: <= 8K
#             am_bcopy: <= 8K
#             am_zcopy: <= 64K, up to 6 iov
#   am_opt_zcopy_align: <= 1
#         am_align_mtu: <= 0
#            am header: <= 8037
#           connection: to ep, to iface
#      device priority: 0
#     device num paths: 1
#              max eps: 256
#       device address: 6 bytes
#        iface address: 2 bytes
#           ep address: 10 bytes
#       error handling: peer failure, ep_check, keepalive
#
#
# Connection manager: tcp
#      max_conn_priv: 2064 bytes
#
# Memory domain: sysv
#     Component: sysv
#             allocate: unlimited
#           remote key: 12 bytes
#           rkey_ptr is supported
#
#      Transport: sysv
#         Device: memory
#           Type: intra-node
#  System device: <unknown>
#
#      capabilities:
#            bandwidth: 0.00/ppn + 12179.00 MB/sec
#              latency: 80 nsec
#             overhead: 10 nsec
#            put_short: <= 4294967295
#            put_bcopy: unlimited
#            get_bcopy: unlimited
#             am_short: <= 100
#             am_bcopy: <= 8256
#               domain: cpu
#           atomic_add: 32, 64 bit
#           atomic_and: 32, 64 bit
#            atomic_or: 32, 64 bit
#           atomic_xor: 32, 64 bit
#          atomic_fadd: 32, 64 bit
#          atomic_fand: 32, 64 bit
#           atomic_for: 32, 64 bit
#          atomic_fxor: 32, 64 bit
#          atomic_swap: 32, 64 bit
#         atomic_cswap: 32, 64 bit
#           connection: to iface
#      device priority: 0
#     device num paths: 1
#              max eps: inf
#       device address: 8 bytes
#        iface address: 8 bytes
#       error handling: ep_check
#
#
# Memory domain: posix
#     Component: posix
#             allocate: <= 235268300K
#           remote key: 24 bytes
#           rkey_ptr is supported
#
#      Transport: posix
#         Device: memory
#           Type: intra-node
#  System device: <unknown>
#
#      capabilities:
#            bandwidth: 0.00/ppn + 12179.00 MB/sec
#              latency: 80 nsec
#             overhead: 10 nsec
#            put_short: <= 4294967295
#            put_bcopy: unlimited
#            get_bcopy: unlimited
#             am_short: <= 100
#             am_bcopy: <= 8256
#               domain: cpu
#           atomic_add: 32, 64 bit
#           atomic_and: 32, 64 bit
#            atomic_or: 32, 64 bit
#           atomic_xor: 32, 64 bit
#          atomic_fadd: 32, 64 bit
#          atomic_fand: 32, 64 bit
#           atomic_for: 32, 64 bit
#          atomic_fxor: 32, 64 bit
#          atomic_swap: 32, 64 bit
#         atomic_cswap: 32, 64 bit
#           connection: to iface
#      device priority: 0
#     device num paths: 1
#              max eps: inf
#       device address: 8 bytes
#        iface address: 8 bytes
#       error handling: ep_check
#
#
# Memory domain: mlx5_0
#     Component: ib
#             register: unlimited, cost: 180 nsec
#           remote key: 8 bytes
#           local memory handle is required for zcopy
#           memory invalidation is supported
#
#      Transport: rc_verbs
#         Device: mlx5_0:1
#           Type: network
#  System device: mlx5_0 (0)
#
#      capabilities:
#            bandwidth: 23588.47/ppn + 0.00 MB/sec
#              latency: 600 + 1.000 * N nsec
#             overhead: 75 nsec
#            put_bcopy: <= 8256
#            put_zcopy: <= 1G, up to 8 iov
#  put_opt_zcopy_align: <= 512
#        put_align_mtu: <= 4K
#            get_bcopy: <= 8256
#            get_zcopy: 65..1G, up to 8 iov
#  get_opt_zcopy_align: <= 512
#        get_align_mtu: <= 4K
#             am_bcopy: <= 8255
#             am_zcopy: <= 8255, up to 7 iov
#   am_opt_zcopy_align: <= 512
#         am_align_mtu: <= 4K
#            am header: <= 127
#               domain: device
#           atomic_add: 64 bit
#          atomic_fadd: 64 bit
#         atomic_cswap: 64 bit
#           connection: to ep
#      device priority: 50
#     device num paths: 1
#              max eps: 256
#       device address: 5 bytes
#           ep address: 4 bytes
#       error handling: peer failure, ep_check
#
#
#      Transport: ud_verbs
#         Device: mlx5_0:1
#           Type: network
#  System device: mlx5_0 (0)
#
#      capabilities:
#            bandwidth: 23588.47/ppn + 0.00 MB/sec
#              latency: 630 nsec
#             overhead: 105 nsec
#             am_bcopy: <= 4088
#             am_zcopy: <= 4088, up to 5 iov
#   am_opt_zcopy_align: <= 512
#         am_align_mtu: <= 4K
#            am header: <= 3952
#           connection: to ep, to iface
#      device priority: 50
#     device num paths: 1
#              max eps: inf
#       device address: 5 bytes
#        iface address: 3 bytes
#           ep address: 6 bytes
#       error handling: peer failure, ep_check
#
#
# Connection manager: rdmacm
#      max_conn_priv: 54 bytes
```

**Comment by evgeny-leksikov** [comment]
@planetA can you share custom libibverbs patch? I haven't found a way to reproduce the issue without it.

**Comment by planetA** [comment]
Can we take then this discussion in private then? My email is mplaneta os.inf.tu-dresden.de
